// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zUpdateAdminCashGiftRequest = z.object({
    guest_name: z.string().max(20).optional(),
    amount: z.int().gte(0).optional(),
    recipient_slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ]).optional(),
    relation_category: z.string().optional(),
    relation_detail: z.string().max(40).optional(),
    pay_method: z.enum([
        'transfer',
        'kakaopay',
        'toss',
        'cash'
    ]).optional()
});

export const zUpdateAdminRsvpRequest = z.object({
    guest_name: z.string().max(20).optional(),
    attendance: z.enum(['attending', 'absent']).optional(),
    companion_count: z.int().gte(0).lte(20).optional(),
    meal: z.enum([
        'yes',
        'no',
        'undecided'
    ]).optional(),
    recipient_slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ]).optional(),
    phone_last4: z.string().optional()
});

export const zUpdateAdminHostInviteRequest = z.object({
    status: z.enum([
        'pending',
        'accepted',
        'cancelled'
    ]).optional()
});

export const zUpdateAdminMemoryRequest = z.object({
    text: z.string().min(1).max(80).optional()
});

export const zUpdateAdminGuestbookMessageRequest = z.object({
    message: z.string().min(1).max(70).optional()
});

export const zUpdateAdminGuestbookEntryRequest = z.object({
    guest_name: z.string().max(20).optional(),
    recipient_slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ]).optional(),
    relation_category: z.string().optional(),
    relation_detail: z.string().max(40).optional()
});

export const zUpdateAdminMobileInvitationRequest = z.object({
    custom_message: z.string().optional(),
    design_template_id: z.string().optional(),
    slug: z.string().optional(),
    cover_image: z.string().optional()
});

export const zUpdateAdminUserRequest = z.object({
    name: z.string().optional(),
    phone: z.string().optional(),
    email: z.email().optional(),
    profile_image_url: z.string().optional()
});

export const zUpdateAdminLoungeRequest = z.object({
    name: z.string().optional()
});

export const zUpdateAdminWeddingRequest = z.object({
    groom_name: z.string().optional(),
    bride_name: z.string().optional(),
    date: z.iso.date().optional(),
    time: z.string().optional(),
    venue_name: z.string().optional(),
    venue_address: z.string().optional(),
    venue_hall: z.string().optional(),
    status: z.enum(['active', 'deleted']).optional()
});

export const zFieldError = z.object({
    field: z.string(),
    message: z.string()
});

/**
 * RFC 7807 Problem Details
 */
export const zProblemDetail = z.object({
    type: z.string().default('about:blank'),
    title: z.string(),
    status: z.int(),
    detail: z.string().optional(),
    errors: z.array(zFieldError).optional()
});

export const zVenue = z.object({
    venue_name: z.string(),
    venue_address: z.string(),
    venue_hall: z.string().optional()
});

export const zAccount = z.object({
    bank: z.string().optional(),
    address: z.string().optional()
});

export const zPosition = z.object({
    x: z.number(),
    y: z.number()
});

export const zUser = z.object({
    id: z.uuid(),
    name: z.string(),
    email: z.email(),
    phone: z.string().optional(),
    profile_image_url: z.string().optional(),
    created_at: z.iso.datetime(),
    consents_required: z.array(z.enum([
        'age_verification',
        'service',
        'privacy',
        'marketing'
    ])),
    marketing_agreed: z.boolean()
});

export const zConsentItem = z.object({
    terms_type: z.enum([
        'age_verification',
        'service',
        'privacy',
        'marketing'
    ]),
    agreed: z.boolean()
});

export const zCreateConsentsRequest = z.object({
    items: z.array(zConsentItem)
});

export const zUpdateMarketingConsentRequest = z.object({
    agreed: z.boolean()
});

export const zUserPublic = z.object({
    id: z.uuid(),
    name: z.string(),
    profile_image_url: z.string().optional()
});

export const zUpdateUserRequest = z.object({
    name: z.string().optional(),
    phone: z.string().optional(),
    profile_image_url: z.string().optional()
});

export const zWeddingStatus = z.enum([
    'active',
    'completed',
    'cancelled'
]);

export const zHostSlots = z.object({
    host_groom_id: z.uuid().optional(),
    host_bride_id: z.uuid().optional(),
    host_groom_father_id: z.uuid().optional(),
    host_groom_mother_id: z.uuid().optional(),
    host_bride_father_id: z.uuid().optional(),
    host_bride_mother_id: z.uuid().optional()
});

export const zWeddingInfo = z.object({
    groom_name: z.string(),
    bride_name: z.string(),
    groom_father_name: z.string().optional(),
    groom_mother_name: z.string().optional(),
    bride_father_name: z.string().optional(),
    bride_mother_name: z.string().optional(),
    groom_father_deceased: z.boolean().optional().default(false),
    groom_mother_deceased: z.boolean().optional().default(false),
    bride_father_deceased: z.boolean().optional().default(false),
    bride_mother_deceased: z.boolean().optional().default(false),
    date: z.iso.date(),
    time: z.string(),
    venue: zVenue,
    groom_account: zAccount.optional(),
    bride_account: zAccount.optional(),
    groom_father_account: zAccount.optional(),
    groom_mother_account: zAccount.optional(),
    bride_father_account: zAccount.optional(),
    bride_mother_account: zAccount.optional()
});

export const zUpdateSuiIdsRequest = z.object({
    sui_wedding_id: z.string().nullish(),
    sui_lounge_id: z.string().nullish(),
    sui_vault_id: z.string().nullish()
});

export const zParticipatedWedding = z.object({
    id: z.uuid(),
    groom_name: z.string(),
    bride_name: z.string(),
    date: z.iso.date(),
    time: z.string().optional(),
    venue_name: z.string().optional(),
    venue_hall: z.string().optional(),
    cover_image: z.string().optional(),
    lounge_id: z.uuid()
});

export const zCreateWeddingRequest = z.object({
    info: zWeddingInfo,
    hosts: zHostSlots,
    slug: z.string()
});

export const zUpdateWeddingRequest = z.object({
    info: zWeddingInfo.optional(),
    hosts: zHostSlots.optional(),
    version: z.int().optional()
});

export const zInvitationSummary = z.object({
    id: z.uuid(),
    slug: z.string(),
    cover_image: z.string().optional()
});

export const zWeddingSummary = z.object({
    id: z.uuid(),
    status: zWeddingStatus,
    groom_name: z.string(),
    bride_name: z.string(),
    groom_father_name: z.string().optional(),
    groom_mother_name: z.string().optional(),
    bride_father_name: z.string().optional(),
    bride_mother_name: z.string().optional(),
    date: z.iso.date(),
    time: z.string().optional(),
    venue_name: z.string().optional(),
    venue_hall: z.string().optional(),
    invitations: z.array(zInvitationSummary),
    lounge_id: z.uuid().optional(),
    my_role: z.string().optional()
});

export const zCoverTextConfig = z.object({
    text: z.string().optional(),
    font_size: z.int().optional(),
    x: z.int().optional(),
    y: z.int().optional(),
    rotation: z.int().optional(),
    animation: z.enum([
        'none',
        'fade-in',
        'typing'
    ]).optional(),
    color_type: z.enum(['solid', 'gradient']).optional(),
    solid_color: z.string().optional(),
    gradient_colors: z.array(z.string()).optional()
});

/**
 * 레터링·폰트·색상·섹션 구성
 */
export const zDesignConfig = z.object({
    lettering: z.object({
        source: z.enum([
            'text',
            'upload',
            'draw'
        ]).optional(),
        image_url: z.string().nullish(),
        strokes: z.array(z.object({
            d: z.string().optional(),
            color: z.string().optional(),
            width: z.number().optional(),
            tool: z.enum(['pen', 'brush']).optional(),
            points: z.array(z.object({
                x: z.number().optional(),
                y: z.number().optional(),
                t: z.number().optional()
            })).optional()
        })).optional(),
        draw_view_box: z.object({
            width: z.number().optional(),
            height: z.number().optional()
        }).optional(),
        animation: z.enum([
            'none',
            'fade-in',
            'draw',
            'typing',
            'stroke-order'
        ]).optional(),
        x: z.number().optional(),
        y: z.number().optional(),
        width: z.number().optional(),
        height: z.number().optional(),
        rotation: z.number().optional()
    }).optional(),
    theme: z.object({
        fonts: z.object({
            title: z.string().optional(),
            subtitle: z.string().optional(),
            body: z.string().optional()
        }).optional(),
        colors: z.object({
            background: z.string().optional(),
            text: z.string().optional(),
            button: z.string().optional(),
            accent: z.string().optional()
        }).optional()
    }).optional(),
    sections: z.array(z.object({
        key: z.enum([
            'greeting',
            'weddingDate',
            'location',
            'notice',
            'gallery',
            'account',
            'canvas'
        ]),
        enabled: z.boolean(),
        order: z.int()
    })).optional(),
    canvas: z.object({
        title: z.string().optional(),
        subtitle: z.string().optional(),
        items: z.array(z.object({
            id: z.string().optional(),
            type: z.string().optional(),
            x: z.number().optional(),
            y: z.number().optional(),
            width: z.number().optional(),
            height: z.number().optional(),
            rotation: z.number().optional(),
            z_index: z.int().optional(),
            strokes: z.array(z.object({
                d: z.string().optional(),
                color: z.string().optional(),
                width: z.number().optional(),
                tool: z.string().optional()
            })).optional(),
            view_box: z.object({
                width: z.number().optional(),
                height: z.number().optional()
            }).optional(),
            text: z.string().optional(),
            font_size: z.number().optional(),
            font_family: z.string().optional(),
            color: z.string().optional(),
            image_url: z.string().optional(),
            is_sticker: z.boolean().optional()
        })).optional(),
        background_color: z.string().optional(),
        view_box: z.object({
            width: z.number().optional(),
            height: z.number().optional()
        }).optional()
    }).optional(),
    cover_image_position: z.object({
        cropArea: z.object({
            x: z.number().optional(),
            y: z.number().optional(),
            width: z.number().optional(),
            height: z.number().optional()
        }).optional(),
        zoom: z.number().optional(),
        editorCrop: z.object({
            x: z.number().optional(),
            y: z.number().optional()
        }).optional()
    }).optional()
});

export const zInvitation = z.object({
    id: z.uuid(),
    wedding_id: z.uuid(),
    design_template_id: z.string(),
    custom_message: z.string().optional(),
    visited_count: z.int(),
    heart_count: z.int(),
    gallery_photos: z.array(z.string()).optional(),
    cover_image: z.string().optional(),
    cover_text_config: zCoverTextConfig.optional(),
    design_config: zDesignConfig.optional(),
    slug: z.string(),
    created_at: z.iso.datetime(),
    version: z.int().optional()
});

export const zLoungePreview = z.object({
    lounge_id: z.uuid(),
    lounge_name: z.string(),
    visitor_count: z.int(),
    sui_lounge_id: z.string().nullish()
});

export const zInvitationPublic = z.object({
    wedding_id: z.uuid(),
    design_template_id: z.string(),
    custom_message: z.string().optional(),
    info: zWeddingInfo,
    gallery_photos: z.array(z.string()).optional(),
    cover_image: z.string().optional(),
    cover_text_config: zCoverTextConfig.optional(),
    design_config: zDesignConfig.optional(),
    visited_count: z.int(),
    heart_count: z.int(),
    lounge_preview: zLoungePreview,
    version: z.int().optional()
});

export const zCreateInvitationRequest = z.object({
    slug: z.string(),
    design_template_id: z.string().optional(),
    custom_message: z.string().optional(),
    gallery_photos: z.array(z.string()).optional(),
    cover_image: z.string().optional(),
    cover_text_config: zCoverTextConfig.optional(),
    design_config: zDesignConfig.optional()
});

export const zUpdateInvitationRequest = z.object({
    design_template_id: z.string().optional(),
    custom_message: z.string().optional(),
    gallery_photos: z.array(z.string()).optional(),
    cover_image: z.string().optional(),
    cover_text_config: zCoverTextConfig.optional(),
    design_config: zDesignConfig.optional(),
    version: z.int().optional()
});

export const zHeartResponse = z.object({
    heart_count: z.int()
});

export const zShareLinkResponse = z.object({
    slug: z.string(),
    url: z.string()
});

export const zLoungeSummary = z.object({
    id: z.uuid(),
    name: z.string(),
    gather_place_id: z.uuid().optional(),
    groom_side_guest_count: z.int(),
    bride_side_guest_count: z.int(),
    sui_lounge_id: z.string().nullish()
});

export const zWedding = z.object({
    id: z.uuid(),
    status: zWeddingStatus,
    info: zWeddingInfo,
    hosts: zHostSlots,
    lounge: zLoungeSummary,
    invitations: z.array(zInvitationSummary),
    created_at: z.iso.datetime(),
    version: z.int().optional(),
    sui_wedding_id: z.string().nullish(),
    sui_vault_id: z.string().nullish()
});

export const zGatherPlace = z.object({
    id: z.uuid(),
    lounge_id: z.uuid(),
    type: z.string()
});

export const zGatherPlaceSummary = z.object({
    id: z.uuid(),
    type: z.string()
});

export const zLounge = z.object({
    id: z.uuid(),
    wedding_id: z.uuid(),
    name: z.string(),
    gather_place: zGatherPlaceSummary
});

export const zLoungeCheckIn = z.object({
    id: z.uuid(),
    user_id: z.uuid(),
    lounge_id: z.uuid(),
    visitor_name: z.string().readonly(),
    recipient_slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ]).optional(),
    relation_category: z.enum([
        '가족/친척',
        '친구/지인',
        '동문/동창',
        '직장동료',
        '스승/제자',
        '기타모임'
    ]).optional(),
    relation_detail: z.string().optional(),
    created_at: z.iso.datetime()
});

export const zCreateLoungeCheckInRequest = z.object({
    recipient_slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ]).optional(),
    relation_category: z.enum([
        '가족/친척',
        '친구/지인',
        '동문/동창',
        '직장동료',
        '스승/제자',
        '기타모임'
    ]).optional(),
    relation_detail: z.string().optional()
});

export const zLoungeCheckInListResponse = z.object({
    data: z.array(zLoungeCheckIn),
    next_cursor: z.string().optional(),
    has_more: z.boolean()
});

export const zGuestbookEntry = z.object({
    id: z.uuid(),
    lounge_id: z.uuid(),
    guest_name: z.string(),
    guest_id: z.uuid().optional(),
    recipient_slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ]),
    relation_category: z.enum([
        '가족/친척',
        '친구/지인',
        '동문/동창',
        '직장동료',
        '스승/제자',
        '기타모임'
    ]),
    relation_detail: z.string().max(40).optional(),
    created_at: z.iso.datetime()
});

export const zCreateGuestbookEntryRequest = z.object({
    guest_name: z.string().max(20),
    recipient_slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ]),
    relation_category: z.enum([
        '가족/친척',
        '친구/지인',
        '동문/동창',
        '직장동료',
        '스승/제자',
        '기타모임'
    ]),
    relation_detail: z.string().max(40).optional(),
    message: z.string().max(70).optional()
});

/**
 * LIVE 축하메세지(현장 QR 스캔 전용). 사진은 v3_memories 도메인이 담당.
 */
export const zGuestbookMessage = z.object({
    id: z.uuid(),
    guestbook_entry_id: z.uuid(),
    message: z.string().max(60),
    view_count: z.int().optional(),
    created_at: z.iso.datetime()
});

export const zCreateGuestbookMessageRequest = z.object({
    message: z.string().max(60)
});

/**
 * 라운지 V2 "온기" 게시물. text 필수 + photo 0/1. author_user_id로 식별 (entry 무관).
 */
export const zMemory = z.object({
    id: z.uuid(),
    lounge_id: z.uuid(),
    author_user_id: z.uuid(),
    text: z.string().min(1).max(60),
    photo_url: z.string().nullish(),
    created_at: z.iso.datetime()
});

export const zCreateMemoryRequest = z.object({
    lounge_id: z.uuid(),
    text: z.string().min(1).max(60),
    photo_url: z.string().nullish()
});

export const zMemoryListResponse = z.object({
    data: z.array(zMemory)
});

export const zGuestbookEntryListResponse = z.object({
    data: z.array(zGuestbookEntry),
    next_cursor: z.string().optional(),
    has_more: z.boolean()
});

export const zAnnouncement = z.object({
    id: z.uuid(),
    lounge_id: z.uuid(),
    host_id: z.uuid(),
    message: z.string(),
    is_pinned: z.boolean(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime().optional()
});

export const zCreateAnnouncementRequest = z.object({
    message: z.string().max(100),
    is_pinned: z.boolean().optional().default(false)
});

export const zUpdateAnnouncementRequest = z.object({
    message: z.string().max(100).optional(),
    is_pinned: z.boolean().optional()
});

export const zAnnouncementListResponse = z.object({
    data: z.array(zAnnouncement),
    next_cursor: z.string().optional(),
    has_more: z.boolean()
});

export const zInteriorItemStatus = z.enum(['placed', 'unplaced']);

export const zInteriorItem = z.object({
    id: z.uuid(),
    moi_gather_place_id: z.uuid(),
    name: z.string(),
    type: z.string(),
    size: z.string().optional(),
    image: z.string().optional(),
    status: zInteriorItemStatus,
    position: zPosition.optional(),
    created_at: z.iso.datetime()
});

export const zCreateInteriorItemRequest = z.object({
    name: z.string(),
    type: z.string(),
    size: z.string().optional(),
    image: z.string().optional()
});

export const zMoi = z.object({
    id: z.uuid(),
    user_id: z.uuid(),
    owner_name: z.string().readonly(),
    equipped_items: z.record(z.string(), z.uuid())
});

export const zMoiItem = z.object({
    id: z.uuid(),
    moi_id: z.uuid(),
    name: z.string(),
    type: z.string(),
    slot: z.string(),
    created_at: z.iso.datetime()
});

export const zSendMoiItemRequest = z.object({
    to_moi_id: z.uuid()
});

export const zIum = z.object({
    id: z.uuid(),
    relation_type: z.string(),
    relation_label: z.string(),
    from_user_id: z.uuid(),
    to_user_id: z.uuid(),
    created_at: z.iso.datetime()
});

export const zCreateIumRequest = z.object({
    to_user_id: z.uuid(),
    relation_type: z.string(),
    relation_label: z.string()
});

export const zIumListResponse = z.object({
    data: z.array(zIum),
    next_cursor: z.string().optional(),
    has_more: z.boolean()
});

export const zRsvp = z.object({
    id: z.uuid(),
    wedding_id: z.uuid(),
    recipient_slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ]),
    guest_name: z.string(),
    attendance: z.enum(['attending', 'absent']),
    companion_count: z.int().gte(0),
    meal: z.enum([
        'yes',
        'no',
        'undecided'
    ]),
    phone_last4: z.string().optional(),
    created_at: z.iso.datetime()
});

export const zRsvpListResponse = z.object({
    data: z.array(zRsvp),
    viewer_side: z.enum(['groom', 'bride'])
});

export const zCreateRsvpRequest = z.object({
    recipient_slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ]),
    guest_name: z.string().max(20),
    attendance: z.enum(['attending', 'absent']),
    companion_count: z.int().gte(0).optional().default(0),
    meal: z.enum([
        'yes',
        'no',
        'undecided'
    ]).optional().default('undecided'),
    phone_last4: z.string().optional()
});

export const zCashGift = z.object({
    id: z.uuid(),
    wedding_id: z.uuid(),
    guest_name: z.string(),
    guest_id: z.uuid().optional(),
    recipient_slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ]),
    relation_category: z.enum([
        '가족/친척',
        '친구/지인',
        '동문/동창',
        '직장동료',
        '스승/제자',
        '기타모임'
    ]),
    relation_detail: z.string().max(40).optional(),
    amount: z.int().gte(0),
    pay_method: z.enum([
        'transfer',
        'kakaopay',
        'toss',
        'cash'
    ]),
    attended: z.boolean().readonly(),
    guestbook_entry_id: z.uuid().optional(),
    created_at: z.iso.datetime()
});

export const zCashGiftListResponse = z.object({
    data: z.array(zCashGift),
    next_cursor: z.string().optional(),
    has_more: z.boolean()
});

export const zCashGiftSummary = z.object({
    total_amount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    total_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    attended_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zCreateCashGiftRequest = z.object({
    wedding_id: z.uuid(),
    guest_name: z.string().max(10),
    recipient_slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ]),
    relation_category: z.enum([
        '가족/친척',
        '친구/지인',
        '동문/동창',
        '직장동료',
        '스승/제자',
        '기타모임'
    ]),
    relation_detail: z.string().max(40).optional(),
    amount: z.int().gte(0),
    pay_method: z.enum([
        'transfer',
        'kakaopay',
        'toss',
        'cash'
    ]),
    guestbook_entry_id: z.uuid().optional()
});

export const zHostCreateCashGiftRequest = z.object({
    guest_name: z.string().max(10),
    relation_category: z.enum([
        '가족/친척',
        '친구/지인',
        '동문/동창',
        '직장동료',
        '스승/제자',
        '기타모임'
    ]),
    relation_detail: z.string().max(40).optional(),
    amount: z.int().gte(0),
    pay_method: z.enum([
        'transfer',
        'kakaopay',
        'toss',
        'cash'
    ])
});

export const zUpdateCashGiftRequest = z.object({
    guest_name: z.string().max(10).optional(),
    relation_category: z.enum([
        '가족/친척',
        '친구/지인',
        '동문/동창',
        '직장동료',
        '스승/제자',
        '기타모임'
    ]).optional(),
    relation_detail: z.string().max(40).optional(),
    amount: z.int().gte(0).optional(),
    pay_method: z.enum([
        'transfer',
        'kakaopay',
        'toss',
        'cash'
    ]).optional()
});

export const zHostInvite = z.object({
    id: z.uuid(),
    wedding_id: z.uuid(),
    slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ]),
    token: z.string(),
    status: z.enum([
        'pending',
        'accepted',
        'cancelled'
    ]),
    invited_user_id: z.uuid().optional(),
    created_at: z.iso.datetime(),
    accepted_at: z.iso.datetime().optional()
});

export const zHostInvitePublic = z.object({
    slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ]),
    status: z.enum([
        'pending',
        'accepted',
        'cancelled'
    ]),
    wedding_summary: z.object({
        groom_name: z.string(),
        bride_name: z.string(),
        date: z.iso.date(),
        venue_name: z.string().optional()
    })
});

export const zCreateHostInviteRequest = z.object({
    slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ])
});

export const zMoveHostSlotRequest = z.object({
    to_slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ])
});

export const zFeedItemType = z.enum([
    'guestbook_entry',
    'lounge_check_in',
    'host_announcement',
    'guestbook_message',
    'memory'
]);

export const zFeedItem = z.object({
    type: zFeedItemType,
    id: z.uuid(),
    created_at: z.iso.datetime(),
    data: z.record(z.string(), z.unknown()).optional(),
    heart_count: z.int().optional(),
    comment_count: z.int().optional(),
    my_heart: z.boolean().optional()
});

export const zFeedListResponse = z.object({
    data: z.array(zFeedItem),
    next_cursor: z.string().optional(),
    has_more: z.boolean()
});

export const zToggleFeedHeartRequest = z.object({
    target_type: z.enum(['guestbook_entry', 'host_announcement']),
    target_id: z.uuid()
});

export const zFeedHeartResponse = z.object({
    hearted: z.boolean(),
    heart_count: z.int()
});

export const zFeedComment = z.object({
    id: z.uuid(),
    user_id: z.uuid(),
    user_name: z.string(),
    target_type: z.enum(['guestbook_entry', 'host_announcement']),
    target_id: z.uuid(),
    message: z.string(),
    created_at: z.iso.datetime()
});

export const zCreateFeedCommentRequest = z.object({
    target_type: z.enum(['guestbook_entry', 'host_announcement']),
    target_id: z.uuid(),
    message: z.string().max(50)
});

export const zFeedCommentListResponse = z.object({
    data: z.array(zFeedComment),
    next_cursor: z.string().optional(),
    has_more: z.boolean()
});

export const zCreatePresignedUploadRequest = z.object({
    category: z.enum([
        'mobile-invitation',
        'memory',
        'share',
        'invitation-draft'
    ]),
    wedding_id: z.uuid().optional(),
    invitation_id: z.uuid().optional(),
    sub_kind: z.enum([
        'cover',
        'gallery',
        'lettering',
        'canvas'
    ]).optional(),
    lounge_id: z.uuid().optional(),
    file_name: z.string(),
    mime_type: z.string()
});

export const zPresignedUploadResponse = z.object({
    upload_url: z.url(),
    object_key: z.string(),
    public_url: z.url().optional()
});

export const zMobileInvitationPhoto = z.object({
    id: z.uuid(),
    invitation_id: z.uuid(),
    sub_kind: z.enum(['cover', 'gallery']),
    storage_path: z.string(),
    file_name: z.string().optional(),
    file_size: z.int().optional(),
    mime_type: z.string().optional(),
    sort_order: z.int(),
    created_at: z.iso.datetime()
});

export const zCreateMobileInvitationPhotoRequest = z.object({
    sub_kind: z.enum(['cover', 'gallery']),
    storage_path: z.string(),
    file_name: z.string().optional(),
    file_size: z.int().optional(),
    mime_type: z.string().optional(),
    sort_order: z.int().optional()
});

export const zMobileInvitationPhotoListResponse = z.object({
    data: z.array(zMobileInvitationPhoto)
});

export const zSharedPhoto = z.object({
    id: z.uuid(),
    lounge_id: z.uuid(),
    guest_user_id: z.uuid(),
    storage_path: z.string(),
    file_name: z.string().optional(),
    file_size: z.int().optional(),
    mime_type: z.string().optional(),
    created_at: z.iso.datetime()
});

export const zCreateSharedPhotoRequest = z.object({
    storage_path: z.string(),
    file_name: z.string().optional(),
    file_size: z.int().optional(),
    mime_type: z.string().optional()
});

export const zSharedPhotoListResponse = z.object({
    data: z.array(zSharedPhoto)
});

/**
 * recipient_slot 첫 단어 매핑 (호스트는 wedding 6슬롯 기준)
 */
export const zSharedPhotoGroupSide = z.enum([
    'groom',
    'bride',
    'other'
]);

export const zSharedPhotoInGroup = z.object({
    id: z.uuid(),
    storage_path: z.string(),
    created_at: z.iso.datetime()
});

export const zSharedPhotoGroup = z.object({
    user_id: z.uuid(),
    guest_name: z.string(),
    side: zSharedPhotoGroupSide.optional(),
    recipient_slot: z.string().nullish(),
    relation_category: z.string().nullish(),
    relation_detail: z.string().nullish(),
    photos: z.array(zSharedPhotoInGroup),
    photo_count: z.int().gte(0)
});

export const zSharedPhotoGroupsResponse = z.object({
    groups: z.array(zSharedPhotoGroup)
});

/**
 * ready_uncurated = 큐레이션 0건, ready = 1건 이상 큐레이션 완료
 */
export const zMemoryBookStatus = z.enum(['ready_uncurated', 'ready']);

export const zMemoryBookCouple = z.object({
    groom_name: z.string(),
    bride_name: z.string(),
    wedding_date: z.iso.date(),
    time: z.string().nullish(),
    venue_name: z.string(),
    venue_address: z.string().nullish(),
    venue_hall: z.string().nullish(),
    cover_photo_url: z.string().nullish()
});

export const zMemoryBookPhoto = z.object({
    id: z.uuid(),
    storage_path: z.string(),
    guest_user_id: z.uuid().nullish()
});

export const zMemoryBookMessage = z.object({
    id: z.uuid(),
    guest_name: z.string().nullish(),
    relation_label: z.string().nullish(),
    side: z.enum([
        'groom',
        'bride',
        'other'
    ]).optional(),
    message: z.string(),
    is_heart: z.boolean(),
    created_at: z.iso.datetime()
});

export const zMemoryBookStats = z.object({
    total_guests: z.int(),
    total_messages: z.int(),
    photos_uploaded: z.int()
});

export const zMemoryBookData = z.object({
    couple: zMemoryBookCouple,
    curated_photos: z.array(zMemoryBookPhoto),
    display_photos: z.array(z.string()),
    mec_messages: z.array(zMemoryBookMessage),
    stats: zMemoryBookStats
});

export const zMemoryBookResponse = z.object({
    status: zMemoryBookStatus,
    data: zMemoryBookData.optional()
});

export const zReplaceMemoryBookPhotosRequest = z.object({
    photo_ids: z.array(z.uuid()).max(30)
});

export const zReplaceMemoryBookPhotosResponse = z.object({
    ok: z.boolean(),
    count: z.int().gte(0).lte(30)
});

export const zInvalidMemoryBookPhotosError = z.object({
    error: z.string(),
    invalid_ids: z.array(z.uuid()).optional()
});

export const zAdminPagination = z.object({
    page: z.int().gte(1),
    limit: z.int().gte(1),
    total: z.int().gte(0)
});

export const zAdminUser = z.object({
    id: z.uuid(),
    name: z.string(),
    email: z.string(),
    phone: z.string().nullish(),
    profile_image_url: z.string().nullish(),
    created_at: z.iso.datetime(),
    provider: z.string().nullish(),
    last_sign_in_at: z.iso.datetime().nullish(),
    own_weddings_count: z.int().gte(0),
    guest_weddings_count: z.int().gte(0)
});

export const zAdminUserList = z.object({
    data: z.array(zAdminUser),
    meta: zAdminPagination
});

export const zAdminHostParticipation = z.object({
    wedding_id: z.uuid(),
    wedding_label: z.string(),
    slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ]),
    wedding_date: z.iso.date().nullish(),
    wedding_status: z.string()
});

export const zAdminActivityCounts = z.object({
    guestbook: z.int().gte(0),
    cash_gifts: z.int().gte(0),
    messages: z.int().gte(0),
    shared_photos: z.int().gte(0),
    memories: z.int().gte(0),
    memory_book: z.int().gte(0),
    lounge: z.int().gte(0)
});

export const zAdminUserDetail = zAdminUser.and(z.object({
    host_participations: z.array(zAdminHostParticipation),
    activity_counts: zAdminActivityCounts,
    is_placeholder: z.boolean().optional()
}));

export const zAdminActivity = z.object({
    id: z.uuid(),
    type: z.enum([
        'guestbook',
        'cash_gifts',
        'messages',
        'shared_photos',
        'memories',
        'memory_book',
        'lounge'
    ]),
    wedding_id: z.uuid(),
    wedding_label: z.string(),
    role: z.enum(['host', 'guest']),
    summary: z.string(),
    amount: z.int().nullish(),
    created_at: z.iso.datetime()
});

export const zAdminActivityList = z.object({
    data: z.array(zAdminActivity),
    meta: zAdminPagination
});

export const zAdminWeddingSummary = z.object({
    id: z.uuid(),
    groom_name: z.string(),
    bride_name: z.string(),
    date: z.iso.date().nullish(),
    status: z.string(),
    created_at: z.iso.datetime()
});

export const zAdminDashboardStats = z.object({
    today_weddings: z.int().gte(0),
    today_users: z.int().gte(0),
    today_cash_gifts_count: z.int().gte(0),
    today_cash_gifts_amount: z.int().gte(0),
    total_users: z.int().gte(0),
    total_weddings: z.int().gte(0)
});

export const zAdminDashboardRecent = z.object({
    recent_users: z.array(zAdminUser).max(5),
    recent_weddings: z.array(zAdminWeddingSummary).max(5)
});

export const zAdminHealthCheck = z.object({
    key: z.enum([
        'placeholder_host_weddings',
        'name_fallback_users',
        'deleted_weddings',
        'duplicate_couples',
        'null_host_slot_ratio'
    ]),
    value: z.number(),
    severity: z.enum([
        'ok',
        'warn',
        'error'
    ]).optional(),
    description: z.string()
});

export const zAdminDashboardHealth = z.object({
    checks: z.array(zAdminHealthCheck)
});

export const zLoungeCheckInWritable = z.object({
    id: z.uuid(),
    user_id: z.uuid(),
    lounge_id: z.uuid(),
    recipient_slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ]).optional(),
    relation_category: z.enum([
        '가족/친척',
        '친구/지인',
        '동문/동창',
        '직장동료',
        '스승/제자',
        '기타모임'
    ]).optional(),
    relation_detail: z.string().optional(),
    created_at: z.iso.datetime()
});

export const zLoungeCheckInListResponseWritable = z.object({
    data: z.array(zLoungeCheckInWritable),
    next_cursor: z.string().optional(),
    has_more: z.boolean()
});

export const zMoiWritable = z.object({
    id: z.uuid(),
    user_id: z.uuid(),
    equipped_items: z.record(z.string(), z.uuid())
});

export const zCashGiftWritable = z.object({
    id: z.uuid(),
    wedding_id: z.uuid(),
    guest_name: z.string(),
    guest_id: z.uuid().optional(),
    recipient_slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ]),
    relation_category: z.enum([
        '가족/친척',
        '친구/지인',
        '동문/동창',
        '직장동료',
        '스승/제자',
        '기타모임'
    ]),
    relation_detail: z.string().max(40).optional(),
    amount: z.int().gte(0),
    pay_method: z.enum([
        'transfer',
        'kakaopay',
        'toss',
        'cash'
    ]),
    guestbook_entry_id: z.uuid().optional(),
    created_at: z.iso.datetime()
});

export const zCashGiftListResponseWritable = z.object({
    data: z.array(zCashGiftWritable),
    next_cursor: z.string().optional(),
    has_more: z.boolean()
});

export const zUserId = z.uuid();

/**
 * admin write 대상 리소스의 UUID
 */
export const zAdminResourceId = z.uuid();

/**
 * 호스트 6슬롯 키 (host_<slot>_id 컬럼과 1:1 대응)
 */
export const zHostSlot = z.enum([
    'groom',
    'bride',
    'groom_father',
    'groom_mother',
    'bride_father',
    'bride_mother'
]);

export const zWeddingId = z.uuid();

export const zLoungeId = z.uuid();

export const zPlaceId = z.uuid();

export const zItemId = z.uuid();

export const zMoiId = z.uuid();

export const zAnnouncementId = z.uuid();

export const zIumId = z.uuid();

export const zCommentId = z.uuid();

export const zInvitationId = z.uuid();

export const zInviteToken = z.string();

export const zInviteId = z.uuid();

export const zSlug = z.string();

export const zGiftId = z.uuid();

/**
 * 페이지네이션 커서 (첫 요청 시 생략)
 */
export const zCursor = z.string();

/**
 * 페이지 당 항목 수
 */
export const zLimit = z.int().gte(1).lte(100).default(20);

/**
 * 1부터 시작하는 페이지 번호
 */
export const zAdminPage = z.int().gte(1).default(1);

/**
 * 페이지 당 항목 수 (admin 전용, 더 큰 한도)
 */
export const zAdminLimit = z.int().gte(1).lte(200).default(50);

/**
 * 이름·이메일·전화번호 부분 일치 (2자 이상 권장)
 */
export const zAdminSearch = z.string();

/**
 * 게스트 활동 유형 필터
 */
export const zAdminActivityTypeParam = z.enum([
    'all',
    'guestbook',
    'cash_gifts',
    'messages',
    'shared_photos',
    'memories',
    'memory_book',
    'lounge'
]).default('all');

/**
 * OK
 */
export const zGetMeResponse = zUser;

export const zUpdateMeBody = zUpdateUserRequest;

/**
 * OK
 */
export const zUpdateMeResponse = zUser;

export const zCreateConsentsBody = zCreateConsentsRequest;

export const zUpdateMarketingConsentBody = zUpdateMarketingConsentRequest;

export const zGetUserPath = z.object({
    userId: z.uuid()
});

/**
 * OK
 */
export const zGetUserResponse = zUserPublic;

/**
 * OK
 */
export const zGetMyWeddingsResponse = z.array(zWeddingSummary);

/**
 * OK
 */
export const zGetMyParticipatedWeddingsResponse = z.array(zParticipatedWedding);

export const zListMyIumsQuery = z.object({
    cursor: z.string().optional(),
    limit: z.int().gte(1).lte(100).optional().default(20)
});

/**
 * OK
 */
export const zListMyIumsResponse = zIumListResponse;

export const zCreateWeddingBody = zCreateWeddingRequest;

/**
 * Created
 */
export const zCreateWeddingResponse = zWedding;

export const zGetWeddingPath = z.object({
    weddingId: z.uuid()
});

/**
 * OK
 */
export const zGetWeddingResponse = zWedding;

export const zUpdateWeddingBody = zUpdateWeddingRequest;

export const zUpdateWeddingPath = z.object({
    weddingId: z.uuid()
});

/**
 * OK
 */
export const zUpdateWeddingResponse = zWedding;

export const zUpdateWeddingSuiIdsBody = zUpdateSuiIdsRequest;

export const zUpdateWeddingSuiIdsPath = z.object({
    weddingId: z.uuid()
});

/**
 * No Content
 */
export const zUpdateWeddingSuiIdsResponse = z.void();

export const zCreateInvitationBody = zCreateInvitationRequest;

export const zCreateInvitationPath = z.object({
    weddingId: z.uuid()
});

/**
 * Created
 */
export const zCreateInvitationResponse = zInvitation;

export const zGetInvitationPath = z.object({
    slug: z.string()
});

/**
 * OK
 */
export const zGetInvitationResponse = zInvitationPublic;

export const zHeartInvitationPath = z.object({
    slug: z.string()
});

/**
 * OK
 */
export const zHeartInvitationResponse = zHeartResponse;

export const zDeleteInvitationPath = z.object({
    weddingId: z.uuid(),
    invitationId: z.uuid()
});

/**
 * No Content
 */
export const zDeleteInvitationResponse = z.void();

export const zUpdateInvitationBody = zUpdateInvitationRequest;

export const zUpdateInvitationPath = z.object({
    weddingId: z.uuid(),
    invitationId: z.uuid()
});

/**
 * OK
 */
export const zUpdateInvitationResponse = zInvitation;

export const zShareInvitationPath = z.object({
    weddingId: z.uuid(),
    invitationId: z.uuid()
});

/**
 * OK
 */
export const zShareInvitationResponse = zShareLinkResponse;

export const zGetLoungePath = z.object({
    loungeId: z.uuid()
});

/**
 * OK
 */
export const zGetLoungeResponse = zLounge;

export const zGetMyLoungeCheckInPath = z.object({
    loungeId: z.uuid()
});

/**
 * OK
 */
export const zGetMyLoungeCheckInResponse = zLoungeCheckIn;

export const zCreateLoungeCheckInBody = zCreateLoungeCheckInRequest;

export const zCreateLoungeCheckInPath = z.object({
    loungeId: z.uuid()
});

/**
 * Created
 */
export const zCreateLoungeCheckInResponse = zLoungeCheckIn;

export const zListFeedPath = z.object({
    loungeId: z.uuid()
});

export const zListFeedQuery = z.object({
    cursor: z.string().optional(),
    limit: z.int().gte(1).lte(100).optional().default(20)
});

/**
 * OK
 */
export const zListFeedResponse = zFeedListResponse;

export const zListGuestbookEntriesPath = z.object({
    loungeId: z.uuid()
});

export const zListGuestbookEntriesQuery = z.object({
    cursor: z.string().optional(),
    limit: z.int().gte(1).lte(100).optional().default(20)
});

/**
 * OK
 */
export const zListGuestbookEntriesResponse = zGuestbookEntryListResponse;

export const zCreateGuestbookEntryBody = zCreateGuestbookEntryRequest;

export const zCreateGuestbookEntryPath = z.object({
    loungeId: z.uuid()
});

/**
 * Created
 */
export const zCreateGuestbookEntryResponse = zGuestbookEntry;

export const zGetMyGuestbookEntryPath = z.object({
    loungeId: z.uuid()
});

/**
 * OK
 */
export const zGetMyGuestbookEntryResponse = zGuestbookEntry;

export const zCreateGuestbookMessageBody = zCreateGuestbookMessageRequest;

export const zCreateGuestbookMessagePath = z.object({
    entryId: z.uuid()
});

/**
 * Created
 */
export const zCreateGuestbookMessageResponse = zGuestbookMessage;

export const zRecordGuestbookMessageViewPath = z.object({
    messageId: z.uuid()
});

/**
 * No Content (기록 완료, 또는 작성자 본인·중복으로 무시)
 */
export const zRecordGuestbookMessageViewResponse = z.void();

export const zClaimGuestbookEntryPath = z.object({
    entryId: z.uuid()
});

/**
 * No Content
 */
export const zClaimGuestbookEntryResponse = z.void();

export const zListAnnouncementsPath = z.object({
    loungeId: z.uuid()
});

export const zListAnnouncementsQuery = z.object({
    cursor: z.string().optional(),
    limit: z.int().gte(1).lte(100).optional().default(20)
});

/**
 * OK
 */
export const zListAnnouncementsResponse = zAnnouncementListResponse;

export const zCreateAnnouncementBody = zCreateAnnouncementRequest;

export const zCreateAnnouncementPath = z.object({
    loungeId: z.uuid()
});

/**
 * Created
 */
export const zCreateAnnouncementResponse = zAnnouncement;

export const zDeleteAnnouncementPath = z.object({
    announcementId: z.uuid()
});

/**
 * No Content
 */
export const zDeleteAnnouncementResponse = z.void();

export const zUpdateAnnouncementBody = zUpdateAnnouncementRequest;

export const zUpdateAnnouncementPath = z.object({
    announcementId: z.uuid()
});

/**
 * OK
 */
export const zUpdateAnnouncementResponse = zAnnouncement;

export const zCreateRsvpBody = zCreateRsvpRequest;

export const zCreateRsvpPath = z.object({
    weddingId: z.uuid()
});

/**
 * Created
 */
export const zCreateRsvpResponse = zRsvp;

export const zListRsvpsPath = z.object({
    weddingId: z.uuid()
});

/**
 * OK
 */
export const zListRsvpsResponse = zRsvpListResponse;

export const zCreateCashGiftBody = zCreateCashGiftRequest;

/**
 * Created
 */
export const zCreateCashGiftResponse = zCashGift;

export const zListCashGiftsPath = z.object({
    weddingId: z.uuid()
});

export const zListCashGiftsQuery = z.object({
    cursor: z.string().optional(),
    limit: z.int().gte(1).lte(100).optional().default(20)
});

/**
 * OK
 */
export const zListCashGiftsResponse = zCashGiftListResponse;

export const zHostCreateCashGiftBody = zHostCreateCashGiftRequest;

export const zHostCreateCashGiftPath = z.object({
    weddingId: z.uuid()
});

/**
 * Created
 */
export const zHostCreateCashGiftResponse = zCashGift;

export const zGetCashGiftsSummaryPath = z.object({
    weddingId: z.uuid()
});

/**
 * OK
 */
export const zGetCashGiftsSummaryResponse = zCashGiftSummary;

export const zDeleteCashGiftPath = z.object({
    weddingId: z.uuid(),
    giftId: z.uuid()
});

/**
 * Deleted
 */
export const zDeleteCashGiftResponse = z.void();

export const zUpdateCashGiftBody = zUpdateCashGiftRequest;

export const zUpdateCashGiftPath = z.object({
    weddingId: z.uuid(),
    giftId: z.uuid()
});

/**
 * OK
 */
export const zUpdateCashGiftResponse = zCashGift;

export const zGetWeddingMemoryBookPath = z.object({
    weddingId: z.uuid()
});

/**
 * OK
 */
export const zGetWeddingMemoryBookResponse = zMemoryBookResponse;

export const zReplaceWeddingMemoryBookPhotosBody = zReplaceMemoryBookPhotosRequest;

export const zReplaceWeddingMemoryBookPhotosPath = z.object({
    weddingId: z.uuid()
});

/**
 * OK
 */
export const zReplaceWeddingMemoryBookPhotosResponse = zReplaceMemoryBookPhotosResponse;

export const zGetWeddingSharedPhotoGroupsPath = z.object({
    weddingId: z.uuid()
});

/**
 * OK
 */
export const zGetWeddingSharedPhotoGroupsResponse = zSharedPhotoGroupsResponse;

export const zGetGatherPlacePath = z.object({
    placeId: z.uuid()
});

/**
 * OK
 */
export const zGetGatherPlaceResponse = zGatherPlace;

export const zListLoungeCheckInsPath = z.object({
    placeId: z.uuid()
});

export const zListLoungeCheckInsQuery = z.object({
    cursor: z.string().optional(),
    limit: z.int().gte(1).lte(100).optional().default(20)
});

/**
 * OK
 */
export const zListLoungeCheckInsResponse = zLoungeCheckInListResponse;

export const zListInteriorItemsPath = z.object({
    placeId: z.uuid()
});

/**
 * OK
 */
export const zListInteriorItemsResponse = z.array(zInteriorItem);

export const zCreateInteriorItemBody = zCreateInteriorItemRequest;

export const zCreateInteriorItemPath = z.object({
    placeId: z.uuid()
});

/**
 * Created
 */
export const zCreateInteriorItemResponse = zInteriorItem;

export const zUnplaceInteriorItemPath = z.object({
    itemId: z.uuid()
});

/**
 * OK
 */
export const zUnplaceInteriorItemResponse = zInteriorItem;

export const zPlaceInteriorItemBody = zPosition;

export const zPlaceInteriorItemPath = z.object({
    itemId: z.uuid()
});

/**
 * OK
 */
export const zPlaceInteriorItemResponse = zInteriorItem;

/**
 * OK
 */
export const zGetMyMoiResponse = zMoi;

export const zGetMoiPath = z.object({
    moiId: z.uuid()
});

/**
 * OK
 */
export const zGetMoiResponse = zMoi;

/**
 * OK
 */
export const zListMyMoiItemsResponse = z.array(zMoiItem);

export const zEquipMoiItemPath = z.object({
    itemId: z.uuid()
});

/**
 * OK
 */
export const zEquipMoiItemResponse = zMoi;

export const zUnequipMoiItemPath = z.object({
    itemId: z.uuid()
});

/**
 * OK
 */
export const zUnequipMoiItemResponse = zMoi;

export const zSendMoiItemBody = zSendMoiItemRequest;

export const zSendMoiItemPath = z.object({
    itemId: z.uuid()
});

/**
 * OK
 */
export const zSendMoiItemResponse = zMoiItem;

export const zToggleFeedHeartBody = zToggleFeedHeartRequest;

/**
 * OK
 */
export const zToggleFeedHeartResponse = zFeedHeartResponse;

export const zListFeedCommentsQuery = z.object({
    target_type: z.enum(['guestbook_entry', 'host_announcement']),
    target_id: z.uuid(),
    cursor: z.string().optional(),
    limit: z.int().gte(1).lte(100).optional().default(20)
});

/**
 * OK
 */
export const zListFeedCommentsResponse = zFeedCommentListResponse;

export const zCreateFeedCommentBody = zCreateFeedCommentRequest;

/**
 * Created
 */
export const zCreateFeedCommentResponse = zFeedComment;

export const zDeleteFeedCommentPath = z.object({
    commentId: z.uuid()
});

/**
 * No Content
 */
export const zDeleteFeedCommentResponse = z.void();

export const zListHostInvitesPath = z.object({
    weddingId: z.uuid()
});

/**
 * OK
 */
export const zListHostInvitesResponse = z.array(zHostInvite);

export const zCreateHostInviteBody = zCreateHostInviteRequest;

export const zCreateHostInvitePath = z.object({
    weddingId: z.uuid()
});

/**
 * Created
 */
export const zCreateHostInviteResponse = zHostInvite;

export const zGetHostInvitePath = z.object({
    token: z.string()
});

/**
 * OK
 */
export const zGetHostInviteResponse = zHostInvitePublic;

export const zAcceptHostInvitePath = z.object({
    token: z.string()
});

/**
 * OK
 */
export const zAcceptHostInviteResponse = zHostInvite;

export const zCancelHostInvitePath = z.object({
    weddingId: z.uuid(),
    inviteId: z.uuid()
});

/**
 * No Content
 */
export const zCancelHostInviteResponse = z.void();

export const zCreateIumBody = zCreateIumRequest;

/**
 * Created
 */
export const zCreateIumResponse = zIum;

export const zDeleteIumPath = z.object({
    iumId: z.uuid()
});

/**
 * No Content
 */
export const zDeleteIumResponse = z.void();

export const zCreatePresignedUploadBody = zCreatePresignedUploadRequest;

/**
 * 발급 성공
 */
export const zCreatePresignedUploadResponse = zPresignedUploadResponse;

export const zListMobileInvitationPhotosPath = z.object({
    weddingId: z.uuid(),
    invitationId: z.uuid()
});

/**
 * OK
 */
export const zListMobileInvitationPhotosResponse = zMobileInvitationPhotoListResponse;

export const zCreateMobileInvitationPhotoBody = zCreateMobileInvitationPhotoRequest;

export const zCreateMobileInvitationPhotoPath = z.object({
    weddingId: z.uuid(),
    invitationId: z.uuid()
});

/**
 * Created
 */
export const zCreateMobileInvitationPhotoResponse = zMobileInvitationPhoto;

export const zListSharedPhotosPath = z.object({
    loungeId: z.uuid()
});

export const zListSharedPhotosQuery = z.object({
    guest_user_id: z.uuid().optional()
});

/**
 * OK
 */
export const zListSharedPhotosResponse = zSharedPhotoListResponse;

export const zCreateSharedPhotoBody = zCreateSharedPhotoRequest;

export const zCreateSharedPhotoPath = z.object({
    loungeId: z.uuid()
});

/**
 * Created
 */
export const zCreateSharedPhotoResponse = zSharedPhoto;

export const zDownloadSharedPhotosZipPath = z.object({
    loungeId: z.uuid()
});

export const zDownloadSharedPhotosZipQuery = z.object({
    guest_user_id: z.uuid()
});

/**
 * ZIP 스트림
 */
export const zDownloadSharedPhotosZipResponse = z.string();

export const zCreateMemoryBody = zCreateMemoryRequest;

/**
 * 생성 완료
 */
export const zCreateMemoryResponse = zMemory;

export const zListMemoriesPath = z.object({
    loungeId: z.uuid()
});

export const zListMemoriesQuery = z.object({
    limit: z.int().gte(1).lte(200).optional().default(100)
});

/**
 * Memory 목록 (created_at DESC, deleted_at IS NULL)
 */
export const zListMemoriesResponse = zMemoryListResponse;

export const zDeleteMemoryPath = z.object({
    memoryId: z.uuid()
});

/**
 * 삭제 완료
 */
export const zDeleteMemoryResponse = z.void();

export const zListAdminUsersQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    limit: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().optional()
});

/**
 * OK
 */
export const zListAdminUsersResponse = zAdminUserList;

export const zGetAdminUserPath = z.object({
    userId: z.uuid()
});

/**
 * OK
 */
export const zGetAdminUserResponse = zAdminUserDetail;

export const zAdminUpdateUserBody = zUpdateAdminUserRequest;

export const zAdminUpdateUserPath = z.object({
    userId: z.uuid()
});

/**
 * Updated
 */
export const zAdminUpdateUserResponse = z.void();

export const zListAdminUserActivitiesPath = z.object({
    userId: z.uuid()
});

export const zListAdminUserActivitiesQuery = z.object({
    type: z.enum([
        'all',
        'guestbook',
        'cash_gifts',
        'messages',
        'shared_photos',
        'memories',
        'memory_book',
        'lounge'
    ]).optional().default('all'),
    page: z.int().gte(1).optional().default(1),
    limit: z.int().gte(1).lte(200).optional().default(50)
});

/**
 * OK
 */
export const zListAdminUserActivitiesResponse = zAdminActivityList;

/**
 * OK
 */
export const zGetAdminDashboardStatsResponse = zAdminDashboardStats;

/**
 * OK
 */
export const zGetAdminDashboardRecentResponse = zAdminDashboardRecent;

/**
 * OK
 */
export const zGetAdminDashboardHealthResponse = zAdminDashboardHealth;

export const zAdminDeleteCashGiftPath = z.object({
    id: z.uuid()
});

/**
 * Deleted
 */
export const zAdminDeleteCashGiftResponse = z.void();

export const zAdminUpdateCashGiftBody = zUpdateAdminCashGiftRequest;

export const zAdminUpdateCashGiftPath = z.object({
    id: z.uuid()
});

/**
 * Updated
 */
export const zAdminUpdateCashGiftResponse = z.void();

export const zAdminDeleteRsvpPath = z.object({
    id: z.uuid()
});

/**
 * Deleted
 */
export const zAdminDeleteRsvpResponse = z.void();

export const zAdminUpdateRsvpBody = zUpdateAdminRsvpRequest;

export const zAdminUpdateRsvpPath = z.object({
    id: z.uuid()
});

/**
 * Updated
 */
export const zAdminUpdateRsvpResponse = z.void();

export const zAdminDeleteHostInvitePath = z.object({
    id: z.uuid()
});

/**
 * Deleted
 */
export const zAdminDeleteHostInviteResponse = z.void();

export const zAdminUpdateHostInviteBody = zUpdateAdminHostInviteRequest;

export const zAdminUpdateHostInvitePath = z.object({
    id: z.uuid()
});

/**
 * Updated
 */
export const zAdminUpdateHostInviteResponse = z.void();

export const zAdminDeleteGuestbookMessagePath = z.object({
    id: z.uuid()
});

/**
 * Deleted
 */
export const zAdminDeleteGuestbookMessageResponse = z.void();

export const zAdminUpdateGuestbookMessageBody = zUpdateAdminGuestbookMessageRequest;

export const zAdminUpdateGuestbookMessagePath = z.object({
    id: z.uuid()
});

/**
 * Updated
 */
export const zAdminUpdateGuestbookMessageResponse = z.void();

export const zAdminDeleteGuestbookEntryPath = z.object({
    id: z.uuid()
});

/**
 * Deleted
 */
export const zAdminDeleteGuestbookEntryResponse = z.void();

export const zAdminUpdateGuestbookEntryBody = zUpdateAdminGuestbookEntryRequest;

export const zAdminUpdateGuestbookEntryPath = z.object({
    id: z.uuid()
});

/**
 * Updated
 */
export const zAdminUpdateGuestbookEntryResponse = z.void();

export const zAdminDeleteMobileInvitationPath = z.object({
    id: z.uuid()
});

/**
 * Deleted
 */
export const zAdminDeleteMobileInvitationResponse = z.void();

export const zAdminUpdateMobileInvitationBody = zUpdateAdminMobileInvitationRequest;

export const zAdminUpdateMobileInvitationPath = z.object({
    id: z.uuid()
});

/**
 * Updated
 */
export const zAdminUpdateMobileInvitationResponse = z.void();

export const zAdminDeleteMemoryPath = z.object({
    id: z.uuid()
});

/**
 * Deleted
 */
export const zAdminDeleteMemoryResponse = z.void();

export const zAdminUpdateMemoryBody = zUpdateAdminMemoryRequest;

export const zAdminUpdateMemoryPath = z.object({
    id: z.uuid()
});

/**
 * Updated
 */
export const zAdminUpdateMemoryResponse = z.void();

export const zAdminDeleteWeddingPath = z.object({
    id: z.uuid()
});

/**
 * Soft-deleted
 */
export const zAdminDeleteWeddingResponse = z.void();

export const zAdminUpdateWeddingBody = zUpdateAdminWeddingRequest;

export const zAdminUpdateWeddingPath = z.object({
    id: z.uuid()
});

/**
 * Updated
 */
export const zAdminUpdateWeddingResponse = z.void();

export const zAdminClearWeddingHostSlotPath = z.object({
    id: z.uuid(),
    slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ])
});

/**
 * Cleared
 */
export const zAdminClearWeddingHostSlotResponse = z.void();

export const zAdminMoveWeddingHostSlotBody = zMoveHostSlotRequest;

export const zAdminMoveWeddingHostSlotPath = z.object({
    id: z.uuid(),
    slot: z.enum([
        'groom',
        'bride',
        'groom_father',
        'groom_mother',
        'bride_father',
        'bride_mother'
    ])
});

/**
 * Moved
 */
export const zAdminMoveWeddingHostSlotResponse = z.void();

export const zAdminCreateHostInviteBody = zCreateHostInviteRequest;

export const zAdminCreateHostInvitePath = z.object({
    id: z.uuid()
});

/**
 * Created
 */
export const zAdminCreateHostInviteResponse = zHostInvite;

export const zAdminUpdateLoungeBody = zUpdateAdminLoungeRequest;

export const zAdminUpdateLoungePath = z.object({
    id: z.uuid()
});

/**
 * Updated
 */
export const zAdminUpdateLoungeResponse = z.void();

export const zAdminDeleteMemoryBookPhotoPath = z.object({
    id: z.uuid()
});

/**
 * Deleted
 */
export const zAdminDeleteMemoryBookPhotoResponse = z.void();

export const zAdminDeleteSharedPhotoPath = z.object({
    id: z.uuid()
});

/**
 * Deleted
 */
export const zAdminDeleteSharedPhotoResponse = z.void();

export const zAdminDeleteLoungeCheckInPath = z.object({
    id: z.uuid()
});

/**
 * Deleted
 */
export const zAdminDeleteLoungeCheckInResponse = z.void();
