// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdminDashboardHealth = `-- name: GetAdminDashboardHealth :one
SELECT
    (SELECT COUNT(*) FROM v3_weddings w
        WHERE w.status <> 'deleted'
          AND $1::uuid IN (
              w.host_groom_id, w.host_bride_id,
              w.host_groom_father_id, w.host_groom_mother_id,
              w.host_bride_father_id, w.host_bride_mother_id
          )) AS placeholder_host_weddings,
    (SELECT COUNT(*) FROM v3_users
        WHERE name IN ('사용자', 'User') OR split_part(email, '@', 1) = name) AS name_fallback_users,
    (SELECT COUNT(*) FROM v3_weddings WHERE status = 'deleted') AS deleted_weddings,
    (SELECT COUNT(*) FROM (
        SELECT 1 FROM v3_weddings
        GROUP BY groom_name, bride_name
        HAVING COUNT(*) > 1
    ) dup) AS duplicate_couples,
    (
        SELECT ROUND(
            AVG(
                CASE WHEN host_groom_id IS NULL THEN 1 ELSE 0 END +
                CASE WHEN host_bride_id IS NULL THEN 1 ELSE 0 END +
                CASE WHEN host_groom_father_id IS NULL THEN 1 ELSE 0 END +
                CASE WHEN host_groom_mother_id IS NULL THEN 1 ELSE 0 END +
                CASE WHEN host_bride_father_id IS NULL THEN 1 ELSE 0 END +
                CASE WHEN host_bride_mother_id IS NULL THEN 1 ELSE 0 END
            ) / 6.0, 4
        )
        FROM v3_weddings WHERE status <> 'deleted'
    )::float AS null_host_slot_ratio
`

type GetAdminDashboardHealthRow struct {
	PlaceholderHostWeddings int64   `json:"placeholder_host_weddings"`
	NameFallbackUsers       int64   `json:"name_fallback_users"`
	DeletedWeddings         int64   `json:"deleted_weddings"`
	DuplicateCouples        int64   `json:"duplicate_couples"`
	NullHostSlotRatio       float64 `json:"null_host_slot_ratio"`
}

// 5개 헬스체크 메트릭.
func (q *Queries) GetAdminDashboardHealth(ctx context.Context, placeholderUid pgtype.UUID) (GetAdminDashboardHealthRow, error) {
	row := q.db.QueryRow(ctx, getAdminDashboardHealth, placeholderUid)
	var i GetAdminDashboardHealthRow
	err := row.Scan(
		&i.PlaceholderHostWeddings,
		&i.NameFallbackUsers,
		&i.DeletedWeddings,
		&i.DuplicateCouples,
		&i.NullHostSlotRatio,
	)
	return i, err
}

const getAdminDashboardStats = `-- name: GetAdminDashboardStats :one
SELECT
    (SELECT COUNT(*) FROM v3_weddings
        WHERE (created_at AT TIME ZONE 'Asia/Seoul')::date = ((now() AT TIME ZONE 'Asia/Seoul')::date)
          AND status <> 'deleted') AS today_weddings,
    (SELECT COUNT(*) FROM v3_users
        WHERE (created_at AT TIME ZONE 'Asia/Seoul')::date = ((now() AT TIME ZONE 'Asia/Seoul')::date)) AS today_users,
    (SELECT COUNT(*) FROM v3_cash_gifts
        WHERE (created_at AT TIME ZONE 'Asia/Seoul')::date = ((now() AT TIME ZONE 'Asia/Seoul')::date)) AS today_cash_gifts_count,
    (SELECT COALESCE(SUM(amount), 0) FROM v3_cash_gifts
        WHERE (created_at AT TIME ZONE 'Asia/Seoul')::date = ((now() AT TIME ZONE 'Asia/Seoul')::date))::bigint AS today_cash_gifts_amount,
    (SELECT COUNT(*) FROM v3_users) AS total_users,
    (SELECT COUNT(*) FROM v3_weddings WHERE status <> 'deleted') AS total_weddings
`

type GetAdminDashboardStatsRow struct {
	TodayWeddings        int64 `json:"today_weddings"`
	TodayUsers           int64 `json:"today_users"`
	TodayCashGiftsCount  int64 `json:"today_cash_gifts_count"`
	TodayCashGiftsAmount int64 `json:"today_cash_gifts_amount"`
	TotalUsers           int64 `json:"total_users"`
	TotalWeddings        int64 `json:"total_weddings"`
}

// KST 자정 기준 오늘 통계 + 전체. NOW() AT TIME ZONE 'Asia/Seoul' → 한국 시각 → date 변환.
func (q *Queries) GetAdminDashboardStats(ctx context.Context) (GetAdminDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminDashboardStats)
	var i GetAdminDashboardStatsRow
	err := row.Scan(
		&i.TodayWeddings,
		&i.TodayUsers,
		&i.TodayCashGiftsCount,
		&i.TodayCashGiftsAmount,
		&i.TotalUsers,
		&i.TotalWeddings,
	)
	return i, err
}

const listAdminRecentUsers = `-- name: ListAdminRecentUsers :many
SELECT u.id, u.name, u.email, u.phone, u.profile_image_url, u.created_at,
       (
           SELECT COUNT(*) FROM v3_weddings w
           WHERE w.status <> 'deleted'
             AND u.id IN (
                 w.host_groom_id, w.host_bride_id,
                 w.host_groom_father_id, w.host_groom_mother_id,
                 w.host_bride_father_id, w.host_bride_mother_id
             )
       ) AS own_weddings_count,
       (
           SELECT COUNT(DISTINCT g.wedding_id) FROM (
               SELECT l.wedding_id FROM v3_guestbook_entries gbe
                   JOIN v3_wedding_lounges l ON l.id = gbe.lounge_id
                   WHERE gbe.guest_id = u.id
               UNION
               SELECT cg.wedding_id FROM v3_cash_gifts cg WHERE cg.guest_id = u.id
               UNION
               SELECT l.wedding_id FROM v3_shared_photos sp
                   JOIN v3_wedding_lounges l ON l.id = sp.lounge_id
                   WHERE sp.guest_user_id = u.id
               UNION
               SELECT l.wedding_id FROM v3_memories mm
                   JOIN v3_wedding_lounges l ON l.id = mm.lounge_id
                   WHERE mm.author_user_id = u.id
               UNION
               SELECT mbp.wedding_id FROM v3_memory_book_photos mbp WHERE mbp.selected_by = u.id
               UNION
               SELECT l.wedding_id FROM v3_lounge_check_ins le
                   JOIN v3_wedding_lounges l ON l.id = le.lounge_id
                   WHERE le.user_id = u.id
           ) g
       ) AS guest_weddings_count
FROM v3_users u
ORDER BY u.created_at DESC
LIMIT 5
`

type ListAdminRecentUsersRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Email              string             `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	ProfileImageUrl    pgtype.Text        `json:"profile_image_url"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	OwnWeddingsCount   int64              `json:"own_weddings_count"`
	GuestWeddingsCount int64              `json:"guest_weddings_count"`
}

func (q *Queries) ListAdminRecentUsers(ctx context.Context) ([]ListAdminRecentUsersRow, error) {
	rows, err := q.db.Query(ctx, listAdminRecentUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminRecentUsersRow{}
	for rows.Next() {
		var i ListAdminRecentUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.ProfileImageUrl,
			&i.CreatedAt,
			&i.OwnWeddingsCount,
			&i.GuestWeddingsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminRecentWeddings = `-- name: ListAdminRecentWeddings :many
SELECT id, groom_name, bride_name, date, status, created_at
FROM v3_weddings
WHERE status <> 'deleted'
ORDER BY created_at DESC
LIMIT 5
`

type ListAdminRecentWeddingsRow struct {
	ID        pgtype.UUID        `json:"id"`
	GroomName string             `json:"groom_name"`
	BrideName string             `json:"bride_name"`
	Date      pgtype.Date        `json:"date"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAdminRecentWeddings(ctx context.Context) ([]ListAdminRecentWeddingsRow, error) {
	rows, err := q.db.Query(ctx, listAdminRecentWeddings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminRecentWeddingsRow{}
	for rows.Next() {
		var i ListAdminRecentWeddingsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroomName,
			&i.BrideName,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
