// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdminUser = `-- name: GetAdminUser :one
SELECT
    u.id, u.name, u.email, u.phone, u.profile_image_url, u.created_at,
    (
        SELECT COUNT(*) FROM v3_weddings w
        WHERE w.status <> 'deleted'
          AND u.id IN (
              w.host_groom_id, w.host_bride_id,
              w.host_groom_father_id, w.host_groom_mother_id,
              w.host_bride_father_id, w.host_bride_mother_id
          )
    ) AS own_weddings_count,
    (
        SELECT COUNT(DISTINCT g.wedding_id) FROM (
            SELECT l.wedding_id FROM v3_guestbook_entries gbe
                JOIN v3_wedding_lounges l ON l.id = gbe.lounge_id
                WHERE gbe.guest_id = u.id
            UNION
            SELECT cg.wedding_id FROM v3_cash_gifts cg WHERE cg.guest_id = u.id
            UNION
            SELECT l.wedding_id FROM v3_shared_photos sp
                JOIN v3_wedding_lounges l ON l.id = sp.lounge_id
                WHERE sp.guest_user_id = u.id
            UNION
            SELECT l.wedding_id FROM v3_memories mm
                JOIN v3_wedding_lounges l ON l.id = mm.lounge_id
                WHERE mm.author_user_id = u.id
            UNION
            SELECT mbp.wedding_id FROM v3_memory_book_photos mbp WHERE mbp.selected_by = u.id
            UNION
            SELECT l.wedding_id FROM v3_lounge_check_ins le
                JOIN v3_wedding_lounges l ON l.id = le.lounge_id
                WHERE le.user_id = u.id
        ) g
    ) AS guest_weddings_count
FROM v3_users u
WHERE u.id = $1
`

type GetAdminUserRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Email              string             `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	ProfileImageUrl    pgtype.Text        `json:"profile_image_url"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	OwnWeddingsCount   int64              `json:"own_weddings_count"`
	GuestWeddingsCount int64              `json:"guest_weddings_count"`
}

func (q *Queries) GetAdminUser(ctx context.Context, id pgtype.UUID) (GetAdminUserRow, error) {
	row := q.db.QueryRow(ctx, getAdminUser, id)
	var i GetAdminUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.ProfileImageUrl,
		&i.CreatedAt,
		&i.OwnWeddingsCount,
		&i.GuestWeddingsCount,
	)
	return i, err
}

const getAdminUserActivityCounts = `-- name: GetAdminUserActivityCounts :one
SELECT
    (SELECT COUNT(*) FROM v3_guestbook_entries gbe WHERE gbe.guest_id = $1) AS guestbook,
    (SELECT COUNT(*) FROM v3_cash_gifts cg WHERE cg.guest_id = $1) AS cash_gifts,
    (SELECT COUNT(*) FROM v3_guestbook_entries gbe2
        WHERE gbe2.guest_id = $1
          AND EXISTS (SELECT 1 FROM v3_guestbook_messages gm2 WHERE gm2.guestbook_entry_id = gbe2.id)
    ) AS messages,
    (SELECT COUNT(*) FROM v3_shared_photos sp WHERE sp.guest_user_id = $1) AS shared_photos,
    (SELECT COUNT(*) FROM v3_memories mm WHERE mm.author_user_id = $1) AS memories,
    (SELECT COUNT(*) FROM v3_memory_book_photos mbp WHERE mbp.selected_by = $1) AS memory_book,
    (SELECT COUNT(*) FROM v3_lounge_check_ins le WHERE le.user_id = $1) AS lounge
`

type GetAdminUserActivityCountsRow struct {
	Guestbook    int64 `json:"guestbook"`
	CashGifts    int64 `json:"cash_gifts"`
	Messages     int64 `json:"messages"`
	SharedPhotos int64 `json:"shared_photos"`
	Memories     int64 `json:"memories"`
	MemoryBook   int64 `json:"memory_book"`
	Lounge       int64 `json:"lounge"`
}

// 단일 row에 7개 활동 카운트. sqlc v1.30 회피: 모든 subquery에 명시 alias + 조건은 단일 컬럼.
func (q *Queries) GetAdminUserActivityCounts(ctx context.Context, uid pgtype.UUID) (GetAdminUserActivityCountsRow, error) {
	row := q.db.QueryRow(ctx, getAdminUserActivityCounts, uid)
	var i GetAdminUserActivityCountsRow
	err := row.Scan(
		&i.Guestbook,
		&i.CashGifts,
		&i.Messages,
		&i.SharedPhotos,
		&i.Memories,
		&i.MemoryBook,
		&i.Lounge,
	)
	return i, err
}

const listAdminCashGiftActivities = `-- name: ListAdminCashGiftActivities :many
SELECT
    g.id,
    g.created_at,
    g.amount,
    -- summary: {관계 카테고리} · {세부}. NULL 안전.
    (
        g.relation_category
        || CASE WHEN g.relation_detail IS NOT NULL AND g.relation_detail <> '' THEN ' · ' || g.relation_detail ELSE '' END
    )::text AS relation_summary,
    w.id AS wedding_id,
    w.groom_name,
    w.bride_name,
    COUNT(*) OVER () AS total_count
FROM v3_cash_gifts g
JOIN v3_weddings w ON w.id = g.wedding_id
WHERE g.guest_id = $1
ORDER BY g.created_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListAdminCashGiftActivitiesParams struct {
	GuestID pgtype.UUID `json:"guest_id"`
	Off     int32       `json:"off"`
	Lim     int32       `json:"lim"`
}

type ListAdminCashGiftActivitiesRow struct {
	ID              pgtype.UUID        `json:"id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Amount          int32              `json:"amount"`
	RelationSummary string             `json:"relation_summary"`
	WeddingID       pgtype.UUID        `json:"wedding_id"`
	GroomName       string             `json:"groom_name"`
	BrideName       string             `json:"bride_name"`
	TotalCount      int64              `json:"total_count"`
}

func (q *Queries) ListAdminCashGiftActivities(ctx context.Context, arg ListAdminCashGiftActivitiesParams) ([]ListAdminCashGiftActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listAdminCashGiftActivities, arg.GuestID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminCashGiftActivitiesRow{}
	for rows.Next() {
		var i ListAdminCashGiftActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Amount,
			&i.RelationSummary,
			&i.WeddingID,
			&i.GroomName,
			&i.BrideName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminGuestbookActivities = `-- name: ListAdminGuestbookActivities :many
SELECT
    e.id,
    e.created_at,
    -- summary: {관계 카테고리} · {세부}. entries.message 컬럼은 20260525130000 마이그레이션으로 드롭됨 — 메시지 본문은 ListAdminMessageActivities가 별도 보고.
    (
        e.relation_category
        || CASE WHEN e.relation_detail IS NOT NULL AND e.relation_detail <> '' THEN ' · ' || e.relation_detail ELSE '' END
    )::text AS summary,
    w.id AS wedding_id,
    w.groom_name,
    w.bride_name,
    COUNT(*) OVER () AS total_count
FROM v3_guestbook_entries e
JOIN v3_wedding_lounges l ON l.id = e.lounge_id
JOIN v3_weddings w ON w.id = l.wedding_id
WHERE e.guest_id = $1
ORDER BY e.created_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListAdminGuestbookActivitiesParams struct {
	GuestID pgtype.UUID `json:"guest_id"`
	Off     int32       `json:"off"`
	Lim     int32       `json:"lim"`
}

type ListAdminGuestbookActivitiesRow struct {
	ID         pgtype.UUID        `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Summary    string             `json:"summary"`
	WeddingID  pgtype.UUID        `json:"wedding_id"`
	GroomName  string             `json:"groom_name"`
	BrideName  string             `json:"bride_name"`
	TotalCount int64              `json:"total_count"`
}

func (q *Queries) ListAdminGuestbookActivities(ctx context.Context, arg ListAdminGuestbookActivitiesParams) ([]ListAdminGuestbookActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listAdminGuestbookActivities, arg.GuestID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminGuestbookActivitiesRow{}
	for rows.Next() {
		var i ListAdminGuestbookActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Summary,
			&i.WeddingID,
			&i.GroomName,
			&i.BrideName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminLoungeActivities = `-- name: ListAdminLoungeActivities :many
SELECT
    le.id,
    le.created_at,
    -- summary: {관계 카테고리} · {세부}. 둘 다 nullable.
    (
        COALESCE(le.relation_category, '')
        || CASE
            WHEN le.relation_detail IS NOT NULL AND le.relation_detail <> ''
            THEN CASE WHEN le.relation_category IS NOT NULL AND le.relation_category <> '' THEN ' · ' ELSE '' END || le.relation_detail
            ELSE ''
        END
    )::text AS summary,
    w.id AS wedding_id,
    w.groom_name,
    w.bride_name,
    COUNT(*) OVER () AS total_count
FROM v3_lounge_check_ins le
JOIN v3_wedding_lounges l ON l.id = le.lounge_id
JOIN v3_weddings w ON w.id = l.wedding_id
WHERE le.user_id = $1
ORDER BY le.created_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListAdminLoungeActivitiesParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Off    int32       `json:"off"`
	Lim    int32       `json:"lim"`
}

type ListAdminLoungeActivitiesRow struct {
	ID         pgtype.UUID        `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Summary    string             `json:"summary"`
	WeddingID  pgtype.UUID        `json:"wedding_id"`
	GroomName  string             `json:"groom_name"`
	BrideName  string             `json:"bride_name"`
	TotalCount int64              `json:"total_count"`
}

func (q *Queries) ListAdminLoungeActivities(ctx context.Context, arg ListAdminLoungeActivitiesParams) ([]ListAdminLoungeActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listAdminLoungeActivities, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminLoungeActivitiesRow{}
	for rows.Next() {
		var i ListAdminLoungeActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Summary,
			&i.WeddingID,
			&i.GroomName,
			&i.BrideName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminMemoryActivities = `-- name: ListAdminMemoryActivities :many
SELECT
    mm.id,
    mm.created_at,
    mm.text AS summary,
    w.id AS wedding_id,
    w.groom_name,
    w.bride_name,
    COUNT(*) OVER () AS total_count
FROM v3_memories mm
JOIN v3_wedding_lounges l ON l.id = mm.lounge_id
JOIN v3_weddings w ON w.id = l.wedding_id
WHERE mm.author_user_id = $1
ORDER BY mm.created_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListAdminMemoryActivitiesParams struct {
	AuthorUserID pgtype.UUID `json:"author_user_id"`
	Off          int32       `json:"off"`
	Lim          int32       `json:"lim"`
}

type ListAdminMemoryActivitiesRow struct {
	ID         pgtype.UUID        `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Summary    string             `json:"summary"`
	WeddingID  pgtype.UUID        `json:"wedding_id"`
	GroomName  string             `json:"groom_name"`
	BrideName  string             `json:"bride_name"`
	TotalCount int64              `json:"total_count"`
}

func (q *Queries) ListAdminMemoryActivities(ctx context.Context, arg ListAdminMemoryActivitiesParams) ([]ListAdminMemoryActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listAdminMemoryActivities, arg.AuthorUserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminMemoryActivitiesRow{}
	for rows.Next() {
		var i ListAdminMemoryActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Summary,
			&i.WeddingID,
			&i.GroomName,
			&i.BrideName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminMemoryBookActivities = `-- name: ListAdminMemoryBookActivities :many
SELECT
    mbp.id,
    mbp.created_at,
    NULL::text AS summary,
    w.id AS wedding_id,
    w.groom_name,
    w.bride_name,
    COUNT(*) OVER () AS total_count
FROM v3_memory_book_photos mbp
JOIN v3_weddings w ON w.id = mbp.wedding_id
WHERE mbp.selected_by = $1
ORDER BY mbp.created_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListAdminMemoryBookActivitiesParams struct {
	SelectedBy pgtype.UUID `json:"selected_by"`
	Off        int32       `json:"off"`
	Lim        int32       `json:"lim"`
}

type ListAdminMemoryBookActivitiesRow struct {
	ID         pgtype.UUID        `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Summary    pgtype.Text        `json:"summary"`
	WeddingID  pgtype.UUID        `json:"wedding_id"`
	GroomName  string             `json:"groom_name"`
	BrideName  string             `json:"bride_name"`
	TotalCount int64              `json:"total_count"`
}

func (q *Queries) ListAdminMemoryBookActivities(ctx context.Context, arg ListAdminMemoryBookActivitiesParams) ([]ListAdminMemoryBookActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listAdminMemoryBookActivities, arg.SelectedBy, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminMemoryBookActivitiesRow{}
	for rows.Next() {
		var i ListAdminMemoryBookActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Summary,
			&i.WeddingID,
			&i.GroomName,
			&i.BrideName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminMessageActivities = `-- name: ListAdminMessageActivities :many
SELECT
    gm.id,
    gm.created_at,
    gm.message AS summary,
    w.id AS wedding_id,
    w.groom_name,
    w.bride_name,
    COUNT(*) OVER () AS total_count
FROM v3_guestbook_messages gm
JOIN v3_guestbook_entries ge ON ge.id = gm.guestbook_entry_id
JOIN v3_wedding_lounges l ON l.id = ge.lounge_id
JOIN v3_weddings w ON w.id = l.wedding_id
WHERE ge.guest_id = $1
ORDER BY gm.created_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListAdminMessageActivitiesParams struct {
	GuestID pgtype.UUID `json:"guest_id"`
	Off     int32       `json:"off"`
	Lim     int32       `json:"lim"`
}

type ListAdminMessageActivitiesRow struct {
	ID         pgtype.UUID        `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Summary    string             `json:"summary"`
	WeddingID  pgtype.UUID        `json:"wedding_id"`
	GroomName  string             `json:"groom_name"`
	BrideName  string             `json:"bride_name"`
	TotalCount int64              `json:"total_count"`
}

func (q *Queries) ListAdminMessageActivities(ctx context.Context, arg ListAdminMessageActivitiesParams) ([]ListAdminMessageActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listAdminMessageActivities, arg.GuestID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminMessageActivitiesRow{}
	for rows.Next() {
		var i ListAdminMessageActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Summary,
			&i.WeddingID,
			&i.GroomName,
			&i.BrideName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminSharedPhotoActivities = `-- name: ListAdminSharedPhotoActivities :many
SELECT
    sp.id,
    sp.created_at,
    COALESCE(sp.file_name, '')::text AS summary,
    w.id AS wedding_id,
    w.groom_name,
    w.bride_name,
    COUNT(*) OVER () AS total_count
FROM v3_shared_photos sp
JOIN v3_wedding_lounges l ON l.id = sp.lounge_id
JOIN v3_weddings w ON w.id = l.wedding_id
WHERE sp.guest_user_id = $1
ORDER BY sp.created_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListAdminSharedPhotoActivitiesParams struct {
	GuestUserID pgtype.UUID `json:"guest_user_id"`
	Off         int32       `json:"off"`
	Lim         int32       `json:"lim"`
}

type ListAdminSharedPhotoActivitiesRow struct {
	ID         pgtype.UUID        `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Summary    string             `json:"summary"`
	WeddingID  pgtype.UUID        `json:"wedding_id"`
	GroomName  string             `json:"groom_name"`
	BrideName  string             `json:"bride_name"`
	TotalCount int64              `json:"total_count"`
}

func (q *Queries) ListAdminSharedPhotoActivities(ctx context.Context, arg ListAdminSharedPhotoActivitiesParams) ([]ListAdminSharedPhotoActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listAdminSharedPhotoActivities, arg.GuestUserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminSharedPhotoActivitiesRow{}
	for rows.Next() {
		var i ListAdminSharedPhotoActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Summary,
			&i.WeddingID,
			&i.GroomName,
			&i.BrideName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminUserHostParticipations = `-- name: ListAdminUserHostParticipations :many
SELECT
    w.id AS wedding_id, w.groom_name, w.bride_name,
    w.date AS wedding_date, w.status AS wedding_status,
    w.created_at,
    'groom'::text AS slot_kind
FROM v3_weddings w
WHERE w.host_groom_id = $1 AND w.status <> 'deleted'
UNION ALL
SELECT w.id, w.groom_name, w.bride_name, w.date, w.status, w.created_at, 'bride'::text
FROM v3_weddings w
WHERE w.host_bride_id = $1 AND w.status <> 'deleted'
UNION ALL
SELECT w.id, w.groom_name, w.bride_name, w.date, w.status, w.created_at, 'groom_father'::text
FROM v3_weddings w
WHERE w.host_groom_father_id = $1 AND w.status <> 'deleted'
UNION ALL
SELECT w.id, w.groom_name, w.bride_name, w.date, w.status, w.created_at, 'groom_mother'::text
FROM v3_weddings w
WHERE w.host_groom_mother_id = $1 AND w.status <> 'deleted'
UNION ALL
SELECT w.id, w.groom_name, w.bride_name, w.date, w.status, w.created_at, 'bride_father'::text
FROM v3_weddings w
WHERE w.host_bride_father_id = $1 AND w.status <> 'deleted'
UNION ALL
SELECT w.id, w.groom_name, w.bride_name, w.date, w.status, w.created_at, 'bride_mother'::text
FROM v3_weddings w
WHERE w.host_bride_mother_id = $1 AND w.status <> 'deleted'
ORDER BY created_at DESC
`

type ListAdminUserHostParticipationsRow struct {
	WeddingID     pgtype.UUID        `json:"wedding_id"`
	GroomName     string             `json:"groom_name"`
	BrideName     string             `json:"bride_name"`
	WeddingDate   pgtype.Date        `json:"wedding_date"`
	WeddingStatus string             `json:"wedding_status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SlotKind      string             `json:"slot_kind"`
}

// 호스트 슬롯 6칸 중 어떤 슬롯인지 라벨링하여 반환. UNION ALL 6개 (sqlc v1.30 호환).
func (q *Queries) ListAdminUserHostParticipations(ctx context.Context, hostGroomID pgtype.UUID) ([]ListAdminUserHostParticipationsRow, error) {
	rows, err := q.db.Query(ctx, listAdminUserHostParticipations, hostGroomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUserHostParticipationsRow{}
	for rows.Next() {
		var i ListAdminUserHostParticipationsRow
		if err := rows.Scan(
			&i.WeddingID,
			&i.GroomName,
			&i.BrideName,
			&i.WeddingDate,
			&i.WeddingStatus,
			&i.CreatedAt,
			&i.SlotKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT
    u.id,
    u.name,
    u.email,
    u.phone,
    u.profile_image_url,
    u.created_at,
    COUNT(*) OVER () AS total_count,
    (
        SELECT COUNT(*) FROM v3_weddings w
        WHERE w.status <> 'deleted'
          AND u.id IN (
              w.host_groom_id, w.host_bride_id,
              w.host_groom_father_id, w.host_groom_mother_id,
              w.host_bride_father_id, w.host_bride_mother_id
          )
    ) AS own_weddings_count,
    (
        SELECT COUNT(DISTINCT g.wedding_id) FROM (
            SELECT l.wedding_id FROM v3_guestbook_entries gbe
                JOIN v3_wedding_lounges l ON l.id = gbe.lounge_id
                WHERE gbe.guest_id = u.id
            UNION
            SELECT cg.wedding_id FROM v3_cash_gifts cg WHERE cg.guest_id = u.id
            UNION
            SELECT l.wedding_id FROM v3_shared_photos sp
                JOIN v3_wedding_lounges l ON l.id = sp.lounge_id
                WHERE sp.guest_user_id = u.id
            UNION
            SELECT l.wedding_id FROM v3_memories mm
                JOIN v3_wedding_lounges l ON l.id = mm.lounge_id
                WHERE mm.author_user_id = u.id
            UNION
            SELECT mbp.wedding_id FROM v3_memory_book_photos mbp WHERE mbp.selected_by = u.id
            UNION
            SELECT l.wedding_id FROM v3_lounge_check_ins le
                JOIN v3_wedding_lounges l ON l.id = le.lounge_id
                WHERE le.user_id = u.id
        ) g
    ) AS guest_weddings_count
FROM v3_users u
WHERE (
    $1::text = ''
    OR u.name ILIKE '%' || $1::text || '%'
    OR u.email ILIKE '%' || $1::text || '%'
    OR COALESCE(u.phone, '') ILIKE '%' || $1::text || '%'
)
ORDER BY u.created_at DESC
LIMIT $3::int
OFFSET $2::int
`

type ListAdminUsersParams struct {
	Search string `json:"search"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
}

type ListAdminUsersRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Email              string             `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	ProfileImageUrl    pgtype.Text        `json:"profile_image_url"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	TotalCount         int64              `json:"total_count"`
	OwnWeddingsCount   int64              `json:"own_weddings_count"`
	GuestWeddingsCount int64              `json:"guest_weddings_count"`
}

// 운영자 페이지용 v3_users 목록.
// search는 ILIKE 부분 일치 (이름/이메일/전화). 빈 문자열이면 필터 미적용.
// own_weddings_count   = host 슬롯 6칸 중 한 곳이라도 이 유저인 wedding(status!=deleted) 수 ("본인 웨딩")
// guest_weddings_count = 이 유저가 게스트 활동(방명록/축의금/사진/메모리/메모리북/라운지 체크인)을 한 wedding의 distinct 수 ("참여 웨딩")
func (q *Queries) ListAdminUsers(ctx context.Context, arg ListAdminUsersParams) ([]ListAdminUsersRow, error) {
	rows, err := q.db.Query(ctx, listAdminUsers, arg.Search, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUsersRow{}
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.ProfileImageUrl,
			&i.CreatedAt,
			&i.TotalCount,
			&i.OwnWeddingsCount,
			&i.GuestWeddingsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
