// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_mutations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminDeleteAcceptedHostInvitesBySlot = `-- name: AdminDeleteAcceptedHostInvitesBySlot :execrows
DELETE FROM v3_host_invites
WHERE wedding_id = $1 AND slot = $2 AND status = 'accepted'
`

type AdminDeleteAcceptedHostInvitesBySlotParams struct {
	WeddingID pgtype.UUID `json:"wedding_id"`
	Slot      string      `json:"slot"`
}

// 호스트 슬롯 등록 해제 시, 같은 wedding+slot의 수락(accepted)된 초대를 정리(하드 삭제).
// 슬롯 host_*_id를 NULL로 비우는 UPDATE는 컬럼이 동적이라 sqlc로 표현 못 해 서비스의 raw SQL이 담당한다.
// pending 초대는 보존(비운 슬롯에 재수락 가능). 0행이어도 정상(생성 시 직접 채워진 슬롯엔 초대가 없을 수 있음).
func (q *Queries) AdminDeleteAcceptedHostInvitesBySlot(ctx context.Context, arg AdminDeleteAcceptedHostInvitesBySlotParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteAcceptedHostInvitesBySlot, arg.WeddingID, arg.Slot)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteCashGift = `-- name: AdminDeleteCashGift :execrows

DELETE FROM v3_cash_gifts WHERE id = $1
`

// ════════════════════════ DELETE (hard) ════════════════════════
func (q *Queries) AdminDeleteCashGift(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteCashGift, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteGuestbookEntry = `-- name: AdminDeleteGuestbookEntry :execrows
DELETE FROM v3_guestbook_entries WHERE id = $1
`

func (q *Queries) AdminDeleteGuestbookEntry(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteGuestbookEntry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteGuestbookMessage = `-- name: AdminDeleteGuestbookMessage :execrows
DELETE FROM v3_guestbook_messages WHERE id = $1
`

func (q *Queries) AdminDeleteGuestbookMessage(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteGuestbookMessage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteHostInvite = `-- name: AdminDeleteHostInvite :execrows
DELETE FROM v3_host_invites WHERE id = $1
`

func (q *Queries) AdminDeleteHostInvite(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteHostInvite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteLoungeCheckIn = `-- name: AdminDeleteLoungeCheckIn :execrows
DELETE FROM v3_lounge_check_ins WHERE id = $1
`

func (q *Queries) AdminDeleteLoungeCheckIn(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteLoungeCheckIn, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteMemoryBookPhoto = `-- name: AdminDeleteMemoryBookPhoto :execrows
DELETE FROM v3_memory_book_photos WHERE id = $1
`

func (q *Queries) AdminDeleteMemoryBookPhoto(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteMemoryBookPhoto, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteMobileInvitation = `-- name: AdminDeleteMobileInvitation :execrows
DELETE FROM v3_mobile_invitations WHERE id = $1
`

func (q *Queries) AdminDeleteMobileInvitation(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteMobileInvitation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteRsvp = `-- name: AdminDeleteRsvp :execrows
DELETE FROM v3_rsvps WHERE id = $1
`

func (q *Queries) AdminDeleteRsvp(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteRsvp, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteSharedPhoto = `-- name: AdminDeleteSharedPhoto :execrows
DELETE FROM v3_shared_photos WHERE id = $1
`

func (q *Queries) AdminDeleteSharedPhoto(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteSharedPhoto, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminMoveAcceptedHostInvitesBySlot = `-- name: AdminMoveAcceptedHostInvitesBySlot :execrows
UPDATE v3_host_invites
SET slot = $1
WHERE wedding_id = $2 AND slot = $3 AND status = 'accepted'
`

type AdminMoveAcceptedHostInvitesBySlotParams struct {
	ToSlot    string      `json:"to_slot"`
	WeddingID pgtype.UUID `json:"wedding_id"`
	FromSlot  string      `json:"from_slot"`
}

// 호스트 슬롯 이동 시, 같은 wedding+from_slot의 수락(accepted)된 초대의 slot을 to_slot으로 변경.
// wedding 슬롯 이동(서비스의 raw SQL)과 같은 트랜잭션에서 호출돼 초대 기록과 슬롯의 일관성을 유지한다.
// 0행이어도 정상(직접 채워진 슬롯엔 수락 초대가 없을 수 있음).
func (q *Queries) AdminMoveAcceptedHostInvitesBySlot(ctx context.Context, arg AdminMoveAcceptedHostInvitesBySlotParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminMoveAcceptedHostInvitesBySlot, arg.ToSlot, arg.WeddingID, arg.FromSlot)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminSoftDeleteMemory = `-- name: AdminSoftDeleteMemory :execrows

UPDATE v3_memories SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// ════════════════════════ DELETE (soft) ════════════════════════
func (q *Queries) AdminSoftDeleteMemory(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminSoftDeleteMemory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminSoftDeleteWedding = `-- name: AdminSoftDeleteWedding :execrows
UPDATE v3_weddings SET status = 'deleted'
WHERE id = $1 AND status <> 'deleted'
`

func (q *Queries) AdminSoftDeleteWedding(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminSoftDeleteWedding, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUpdateCashGift = `-- name: AdminUpdateCashGift :execrows

UPDATE v3_cash_gifts
SET guest_name        = COALESCE($1, guest_name),
    amount            = COALESCE($2, amount),
    recipient_slot    = COALESCE($3, recipient_slot),
    relation_category = COALESCE($4, relation_category),
    relation_detail   = COALESCE($5, relation_detail),
    pay_method        = COALESCE($6, pay_method)
WHERE id = $7
`

type AdminUpdateCashGiftParams struct {
	GuestName        pgtype.Text `json:"guest_name"`
	Amount           pgtype.Int4 `json:"amount"`
	RecipientSlot    pgtype.Text `json:"recipient_slot"`
	RelationCategory pgtype.Text `json:"relation_category"`
	RelationDetail   pgtype.Text `json:"relation_detail"`
	PayMethod        pgtype.Text `json:"pay_method"`
	ID               pgtype.UUID `json:"id"`
}

// ════════════════════════ UPDATE (핵심 필드만) ════════════════════════
func (q *Queries) AdminUpdateCashGift(ctx context.Context, arg AdminUpdateCashGiftParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminUpdateCashGift,
		arg.GuestName,
		arg.Amount,
		arg.RecipientSlot,
		arg.RelationCategory,
		arg.RelationDetail,
		arg.PayMethod,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUpdateGuestbookEntry = `-- name: AdminUpdateGuestbookEntry :execrows
UPDATE v3_guestbook_entries
SET guest_name        = COALESCE($1, guest_name),
    recipient_slot    = COALESCE($2, recipient_slot),
    relation_category = COALESCE($3, relation_category),
    relation_detail   = COALESCE($4, relation_detail)
WHERE id = $5
`

type AdminUpdateGuestbookEntryParams struct {
	GuestName        pgtype.Text `json:"guest_name"`
	RecipientSlot    pgtype.Text `json:"recipient_slot"`
	RelationCategory pgtype.Text `json:"relation_category"`
	RelationDetail   pgtype.Text `json:"relation_detail"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) AdminUpdateGuestbookEntry(ctx context.Context, arg AdminUpdateGuestbookEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminUpdateGuestbookEntry,
		arg.GuestName,
		arg.RecipientSlot,
		arg.RelationCategory,
		arg.RelationDetail,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUpdateGuestbookMessage = `-- name: AdminUpdateGuestbookMessage :execrows
UPDATE v3_guestbook_messages
SET message = COALESCE($1, message)
WHERE id = $2
`

type AdminUpdateGuestbookMessageParams struct {
	Message pgtype.Text `json:"message"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) AdminUpdateGuestbookMessage(ctx context.Context, arg AdminUpdateGuestbookMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminUpdateGuestbookMessage, arg.Message, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUpdateHostInvite = `-- name: AdminUpdateHostInvite :execrows
UPDATE v3_host_invites
SET status = COALESCE($1, status)
WHERE id = $2
`

type AdminUpdateHostInviteParams struct {
	Status pgtype.Text `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) AdminUpdateHostInvite(ctx context.Context, arg AdminUpdateHostInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminUpdateHostInvite, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUpdateLounge = `-- name: AdminUpdateLounge :execrows
UPDATE v3_wedding_lounges
SET name = COALESCE($1, name)
WHERE id = $2
`

type AdminUpdateLoungeParams struct {
	Name pgtype.Text `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) AdminUpdateLounge(ctx context.Context, arg AdminUpdateLoungeParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminUpdateLounge, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUpdateMemory = `-- name: AdminUpdateMemory :execrows
UPDATE v3_memories
SET text = COALESCE($1, text)
WHERE id = $2 AND deleted_at IS NULL
`

type AdminUpdateMemoryParams struct {
	Text pgtype.Text `json:"text"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) AdminUpdateMemory(ctx context.Context, arg AdminUpdateMemoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminUpdateMemory, arg.Text, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUpdateMobileInvitation = `-- name: AdminUpdateMobileInvitation :execrows
UPDATE v3_mobile_invitations
SET custom_message     = COALESCE($1, custom_message),
    design_template_id = COALESCE($2, design_template_id),
    slug               = COALESCE($3, slug),
    cover_image        = COALESCE($4, cover_image)
WHERE id = $5
`

type AdminUpdateMobileInvitationParams struct {
	CustomMessage    pgtype.Text `json:"custom_message"`
	DesignTemplateID pgtype.Text `json:"design_template_id"`
	Slug             pgtype.Text `json:"slug"`
	CoverImage       pgtype.Text `json:"cover_image"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) AdminUpdateMobileInvitation(ctx context.Context, arg AdminUpdateMobileInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminUpdateMobileInvitation,
		arg.CustomMessage,
		arg.DesignTemplateID,
		arg.Slug,
		arg.CoverImage,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUpdateRsvp = `-- name: AdminUpdateRsvp :execrows
UPDATE v3_rsvps
SET guest_name      = COALESCE($1, guest_name),
    attendance      = COALESCE($2, attendance),
    companion_count = COALESCE($3, companion_count),
    meal            = COALESCE($4, meal),
    recipient_slot  = COALESCE($5, recipient_slot),
    phone_last4     = COALESCE($6, phone_last4)
WHERE id = $7
`

type AdminUpdateRsvpParams struct {
	GuestName      pgtype.Text `json:"guest_name"`
	Attendance     pgtype.Text `json:"attendance"`
	CompanionCount pgtype.Int4 `json:"companion_count"`
	Meal           pgtype.Text `json:"meal"`
	RecipientSlot  pgtype.Text `json:"recipient_slot"`
	PhoneLast4     pgtype.Text `json:"phone_last4"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) AdminUpdateRsvp(ctx context.Context, arg AdminUpdateRsvpParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminUpdateRsvp,
		arg.GuestName,
		arg.Attendance,
		arg.CompanionCount,
		arg.Meal,
		arg.RecipientSlot,
		arg.PhoneLast4,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUpdateUser = `-- name: AdminUpdateUser :execrows
UPDATE v3_users
SET name              = COALESCE($1, name),
    phone             = COALESCE($2, phone),
    email             = COALESCE($3, email),
    profile_image_url = COALESCE($4, profile_image_url)
WHERE id = $5
`

type AdminUpdateUserParams struct {
	Name            pgtype.Text `json:"name"`
	Phone           pgtype.Text `json:"phone"`
	Email           pgtype.Text `json:"email"`
	ProfileImageUrl pgtype.Text `json:"profile_image_url"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminUpdateUser,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.ProfileImageUrl,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUpdateWedding = `-- name: AdminUpdateWedding :execrows
UPDATE v3_weddings
SET groom_name    = COALESCE($1, groom_name),
    bride_name    = COALESCE($2, bride_name),
    date          = COALESCE($3, date),
    "time"        = COALESCE($4, "time"),
    venue_name    = COALESCE($5, venue_name),
    venue_address = COALESCE($6, venue_address),
    venue_hall    = COALESCE($7, venue_hall),
    status        = COALESCE($8, status)
WHERE id = $9
`

type AdminUpdateWeddingParams struct {
	GroomName    pgtype.Text `json:"groom_name"`
	BrideName    pgtype.Text `json:"bride_name"`
	Date         pgtype.Date `json:"date"`
	Time         pgtype.Text `json:"time"`
	VenueName    pgtype.Text `json:"venue_name"`
	VenueAddress pgtype.Text `json:"venue_address"`
	VenueHall    pgtype.Text `json:"venue_hall"`
	Status       pgtype.Text `json:"status"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) AdminUpdateWedding(ctx context.Context, arg AdminUpdateWeddingParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminUpdateWedding,
		arg.GroomName,
		arg.BrideName,
		arg.Date,
		arg.Time,
		arg.VenueName,
		arg.VenueAddress,
		arg.VenueHall,
		arg.Status,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAdminAuditLog = `-- name: InsertAdminAuditLog :exec

INSERT INTO admin_audit_logs (
    admin_user_id, admin_email, action, resource_type, resource_id, changes, request_method, request_path
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    convert_from($6, 'UTF8')::jsonb,
    $7,
    $8
)
`

type InsertAdminAuditLogParams struct {
	AdminUserID   pgtype.UUID `json:"admin_user_id"`
	AdminEmail    string      `json:"admin_email"`
	Action        string      `json:"action"`
	ResourceType  string      `json:"resource_type"`
	ResourceID    string      `json:"resource_id"`
	Changes       []byte      `json:"changes"`
	RequestMethod pgtype.Text `json:"request_method"`
	RequestPath   pgtype.Text `json:"request_path"`
}

// Admin write (수정·삭제) 쿼리 모음.
// /admin/* 경로는 AdminGuard(이메일 allowlist) 미들웨어가 보호하므로 쿼리 레벨 권한검증 없음.
// 부분수정은 COALESCE(narg, col) — 전달된 필드만 변경, 미전달은 기존값 유지.
// 응답 본문은 FE가 Supabase 직접 재조회로 갱신하므로 :execrows(영향 행수)만 반환 → 0행이면 service에서 ErrNotFound.
// 핵심 필드만 수정 허용(매트릭스: _audit admin-write 설계). 위험 테이블 삭제 정책: weddings=soft, lounges·users=삭제 없음.
// ── 감사 로그 ──
func (q *Queries) InsertAdminAuditLog(ctx context.Context, arg InsertAdminAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAdminAuditLog,
		arg.AdminUserID,
		arg.AdminEmail,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Changes,
		arg.RequestMethod,
		arg.RequestPath,
	)
	return err
}
