// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: announcements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAnnouncementByID = `-- name: GetAnnouncementByID :one
SELECT id, lounge_id, host_id, message, created_at, is_pinned, deleted_at, updated_at FROM v3_host_announcements
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAnnouncementByID(ctx context.Context, id pgtype.UUID) (V3HostAnnouncement, error) {
	row := q.db.QueryRow(ctx, getAnnouncementByID, id)
	var i V3HostAnnouncement
	err := row.Scan(
		&i.ID,
		&i.LoungeID,
		&i.HostID,
		&i.Message,
		&i.CreatedAt,
		&i.IsPinned,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAnnouncement = `-- name: InsertAnnouncement :one
INSERT INTO v3_host_announcements (lounge_id, host_id, message, is_pinned)
VALUES ($1, $2, $3, $4)
RETURNING id, lounge_id, host_id, message, created_at, is_pinned, deleted_at, updated_at
`

type InsertAnnouncementParams struct {
	LoungeID pgtype.UUID `json:"lounge_id"`
	HostID   pgtype.UUID `json:"host_id"`
	Message  string      `json:"message"`
	IsPinned bool        `json:"is_pinned"`
}

func (q *Queries) InsertAnnouncement(ctx context.Context, arg InsertAnnouncementParams) (V3HostAnnouncement, error) {
	row := q.db.QueryRow(ctx, insertAnnouncement,
		arg.LoungeID,
		arg.HostID,
		arg.Message,
		arg.IsPinned,
	)
	var i V3HostAnnouncement
	err := row.Scan(
		&i.ID,
		&i.LoungeID,
		&i.HostID,
		&i.Message,
		&i.CreatedAt,
		&i.IsPinned,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, lounge_id, host_id, message, created_at, is_pinned, deleted_at, updated_at
FROM v3_host_announcements
WHERE lounge_id = $1
  AND deleted_at IS NULL
  AND ($3::timestamptz IS NULL OR created_at < $3::timestamptz)
ORDER BY created_at DESC
LIMIT $2
`

type ListAnnouncementsParams struct {
	LoungeID pgtype.UUID        `json:"lounge_id"`
	Limit    int32              `json:"limit"`
	Cursor   pgtype.Timestamptz `json:"cursor"`
}

func (q *Queries) ListAnnouncements(ctx context.Context, arg ListAnnouncementsParams) ([]V3HostAnnouncement, error) {
	rows, err := q.db.Query(ctx, listAnnouncements, arg.LoungeID, arg.Limit, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []V3HostAnnouncement{}
	for rows.Next() {
		var i V3HostAnnouncement
		if err := rows.Scan(
			&i.ID,
			&i.LoungeID,
			&i.HostID,
			&i.Message,
			&i.CreatedAt,
			&i.IsPinned,
			&i.DeletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAllAnnouncements = `-- name: SoftDeleteAllAnnouncements :exec
UPDATE v3_host_announcements
SET deleted_at = now()
WHERE lounge_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAllAnnouncements(ctx context.Context, loungeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteAllAnnouncements, loungeID)
	return err
}

const softDeleteAnnouncement = `-- name: SoftDeleteAnnouncement :exec
UPDATE v3_host_announcements
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAnnouncement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteAnnouncement, id)
	return err
}

const unpinAllAnnouncements = `-- name: UnpinAllAnnouncements :exec
UPDATE v3_host_announcements
SET is_pinned = false
WHERE lounge_id = $1 AND is_pinned = true AND deleted_at IS NULL
`

func (q *Queries) UnpinAllAnnouncements(ctx context.Context, loungeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unpinAllAnnouncements, loungeID)
	return err
}

const updateAnnouncement = `-- name: UpdateAnnouncement :one
UPDATE v3_host_announcements
SET message = COALESCE($2, message),
    is_pinned = COALESCE($3, is_pinned),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, lounge_id, host_id, message, created_at, is_pinned, deleted_at, updated_at
`

type UpdateAnnouncementParams struct {
	ID       pgtype.UUID `json:"id"`
	Message  pgtype.Text `json:"message"`
	IsPinned pgtype.Bool `json:"is_pinned"`
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (V3HostAnnouncement, error) {
	row := q.db.QueryRow(ctx, updateAnnouncement, arg.ID, arg.Message, arg.IsPinned)
	var i V3HostAnnouncement
	err := row.Scan(
		&i.ID,
		&i.LoungeID,
		&i.HostID,
		&i.Message,
		&i.CreatedAt,
		&i.IsPinned,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
