// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cash_gifts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCashGift = `-- name: DeleteCashGift :exec
DELETE FROM v3_cash_gifts
WHERE id = $1
`

func (q *Queries) DeleteCashGift(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCashGift, id)
	return err
}

const getCashGift = `-- name: GetCashGift :one
SELECT cg.id, cg.wedding_id, cg.guest_name, cg.guest_id, cg.recipient_slot, cg.relation_category, cg.relation_detail, cg.amount, cg.pay_method, cg.guestbook_entry_id, cg.created_at,
    EXISTS (
        SELECT 1 FROM v3_guestbook_entries ge
        JOIN v3_wedding_lounges wl ON wl.id = ge.lounge_id
        WHERE wl.wedding_id = cg.wedding_id AND ge.id = cg.guestbook_entry_id
    ) AS attended
FROM v3_cash_gifts cg
WHERE cg.id = $1
`

type GetCashGiftRow struct {
	ID               pgtype.UUID        `json:"id"`
	WeddingID        pgtype.UUID        `json:"wedding_id"`
	GuestName        string             `json:"guest_name"`
	GuestID          pgtype.UUID        `json:"guest_id"`
	RecipientSlot    string             `json:"recipient_slot"`
	RelationCategory string             `json:"relation_category"`
	RelationDetail   pgtype.Text        `json:"relation_detail"`
	Amount           int32              `json:"amount"`
	PayMethod        string             `json:"pay_method"`
	GuestbookEntryID pgtype.UUID        `json:"guestbook_entry_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Attended         bool               `json:"attended"`
}

func (q *Queries) GetCashGift(ctx context.Context, id pgtype.UUID) (GetCashGiftRow, error) {
	row := q.db.QueryRow(ctx, getCashGift, id)
	var i GetCashGiftRow
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.GuestName,
		&i.GuestID,
		&i.RecipientSlot,
		&i.RelationCategory,
		&i.RelationDetail,
		&i.Amount,
		&i.PayMethod,
		&i.GuestbookEntryID,
		&i.CreatedAt,
		&i.Attended,
	)
	return i, err
}

const getCashGiftsSummary = `-- name: GetCashGiftsSummary :one
SELECT
    COALESCE(SUM(cg.amount), 0)::bigint AS total_amount,
    COUNT(*)::bigint AS total_count,
    COUNT(*) FILTER (WHERE EXISTS (
        SELECT 1 FROM v3_guestbook_entries ge
        JOIN v3_wedding_lounges wl ON wl.id = ge.lounge_id
        WHERE wl.wedding_id = cg.wedding_id AND ge.id = cg.guestbook_entry_id
    ))::bigint AS attended_count
FROM v3_cash_gifts cg
WHERE cg.wedding_id = $1
`

type GetCashGiftsSummaryRow struct {
	TotalAmount   int64 `json:"total_amount"`
	TotalCount    int64 `json:"total_count"`
	AttendedCount int64 `json:"attended_count"`
}

func (q *Queries) GetCashGiftsSummary(ctx context.Context, weddingID pgtype.UUID) (GetCashGiftsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getCashGiftsSummary, weddingID)
	var i GetCashGiftsSummaryRow
	err := row.Scan(&i.TotalAmount, &i.TotalCount, &i.AttendedCount)
	return i, err
}

const insertCashGift = `-- name: InsertCashGift :one

INSERT INTO v3_cash_gifts (wedding_id, guest_name, guest_id, recipient_slot, relation_category, relation_detail, amount, pay_method, guestbook_entry_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING v3_cash_gifts.id, v3_cash_gifts.wedding_id, v3_cash_gifts.guest_name, v3_cash_gifts.guest_id, v3_cash_gifts.recipient_slot, v3_cash_gifts.relation_category, v3_cash_gifts.relation_detail, v3_cash_gifts.amount, v3_cash_gifts.pay_method, v3_cash_gifts.guestbook_entry_id, v3_cash_gifts.created_at,
    EXISTS (
        SELECT 1 FROM v3_guestbook_entries ge
        JOIN v3_wedding_lounges wl ON wl.id = ge.lounge_id
        WHERE wl.wedding_id = v3_cash_gifts.wedding_id AND ge.id = v3_cash_gifts.guestbook_entry_id
    ) AS attended
`

type InsertCashGiftParams struct {
	WeddingID        pgtype.UUID `json:"wedding_id"`
	GuestName        string      `json:"guest_name"`
	GuestID          pgtype.UUID `json:"guest_id"`
	RecipientSlot    string      `json:"recipient_slot"`
	RelationCategory string      `json:"relation_category"`
	RelationDetail   pgtype.Text `json:"relation_detail"`
	Amount           int32       `json:"amount"`
	PayMethod        string      `json:"pay_method"`
	GuestbookEntryID pgtype.UUID `json:"guestbook_entry_id"`
}

type InsertCashGiftRow struct {
	ID               pgtype.UUID        `json:"id"`
	WeddingID        pgtype.UUID        `json:"wedding_id"`
	GuestName        string             `json:"guest_name"`
	GuestID          pgtype.UUID        `json:"guest_id"`
	RecipientSlot    string             `json:"recipient_slot"`
	RelationCategory string             `json:"relation_category"`
	RelationDetail   pgtype.Text        `json:"relation_detail"`
	Amount           int32              `json:"amount"`
	PayMethod        string             `json:"pay_method"`
	GuestbookEntryID pgtype.UUID        `json:"guestbook_entry_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Attended         bool               `json:"attended"`
}

// attended 도출 규약: cash_gift.guestbook_entry_id가 해당 결혼식 라운지의
// GuestbookEntry를 직접 가리키면 현장참석(true). 호스트 수기 입력 등 미연결
// (guestbook_entry_id NULL)은 false. is_attended 캐시 컬럼 폐지(R2),
// guest_id claim 기준 폐지(P1: 비로그인 게스트 플로우 링크 기반으로 전환).
func (q *Queries) InsertCashGift(ctx context.Context, arg InsertCashGiftParams) (InsertCashGiftRow, error) {
	row := q.db.QueryRow(ctx, insertCashGift,
		arg.WeddingID,
		arg.GuestName,
		arg.GuestID,
		arg.RecipientSlot,
		arg.RelationCategory,
		arg.RelationDetail,
		arg.Amount,
		arg.PayMethod,
		arg.GuestbookEntryID,
	)
	var i InsertCashGiftRow
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.GuestName,
		&i.GuestID,
		&i.RecipientSlot,
		&i.RelationCategory,
		&i.RelationDetail,
		&i.Amount,
		&i.PayMethod,
		&i.GuestbookEntryID,
		&i.CreatedAt,
		&i.Attended,
	)
	return i, err
}

const listCashGiftsByWedding = `-- name: ListCashGiftsByWedding :many
SELECT cg.id, cg.wedding_id, cg.guest_name, cg.guest_id, cg.recipient_slot, cg.relation_category, cg.relation_detail, cg.amount, cg.pay_method, cg.guestbook_entry_id, cg.created_at,
    EXISTS (
        SELECT 1 FROM v3_guestbook_entries ge
        JOIN v3_wedding_lounges wl ON wl.id = ge.lounge_id
        WHERE wl.wedding_id = cg.wedding_id AND ge.id = cg.guestbook_entry_id
    ) AS attended
FROM v3_cash_gifts cg
WHERE cg.wedding_id = $1
  AND ($3::timestamptz IS NULL OR cg.created_at < $3::timestamptz)
ORDER BY cg.created_at DESC
LIMIT $2
`

type ListCashGiftsByWeddingParams struct {
	WeddingID pgtype.UUID        `json:"wedding_id"`
	Limit     int32              `json:"limit"`
	Cursor    pgtype.Timestamptz `json:"cursor"`
}

type ListCashGiftsByWeddingRow struct {
	ID               pgtype.UUID        `json:"id"`
	WeddingID        pgtype.UUID        `json:"wedding_id"`
	GuestName        string             `json:"guest_name"`
	GuestID          pgtype.UUID        `json:"guest_id"`
	RecipientSlot    string             `json:"recipient_slot"`
	RelationCategory string             `json:"relation_category"`
	RelationDetail   pgtype.Text        `json:"relation_detail"`
	Amount           int32              `json:"amount"`
	PayMethod        string             `json:"pay_method"`
	GuestbookEntryID pgtype.UUID        `json:"guestbook_entry_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Attended         bool               `json:"attended"`
}

func (q *Queries) ListCashGiftsByWedding(ctx context.Context, arg ListCashGiftsByWeddingParams) ([]ListCashGiftsByWeddingRow, error) {
	rows, err := q.db.Query(ctx, listCashGiftsByWedding, arg.WeddingID, arg.Limit, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCashGiftsByWeddingRow{}
	for rows.Next() {
		var i ListCashGiftsByWeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.WeddingID,
			&i.GuestName,
			&i.GuestID,
			&i.RecipientSlot,
			&i.RelationCategory,
			&i.RelationDetail,
			&i.Amount,
			&i.PayMethod,
			&i.GuestbookEntryID,
			&i.CreatedAt,
			&i.Attended,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCashGift = `-- name: UpdateCashGift :one
UPDATE v3_cash_gifts
SET guest_name = $2,
    amount = $3,
    relation_category = $4,
    relation_detail = $5,
    pay_method = $6
WHERE v3_cash_gifts.id = $1
RETURNING v3_cash_gifts.id, v3_cash_gifts.wedding_id, v3_cash_gifts.guest_name, v3_cash_gifts.guest_id, v3_cash_gifts.recipient_slot, v3_cash_gifts.relation_category, v3_cash_gifts.relation_detail, v3_cash_gifts.amount, v3_cash_gifts.pay_method, v3_cash_gifts.guestbook_entry_id, v3_cash_gifts.created_at,
    EXISTS (
        SELECT 1 FROM v3_guestbook_entries ge
        JOIN v3_wedding_lounges wl ON wl.id = ge.lounge_id
        WHERE wl.wedding_id = v3_cash_gifts.wedding_id AND ge.id = v3_cash_gifts.guestbook_entry_id
    ) AS attended
`

type UpdateCashGiftParams struct {
	ID               pgtype.UUID `json:"id"`
	GuestName        string      `json:"guest_name"`
	Amount           int32       `json:"amount"`
	RelationCategory string      `json:"relation_category"`
	RelationDetail   pgtype.Text `json:"relation_detail"`
	PayMethod        string      `json:"pay_method"`
}

type UpdateCashGiftRow struct {
	ID               pgtype.UUID        `json:"id"`
	WeddingID        pgtype.UUID        `json:"wedding_id"`
	GuestName        string             `json:"guest_name"`
	GuestID          pgtype.UUID        `json:"guest_id"`
	RecipientSlot    string             `json:"recipient_slot"`
	RelationCategory string             `json:"relation_category"`
	RelationDetail   pgtype.Text        `json:"relation_detail"`
	Amount           int32              `json:"amount"`
	PayMethod        string             `json:"pay_method"`
	GuestbookEntryID pgtype.UUID        `json:"guestbook_entry_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Attended         bool               `json:"attended"`
}

func (q *Queries) UpdateCashGift(ctx context.Context, arg UpdateCashGiftParams) (UpdateCashGiftRow, error) {
	row := q.db.QueryRow(ctx, updateCashGift,
		arg.ID,
		arg.GuestName,
		arg.Amount,
		arg.RelationCategory,
		arg.RelationDetail,
		arg.PayMethod,
	)
	var i UpdateCashGiftRow
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.GuestName,
		&i.GuestID,
		&i.RecipientSlot,
		&i.RelationCategory,
		&i.RelationDetail,
		&i.Amount,
		&i.PayMethod,
		&i.GuestbookEntryID,
		&i.CreatedAt,
		&i.Attended,
	)
	return i, err
}
