// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consents.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestMarketingConsent = `-- name: GetLatestMarketingConsent :one
SELECT COALESCE(
    (
        SELECT cr.agreed
        FROM public.consent_records cr
        JOIN public.terms_documents td ON td.id = cr.terms_document_id
        WHERE cr.user_id = $1 AND td.terms_type = 'marketing'
        ORDER BY cr.agreed_at DESC
        LIMIT 1
    ),
    false
)::bool AS marketing_agreed
`

// 마케팅 terms_type 최신 row의 agreed (없으면 false).
func (q *Queries) GetLatestMarketingConsent(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getLatestMarketingConsent, userID)
	var marketing_agreed bool
	err := row.Scan(&marketing_agreed)
	return marketing_agreed, err
}

const getMaxRequiredTermsVersion = `-- name: GetMaxRequiredTermsVersion :one
SELECT COALESCE(MAX(version), 0)::int AS max_version
FROM public.terms_documents
WHERE is_required = true
`

// 필수 약관 전체 중 최신 버전 (= profiles.terms_version 갱신 기준값).
func (q *Queries) GetMaxRequiredTermsVersion(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxRequiredTermsVersion)
	var max_version int32
	err := row.Scan(&max_version)
	return max_version, err
}

const getProfileTermsVersion = `-- name: GetProfileTermsVersion :one
SELECT COALESCE(
    (SELECT terms_version FROM public.profiles WHERE user_id = $1),
    -1
)::int AS terms_version
`

// 유저의 profiles.terms_version. 행 없으면 -1 반환 (CASE WHEN coalesce 트릭은 0 default와 충돌하여 -1로 명시).
func (q *Queries) GetProfileTermsVersion(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getProfileTermsVersion, userID)
	var terms_version int32
	err := row.Scan(&terms_version)
	return terms_version, err
}

const getRequiredTermsTypesLatest = `-- name: GetRequiredTermsTypesLatest :many

SELECT td.id, td.terms_type, td.version
FROM public.terms_documents td
JOIN (
    SELECT terms_type, MAX(version) AS max_version
    FROM public.terms_documents
    WHERE is_required = true
    GROUP BY terms_type
) latest
  ON td.terms_type = latest.terms_type AND td.version = latest.max_version
WHERE td.is_required = true
ORDER BY td.terms_type
`

type GetRequiredTermsTypesLatestRow struct {
	ID        int32  `json:"id"`
	TermsType string `json:"terms_type"`
	Version   int32  `json:"version"`
}

// ============================================
// Consents — onboarding 동의 게이트 + 마케팅 토글
// _scenario/2026-05-26-user-consent-onboarding/SCENARIOS.md
// ============================================
// 현행 필수 약관의 terms_type별 최신 버전 행 (게이트 판정 + INSERT 시 mapping).
func (q *Queries) GetRequiredTermsTypesLatest(ctx context.Context) ([]GetRequiredTermsTypesLatestRow, error) {
	rows, err := q.db.Query(ctx, getRequiredTermsTypesLatest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRequiredTermsTypesLatestRow{}
	for rows.Next() {
		var i GetRequiredTermsTypesLatestRow
		if err := rows.Scan(&i.ID, &i.TermsType, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTermsDocumentByTypeLatest = `-- name: GetTermsDocumentByTypeLatest :one
SELECT id, terms_type, version, is_required
FROM public.terms_documents
WHERE terms_type = $1
ORDER BY version DESC
LIMIT 1
`

type GetTermsDocumentByTypeLatestRow struct {
	ID         int32  `json:"id"`
	TermsType  string `json:"terms_type"`
	Version    int32  `json:"version"`
	IsRequired bool   `json:"is_required"`
}

// 단일 terms_type의 최신 row (marketing 같은 선택 약관 INSERT용).
func (q *Queries) GetTermsDocumentByTypeLatest(ctx context.Context, termsType string) (GetTermsDocumentByTypeLatestRow, error) {
	row := q.db.QueryRow(ctx, getTermsDocumentByTypeLatest, termsType)
	var i GetTermsDocumentByTypeLatestRow
	err := row.Scan(
		&i.ID,
		&i.TermsType,
		&i.Version,
		&i.IsRequired,
	)
	return i, err
}

const insertConsentRecord = `-- name: InsertConsentRecord :exec
INSERT INTO public.consent_records (
    user_id, terms_document_id, agreed, ip_address, user_agent, consent_method
) VALUES ($1, $2, $3, $4::inet, $5, 'checkbox')
`

type InsertConsentRecordParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	TermsDocumentID int32       `json:"terms_document_id"`
	Agreed          bool        `json:"agreed"`
	Column4         netip.Addr  `json:"column_4"`
	UserAgent       pgtype.Text `json:"user_agent"`
}

// append-only. 마케팅 false도 기록.
func (q *Queries) InsertConsentRecord(ctx context.Context, arg InsertConsentRecordParams) error {
	_, err := q.db.Exec(ctx, insertConsentRecord,
		arg.UserID,
		arg.TermsDocumentID,
		arg.Agreed,
		arg.Column4,
		arg.UserAgent,
	)
	return err
}

const upsertProfileTermsVersion = `-- name: UpsertProfileTermsVersion :exec
INSERT INTO public.profiles (user_id, display_name, terms_version)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET terms_version = EXCLUDED.terms_version,
    updated_at    = now()
`

type UpsertProfileTermsVersionParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	DisplayName  string      `json:"display_name"`
	TermsVersion int32       `json:"terms_version"`
}

// profiles 행 없으면 INSERT, 있으면 terms_version UPDATE.
// display_name은 INSERT 시에만 사용. v3_users.name을 caller가 넘겨줌.
func (q *Queries) UpsertProfileTermsVersion(ctx context.Context, arg UpsertProfileTermsVersionParams) error {
	_, err := q.db.Exec(ctx, upsertProfileTermsVersion, arg.UserID, arg.DisplayName, arg.TermsVersion)
	return err
}
