// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gather_places.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertGatherPlace = `-- name: InsertGatherPlace :one
INSERT INTO v3_moi_gather_places (lounge_id, type)
VALUES ($1, $2)
RETURNING id, lounge_id, type
`

type InsertGatherPlaceParams struct {
	LoungeID pgtype.UUID `json:"lounge_id"`
	Type     string      `json:"type"`
}

func (q *Queries) InsertGatherPlace(ctx context.Context, arg InsertGatherPlaceParams) (V3MoiGatherPlace, error) {
	row := q.db.QueryRow(ctx, insertGatherPlace, arg.LoungeID, arg.Type)
	var i V3MoiGatherPlace
	err := row.Scan(&i.ID, &i.LoungeID, &i.Type)
	return i, err
}
