// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guestbook.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimGuestbookEntry = `-- name: ClaimGuestbookEntry :exec
UPDATE v3_guestbook_entries
SET guest_id = $2
WHERE id = $1 AND guest_id IS NULL
`

type ClaimGuestbookEntryParams struct {
	ID      pgtype.UUID `json:"id"`
	GuestID pgtype.UUID `json:"guest_id"`
}

func (q *Queries) ClaimGuestbookEntry(ctx context.Context, arg ClaimGuestbookEntryParams) error {
	_, err := q.db.Exec(ctx, claimGuestbookEntry, arg.ID, arg.GuestID)
	return err
}

const createGuestbookEntry = `-- name: CreateGuestbookEntry :one
INSERT INTO v3_guestbook_entries (lounge_id, guest_name, guest_id, recipient_slot, relation_category, relation_detail)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, lounge_id, guest_name, guest_id, created_at, recipient_slot, relation_category, relation_detail
`

type CreateGuestbookEntryParams struct {
	LoungeID         pgtype.UUID `json:"lounge_id"`
	GuestName        string      `json:"guest_name"`
	GuestID          pgtype.UUID `json:"guest_id"`
	RecipientSlot    string      `json:"recipient_slot"`
	RelationCategory string      `json:"relation_category"`
	RelationDetail   pgtype.Text `json:"relation_detail"`
}

// entries.message 컬럼은 20260525130000 마이그레이션으로 드롭됨.
// 본문은 v3_guestbook_messages에 별도 INSERT (service 레이어가 같은 트랜잭션 안에서 처리).
func (q *Queries) CreateGuestbookEntry(ctx context.Context, arg CreateGuestbookEntryParams) (V3GuestbookEntry, error) {
	row := q.db.QueryRow(ctx, createGuestbookEntry,
		arg.LoungeID,
		arg.GuestName,
		arg.GuestID,
		arg.RecipientSlot,
		arg.RelationCategory,
		arg.RelationDetail,
	)
	var i V3GuestbookEntry
	err := row.Scan(
		&i.ID,
		&i.LoungeID,
		&i.GuestName,
		&i.GuestID,
		&i.CreatedAt,
		&i.RecipientSlot,
		&i.RelationCategory,
		&i.RelationDetail,
	)
	return i, err
}

const getGuestbookEntryByGuestAndLounge = `-- name: GetGuestbookEntryByGuestAndLounge :one

SELECT id, lounge_id, guest_name, guest_id, created_at, recipient_slot, relation_category, relation_detail
FROM v3_guestbook_entries
WHERE guest_id = $1 AND lounge_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetGuestbookEntryByGuestAndLoungeParams struct {
	GuestID  pgtype.UUID `json:"guest_id"`
	LoungeID pgtype.UUID `json:"lounge_id"`
}

// UpdateGuestbookEntryMessage 쿼리는 20260525130000 마이그레이션 이후 폐기.
// 메시지 편집은 별도 messages 도메인(v3_guestbook_messages)으로 이전.
func (q *Queries) GetGuestbookEntryByGuestAndLounge(ctx context.Context, arg GetGuestbookEntryByGuestAndLoungeParams) (V3GuestbookEntry, error) {
	row := q.db.QueryRow(ctx, getGuestbookEntryByGuestAndLounge, arg.GuestID, arg.LoungeID)
	var i V3GuestbookEntry
	err := row.Scan(
		&i.ID,
		&i.LoungeID,
		&i.GuestName,
		&i.GuestID,
		&i.CreatedAt,
		&i.RecipientSlot,
		&i.RelationCategory,
		&i.RelationDetail,
	)
	return i, err
}

const listGuestbookEntries = `-- name: ListGuestbookEntries :many
SELECT id, lounge_id, guest_name, guest_id, created_at, recipient_slot, relation_category, relation_detail
FROM v3_guestbook_entries
WHERE lounge_id = $1
  AND ($3::timestamptz IS NULL OR created_at < $3::timestamptz)
ORDER BY created_at DESC
LIMIT $2
`

type ListGuestbookEntriesParams struct {
	LoungeID pgtype.UUID        `json:"lounge_id"`
	Limit    int32              `json:"limit"`
	Cursor   pgtype.Timestamptz `json:"cursor"`
}

func (q *Queries) ListGuestbookEntries(ctx context.Context, arg ListGuestbookEntriesParams) ([]V3GuestbookEntry, error) {
	rows, err := q.db.Query(ctx, listGuestbookEntries, arg.LoungeID, arg.Limit, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []V3GuestbookEntry{}
	for rows.Next() {
		var i V3GuestbookEntry
		if err := rows.Scan(
			&i.ID,
			&i.LoungeID,
			&i.GuestName,
			&i.GuestID,
			&i.CreatedAt,
			&i.RecipientSlot,
			&i.RelationCategory,
			&i.RelationDetail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
