// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guestbook_messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGuestbookMessage = `-- name: CreateGuestbookMessage :one
INSERT INTO v3_guestbook_messages (guestbook_entry_id, message, lounge_id)
VALUES ($1, $2, $3)
RETURNING id, guestbook_entry_id, message, lounge_id, created_at
`

type CreateGuestbookMessageParams struct {
	GuestbookEntryID pgtype.UUID `json:"guestbook_entry_id"`
	Message          string      `json:"message"`
	LoungeID         pgtype.UUID `json:"lounge_id"`
}

// LIVE 축하메세지(현장 QR) 전용으로 책임 환원. 사진은 v3_memories 도메인이 담당.
// lounge_id는 부모 GuestbookEntry에서 조회해 service가 명시 전달(mecdisplay Realtime
// 구독 `filter:lounge_id=eq.X`의 전제).
func (q *Queries) CreateGuestbookMessage(ctx context.Context, arg CreateGuestbookMessageParams) (V3GuestbookMessage, error) {
	row := q.db.QueryRow(ctx, createGuestbookMessage, arg.GuestbookEntryID, arg.Message, arg.LoungeID)
	var i V3GuestbookMessage
	err := row.Scan(
		&i.ID,
		&i.GuestbookEntryID,
		&i.Message,
		&i.LoungeID,
		&i.CreatedAt,
	)
	return i, err
}

const getGuestbookEntryLoungeID = `-- name: GetGuestbookEntryLoungeID :one
SELECT lounge_id FROM v3_guestbook_entries WHERE id = $1
`

// mecdisplay 워크스트림: 메세지 INSERT 시 부모 entry의 lounge_id를 비정규화 컬럼에
// 채우기 위한 단순 조회. entry 미존재 시 pgx.ErrNoRows.
func (q *Queries) GetGuestbookEntryLoungeID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getGuestbookEntryLoungeID, id)
	var lounge_id pgtype.UUID
	err := row.Scan(&lounge_id)
	return lounge_id, err
}

const getGuestbookMessageEntryGuest = `-- name: GetGuestbookMessageEntryGuest :one
SELECT ge.guest_id
FROM v3_guestbook_messages gm
JOIN v3_guestbook_entries ge ON ge.id = gm.guestbook_entry_id
WHERE gm.id = $1
`

// 본인(작성자) 판정용: 메세지 → 소속 GuestbookEntry → guest_id.
// 행이 없으면 메세지 미존재(404). guest_id는 비로그인 작성 시 NULL.
func (q *Queries) GetGuestbookMessageEntryGuest(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getGuestbookMessageEntryGuest, id)
	var guest_id pgtype.UUID
	err := row.Scan(&guest_id)
	return guest_id, err
}

const recordGuestbookMessageView = `-- name: RecordGuestbookMessageView :exec
INSERT INTO v3_guestbook_message_views (guestbook_message_id, viewer_id)
VALUES ($1, $2)
ON CONFLICT (guestbook_message_id, viewer_id) DO NOTHING
`

type RecordGuestbookMessageViewParams struct {
	GuestbookMessageID pgtype.UUID `json:"guestbook_message_id"`
	ViewerID           pgtype.UUID `json:"viewer_id"`
}

// 조회 기록. 동일 (message, viewer) 중복은 UNIQUE로 멱등(첫 1회만 적재).
func (q *Queries) RecordGuestbookMessageView(ctx context.Context, arg RecordGuestbookMessageViewParams) error {
	_, err := q.db.Exec(ctx, recordGuestbookMessageView, arg.GuestbookMessageID, arg.ViewerID)
	return err
}
