// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host_invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptHostInvite = `-- name: AcceptHostInvite :one
UPDATE v3_host_invites
SET status = 'accepted',
    invited_user_id = $2,
    accepted_at = now()
WHERE token = $1 AND status = 'pending'
RETURNING id, wedding_id, slot, token, status, invited_user_id, created_at, accepted_at
`

type AcceptHostInviteParams struct {
	Token         string      `json:"token"`
	InvitedUserID pgtype.UUID `json:"invited_user_id"`
}

func (q *Queries) AcceptHostInvite(ctx context.Context, arg AcceptHostInviteParams) (V3HostInvite, error) {
	row := q.db.QueryRow(ctx, acceptHostInvite, arg.Token, arg.InvitedUserID)
	var i V3HostInvite
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.Slot,
		&i.Token,
		&i.Status,
		&i.InvitedUserID,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const cancelHostInvite = `-- name: CancelHostInvite :exec
UPDATE v3_host_invites
SET status = 'cancelled'
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) CancelHostInvite(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelHostInvite, id)
	return err
}

const getHostInviteByID = `-- name: GetHostInviteByID :one
SELECT id, wedding_id, slot, token, status, invited_user_id, created_at, accepted_at FROM v3_host_invites WHERE id = $1
`

func (q *Queries) GetHostInviteByID(ctx context.Context, id pgtype.UUID) (V3HostInvite, error) {
	row := q.db.QueryRow(ctx, getHostInviteByID, id)
	var i V3HostInvite
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.Slot,
		&i.Token,
		&i.Status,
		&i.InvitedUserID,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const getHostInviteByToken = `-- name: GetHostInviteByToken :one
SELECT hi.id, hi.wedding_id, hi.slot, hi.token, hi.status, hi.invited_user_id, hi.created_at, hi.accepted_at, w.groom_name, w.bride_name, w.date, w.venue_name
FROM v3_host_invites hi
JOIN v3_weddings w ON w.id = hi.wedding_id
WHERE hi.token = $1
`

type GetHostInviteByTokenRow struct {
	ID            pgtype.UUID        `json:"id"`
	WeddingID     pgtype.UUID        `json:"wedding_id"`
	Slot          string             `json:"slot"`
	Token         string             `json:"token"`
	Status        string             `json:"status"`
	InvitedUserID pgtype.UUID        `json:"invited_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	AcceptedAt    pgtype.Timestamptz `json:"accepted_at"`
	GroomName     string             `json:"groom_name"`
	BrideName     string             `json:"bride_name"`
	Date          pgtype.Date        `json:"date"`
	VenueName     string             `json:"venue_name"`
}

func (q *Queries) GetHostInviteByToken(ctx context.Context, token string) (GetHostInviteByTokenRow, error) {
	row := q.db.QueryRow(ctx, getHostInviteByToken, token)
	var i GetHostInviteByTokenRow
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.Slot,
		&i.Token,
		&i.Status,
		&i.InvitedUserID,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.GroomName,
		&i.BrideName,
		&i.Date,
		&i.VenueName,
	)
	return i, err
}

const getPendingInviteBySlot = `-- name: GetPendingInviteBySlot :one
SELECT id, wedding_id, slot, token, status, invited_user_id, created_at, accepted_at FROM v3_host_invites
WHERE wedding_id = $1 AND slot = $2 AND status = 'pending'
LIMIT 1
`

type GetPendingInviteBySlotParams struct {
	WeddingID pgtype.UUID `json:"wedding_id"`
	Slot      string      `json:"slot"`
}

func (q *Queries) GetPendingInviteBySlot(ctx context.Context, arg GetPendingInviteBySlotParams) (V3HostInvite, error) {
	row := q.db.QueryRow(ctx, getPendingInviteBySlot, arg.WeddingID, arg.Slot)
	var i V3HostInvite
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.Slot,
		&i.Token,
		&i.Status,
		&i.InvitedUserID,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const insertHostInvite = `-- name: InsertHostInvite :one
INSERT INTO v3_host_invites (wedding_id, slot, token)
VALUES ($1, $2, $3)
RETURNING id, wedding_id, slot, token, status, invited_user_id, created_at, accepted_at
`

type InsertHostInviteParams struct {
	WeddingID pgtype.UUID `json:"wedding_id"`
	Slot      string      `json:"slot"`
	Token     string      `json:"token"`
}

func (q *Queries) InsertHostInvite(ctx context.Context, arg InsertHostInviteParams) (V3HostInvite, error) {
	row := q.db.QueryRow(ctx, insertHostInvite, arg.WeddingID, arg.Slot, arg.Token)
	var i V3HostInvite
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.Slot,
		&i.Token,
		&i.Status,
		&i.InvitedUserID,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const listHostInvitesByWeddingID = `-- name: ListHostInvitesByWeddingID :many
SELECT id, wedding_id, slot, token, status, invited_user_id, created_at, accepted_at FROM v3_host_invites
WHERE wedding_id = $1
ORDER BY created_at
`

func (q *Queries) ListHostInvitesByWeddingID(ctx context.Context, weddingID pgtype.UUID) ([]V3HostInvite, error) {
	rows, err := q.db.Query(ctx, listHostInvitesByWeddingID, weddingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []V3HostInvite{}
	for rows.Next() {
		var i V3HostInvite
		if err := rows.Scan(
			&i.ID,
			&i.WeddingID,
			&i.Slot,
			&i.Token,
			&i.Status,
			&i.InvitedUserID,
			&i.CreatedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
