// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInvitationsByWeddingID = `-- name: CountInvitationsByWeddingID :one
SELECT COUNT(*) FROM v3_mobile_invitations WHERE wedding_id = $1
`

func (q *Queries) CountInvitationsByWeddingID(ctx context.Context, weddingID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInvitationsByWeddingID, weddingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM v3_mobile_invitations WHERE id = $1
`

func (q *Queries) DeleteInvitation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvitation, id)
	return err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, wedding_id, design_template_id, custom_message, visited_count, heart_count, gallery_photos, cover_image, cover_text_config, design_config, created_at, slug, version FROM v3_mobile_invitations WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id pgtype.UUID) (V3MobileInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i V3MobileInvitation
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.DesignTemplateID,
		&i.CustomMessage,
		&i.VisitedCount,
		&i.HeartCount,
		&i.GalleryPhotos,
		&i.CoverImage,
		&i.CoverTextConfig,
		&i.DesignConfig,
		&i.CreatedAt,
		&i.Slug,
		&i.Version,
	)
	return i, err
}

const getInvitationBySlug = `-- name: GetInvitationBySlug :one
SELECT i.id, i.wedding_id, i.design_template_id, i.custom_message, i.visited_count, i.heart_count, i.gallery_photos, i.cover_image, i.cover_text_config, i.design_config, i.created_at, i.slug, i.version, w.groom_name, w.bride_name, w.date, w."time",
       w.venue_name, w.venue_address, w.venue_hall,
       w.groom_father_name, w.groom_mother_name,
       w.bride_father_name, w.bride_mother_name,
       w.groom_father_deceased, w.groom_mother_deceased,
       w.bride_father_deceased, w.bride_mother_deceased,
       w.groom_account, w.bride_account,
       w.groom_father_account, w.groom_mother_account,
       w.bride_father_account, w.bride_mother_account
FROM v3_mobile_invitations i
JOIN v3_weddings w ON w.id = i.wedding_id
WHERE i.slug = $1
`

type GetInvitationBySlugRow struct {
	ID                  pgtype.UUID        `json:"id"`
	WeddingID           pgtype.UUID        `json:"wedding_id"`
	DesignTemplateID    string             `json:"design_template_id"`
	CustomMessage       pgtype.Text        `json:"custom_message"`
	VisitedCount        int32              `json:"visited_count"`
	HeartCount          int32              `json:"heart_count"`
	GalleryPhotos       []byte             `json:"gallery_photos"`
	CoverImage          pgtype.Text        `json:"cover_image"`
	CoverTextConfig     []byte             `json:"cover_text_config"`
	DesignConfig        []byte             `json:"design_config"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	Slug                string             `json:"slug"`
	Version             int32              `json:"version"`
	GroomName           string             `json:"groom_name"`
	BrideName           string             `json:"bride_name"`
	Date                pgtype.Date        `json:"date"`
	Time                string             `json:"time"`
	VenueName           string             `json:"venue_name"`
	VenueAddress        string             `json:"venue_address"`
	VenueHall           pgtype.Text        `json:"venue_hall"`
	GroomFatherName     pgtype.Text        `json:"groom_father_name"`
	GroomMotherName     pgtype.Text        `json:"groom_mother_name"`
	BrideFatherName     pgtype.Text        `json:"bride_father_name"`
	BrideMotherName     pgtype.Text        `json:"bride_mother_name"`
	GroomFatherDeceased bool               `json:"groom_father_deceased"`
	GroomMotherDeceased bool               `json:"groom_mother_deceased"`
	BrideFatherDeceased bool               `json:"bride_father_deceased"`
	BrideMotherDeceased bool               `json:"bride_mother_deceased"`
	GroomAccount        []byte             `json:"groom_account"`
	BrideAccount        []byte             `json:"bride_account"`
	GroomFatherAccount  []byte             `json:"groom_father_account"`
	GroomMotherAccount  []byte             `json:"groom_mother_account"`
	BrideFatherAccount  []byte             `json:"bride_father_account"`
	BrideMotherAccount  []byte             `json:"bride_mother_account"`
}

func (q *Queries) GetInvitationBySlug(ctx context.Context, slug string) (GetInvitationBySlugRow, error) {
	row := q.db.QueryRow(ctx, getInvitationBySlug, slug)
	var i GetInvitationBySlugRow
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.DesignTemplateID,
		&i.CustomMessage,
		&i.VisitedCount,
		&i.HeartCount,
		&i.GalleryPhotos,
		&i.CoverImage,
		&i.CoverTextConfig,
		&i.DesignConfig,
		&i.CreatedAt,
		&i.Slug,
		&i.Version,
		&i.GroomName,
		&i.BrideName,
		&i.Date,
		&i.Time,
		&i.VenueName,
		&i.VenueAddress,
		&i.VenueHall,
		&i.GroomFatherName,
		&i.GroomMotherName,
		&i.BrideFatherName,
		&i.BrideMotherName,
		&i.GroomFatherDeceased,
		&i.GroomMotherDeceased,
		&i.BrideFatherDeceased,
		&i.BrideMotherDeceased,
		&i.GroomAccount,
		&i.BrideAccount,
		&i.GroomFatherAccount,
		&i.GroomMotherAccount,
		&i.BrideFatherAccount,
		&i.BrideMotherAccount,
	)
	return i, err
}

const incrementHeartCount = `-- name: IncrementHeartCount :one
UPDATE v3_mobile_invitations
SET heart_count = heart_count + 1
WHERE slug = $1
RETURNING heart_count
`

func (q *Queries) IncrementHeartCount(ctx context.Context, slug string) (int32, error) {
	row := q.db.QueryRow(ctx, incrementHeartCount, slug)
	var heart_count int32
	err := row.Scan(&heart_count)
	return heart_count, err
}

const insertInvitation = `-- name: InsertInvitation :one
INSERT INTO v3_mobile_invitations (wedding_id, slug, design_template_id)
VALUES ($1, $2, $3)
RETURNING id, wedding_id, design_template_id, custom_message, visited_count, heart_count, gallery_photos, cover_image, cover_text_config, design_config, created_at, slug, version
`

type InsertInvitationParams struct {
	WeddingID        pgtype.UUID `json:"wedding_id"`
	Slug             string      `json:"slug"`
	DesignTemplateID string      `json:"design_template_id"`
}

func (q *Queries) InsertInvitation(ctx context.Context, arg InsertInvitationParams) (V3MobileInvitation, error) {
	row := q.db.QueryRow(ctx, insertInvitation, arg.WeddingID, arg.Slug, arg.DesignTemplateID)
	var i V3MobileInvitation
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.DesignTemplateID,
		&i.CustomMessage,
		&i.VisitedCount,
		&i.HeartCount,
		&i.GalleryPhotos,
		&i.CoverImage,
		&i.CoverTextConfig,
		&i.DesignConfig,
		&i.CreatedAt,
		&i.Slug,
		&i.Version,
	)
	return i, err
}

const listInvitationsByWeddingID = `-- name: ListInvitationsByWeddingID :many
SELECT id, slug, cover_image FROM v3_mobile_invitations WHERE wedding_id = $1 ORDER BY created_at
`

type ListInvitationsByWeddingIDRow struct {
	ID         pgtype.UUID `json:"id"`
	Slug       string      `json:"slug"`
	CoverImage pgtype.Text `json:"cover_image"`
}

func (q *Queries) ListInvitationsByWeddingID(ctx context.Context, weddingID pgtype.UUID) ([]ListInvitationsByWeddingIDRow, error) {
	rows, err := q.db.Query(ctx, listInvitationsByWeddingID, weddingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsByWeddingIDRow{}
	for rows.Next() {
		var i ListInvitationsByWeddingIDRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.CoverImage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvitation = `-- name: UpdateInvitation :one
UPDATE v3_mobile_invitations
SET design_template_id = COALESCE($2, design_template_id),
    custom_message = COALESCE($3, custom_message),
    gallery_photos = COALESCE(convert_from($4, 'UTF8')::jsonb, gallery_photos),
    cover_image = COALESCE($5, cover_image),
    cover_text_config = COALESCE(convert_from($6, 'UTF8')::jsonb, cover_text_config),
    design_config = COALESCE(convert_from($7, 'UTF8')::jsonb, design_config),
    version = version + 1
WHERE id = $1 AND ($8 < 0 OR version = $8)
RETURNING id, wedding_id, design_template_id, custom_message, visited_count, heart_count, gallery_photos, cover_image, cover_text_config, design_config, created_at, slug, version
`

type UpdateInvitationParams struct {
	ID               pgtype.UUID `json:"id"`
	DesignTemplateID pgtype.Text `json:"design_template_id"`
	CustomMessage    pgtype.Text `json:"custom_message"`
	GalleryPhotos    []byte      `json:"gallery_photos"`
	CoverImage       pgtype.Text `json:"cover_image"`
	CoverTextConfig  []byte      `json:"cover_text_config"`
	DesignConfig     []byte      `json:"design_config"`
	ExpectedVersion  interface{} `json:"expected_version"`
}

func (q *Queries) UpdateInvitation(ctx context.Context, arg UpdateInvitationParams) (V3MobileInvitation, error) {
	row := q.db.QueryRow(ctx, updateInvitation,
		arg.ID,
		arg.DesignTemplateID,
		arg.CustomMessage,
		arg.GalleryPhotos,
		arg.CoverImage,
		arg.CoverTextConfig,
		arg.DesignConfig,
		arg.ExpectedVersion,
	)
	var i V3MobileInvitation
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.DesignTemplateID,
		&i.CustomMessage,
		&i.VisitedCount,
		&i.HeartCount,
		&i.GalleryPhotos,
		&i.CoverImage,
		&i.CoverTextConfig,
		&i.DesignConfig,
		&i.CreatedAt,
		&i.Slug,
		&i.Version,
	)
	return i, err
}
