// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lounges.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLoungeByID = `-- name: GetLoungeByID :one
SELECT l.id, l.wedding_id, l.name, gp.id as gather_place_id, gp.type as gather_place_type
FROM v3_wedding_lounges l
JOIN v3_moi_gather_places gp ON gp.lounge_id = l.id
WHERE l.id = $1
`

type GetLoungeByIDRow struct {
	ID              pgtype.UUID `json:"id"`
	WeddingID       pgtype.UUID `json:"wedding_id"`
	Name            string      `json:"name"`
	GatherPlaceID   pgtype.UUID `json:"gather_place_id"`
	GatherPlaceType string      `json:"gather_place_type"`
}

func (q *Queries) GetLoungeByID(ctx context.Context, id pgtype.UUID) (GetLoungeByIDRow, error) {
	row := q.db.QueryRow(ctx, getLoungeByID, id)
	var i GetLoungeByIDRow
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.Name,
		&i.GatherPlaceID,
		&i.GatherPlaceType,
	)
	return i, err
}

const getWeddingIDByLoungeID = `-- name: GetWeddingIDByLoungeID :one
SELECT wedding_id FROM v3_wedding_lounges WHERE id = $1
`

func (q *Queries) GetWeddingIDByLoungeID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getWeddingIDByLoungeID, id)
	var wedding_id pgtype.UUID
	err := row.Scan(&wedding_id)
	return wedding_id, err
}

const insertLounge = `-- name: InsertLounge :one
INSERT INTO v3_wedding_lounges (wedding_id, name)
VALUES ($1, $2)
RETURNING id, wedding_id, name, sui_lounge_id
`

type InsertLoungeParams struct {
	WeddingID pgtype.UUID `json:"wedding_id"`
	Name      string      `json:"name"`
}

func (q *Queries) InsertLounge(ctx context.Context, arg InsertLoungeParams) (V3WeddingLounge, error) {
	row := q.db.QueryRow(ctx, insertLounge, arg.WeddingID, arg.Name)
	var i V3WeddingLounge
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.Name,
		&i.SuiLoungeID,
	)
	return i, err
}
