// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lounge_check_ins.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureMoi = `-- name: EnsureMoi :exec
INSERT INTO v3_mois (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
`

// JIT 프로비저닝: 유저의 Moi 행을 멱등 보장(v3_mois_user_id_key UNIQUE 기반).
// id=gen_random_uuid 기본, equipped_items='{}' 기본 → user_id만 필요. v3_users 선행 필수(FK).
func (q *Queries) EnsureMoi(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureMoi, userID)
	return err
}

const getGatherPlaceByLoungeID = `-- name: GetGatherPlaceByLoungeID :one
SELECT id FROM v3_moi_gather_places WHERE lounge_id = $1
`

func (q *Queries) GetGatherPlaceByLoungeID(ctx context.Context, loungeID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getGatherPlaceByLoungeID, loungeID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getLoungeCheckInByUserAndLounge = `-- name: GetLoungeCheckInByUserAndLounge :one
SELECT id, user_id, lounge_id, visitor_name, created_at, recipient_slot, relation_category, relation_detail
FROM v3_lounge_check_ins
WHERE user_id = $1 AND lounge_id = $2
LIMIT 1
`

type GetLoungeCheckInByUserAndLoungeParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	LoungeID pgtype.UUID `json:"lounge_id"`
}

func (q *Queries) GetLoungeCheckInByUserAndLounge(ctx context.Context, arg GetLoungeCheckInByUserAndLoungeParams) (V3LoungeCheckIn, error) {
	row := q.db.QueryRow(ctx, getLoungeCheckInByUserAndLounge, arg.UserID, arg.LoungeID)
	var i V3LoungeCheckIn
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LoungeID,
		&i.VisitorName,
		&i.CreatedAt,
		&i.RecipientSlot,
		&i.RelationCategory,
		&i.RelationDetail,
	)
	return i, err
}

const getMoiByUserID = `-- name: GetMoiByUserID :one
SELECT id FROM v3_mois WHERE user_id = $1
`

func (q *Queries) GetMoiByUserID(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMoiByUserID, userID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertLoungeCheckIn = `-- name: InsertLoungeCheckIn :one
INSERT INTO v3_lounge_check_ins (user_id, lounge_id, visitor_name, recipient_slot, relation_category, relation_detail)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, lounge_id) DO NOTHING
RETURNING id, user_id, lounge_id, visitor_name, created_at, recipient_slot, relation_category, relation_detail
`

type InsertLoungeCheckInParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	LoungeID         pgtype.UUID `json:"lounge_id"`
	VisitorName      string      `json:"visitor_name"`
	RecipientSlot    pgtype.Text `json:"recipient_slot"`
	RelationCategory pgtype.Text `json:"relation_category"`
	RelationDetail   pgtype.Text `json:"relation_detail"`
}

// 멱등 체크인: UNIQUE(user_id, lounge_id) 충돌 시 0행 반환(ErrNoRows) → 호출부가
// 기존 행을 재조회한다(race-safe get-or-create, AUD-7).
func (q *Queries) InsertLoungeCheckIn(ctx context.Context, arg InsertLoungeCheckInParams) (V3LoungeCheckIn, error) {
	row := q.db.QueryRow(ctx, insertLoungeCheckIn,
		arg.UserID,
		arg.LoungeID,
		arg.VisitorName,
		arg.RecipientSlot,
		arg.RelationCategory,
		arg.RelationDetail,
	)
	var i V3LoungeCheckIn
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LoungeID,
		&i.VisitorName,
		&i.CreatedAt,
		&i.RecipientSlot,
		&i.RelationCategory,
		&i.RelationDetail,
	)
	return i, err
}

const listLoungeCheckIns = `-- name: ListLoungeCheckIns :many
SELECT lc.id, lc.user_id, lc.lounge_id,
       lc.visitor_name,
       lc.created_at,
       CASE
           WHEN lc.user_id = w.host_groom_id THEN 'groom'
           WHEN lc.user_id = w.host_bride_id THEN 'bride'
           WHEN lc.user_id = w.host_groom_father_id THEN 'groom_father'
           WHEN lc.user_id = w.host_groom_mother_id THEN 'groom_mother'
           WHEN lc.user_id = w.host_bride_father_id THEN 'bride_father'
           WHEN lc.user_id = w.host_bride_mother_id THEN 'bride_mother'
           ELSE NULL
       END AS host_role,
       -- recipient_slot/relation_category/relation_detail는 LoungeCheckIn에서 nullable(도메인).
       -- LEFT JOIN LATERAL ge도 매칭 없으면 NULL이라 결과도 nullable. sqlc v1.30이 LATERAL의
       -- nullability를 추론하지 못해 NOT NULL string으로 생성 → NULL 스캔 시 panic.
       -- sqlc.yaml의 column override(` + "`" + `v3_lounge_check_ins.recipient_slot` + "`" + ` 등을 pgtype.Text)로 강제.
       COALESCE(lc.recipient_slot, ge.recipient_slot) AS recipient_slot,
       COALESCE(lc.relation_category, ge.relation_category) AS relation_category,
       COALESCE(lc.relation_detail, ge.relation_detail) AS relation_detail
FROM v3_lounge_check_ins lc
JOIN v3_moi_gather_places gp ON gp.lounge_id = lc.lounge_id
JOIN v3_wedding_lounges wl ON wl.id = lc.lounge_id
JOIN v3_weddings w ON w.id = wl.wedding_id
LEFT JOIN LATERAL (
    SELECT recipient_slot, relation_category, relation_detail
    FROM v3_guestbook_entries
    WHERE guest_id = lc.user_id AND lounge_id = lc.lounge_id
    ORDER BY created_at DESC
    LIMIT 1
) ge ON true
WHERE gp.id = $1
  AND ($3::timestamptz IS NULL OR lc.created_at < $3::timestamptz)
ORDER BY lc.created_at DESC
LIMIT $2
`

type ListLoungeCheckInsParams struct {
	ID     pgtype.UUID        `json:"id"`
	Limit  int32              `json:"limit"`
	Cursor pgtype.Timestamptz `json:"cursor"`
}

type ListLoungeCheckInsRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	LoungeID         pgtype.UUID        `json:"lounge_id"`
	VisitorName      string             `json:"visitor_name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	HostRole         interface{}        `json:"host_role"`
	RecipientSlot    pgtype.Text        `json:"recipient_slot"`
	RelationCategory pgtype.Text        `json:"relation_category"`
	RelationDetail   pgtype.Text        `json:"relation_detail"`
}

func (q *Queries) ListLoungeCheckIns(ctx context.Context, arg ListLoungeCheckInsParams) ([]ListLoungeCheckInsRow, error) {
	rows, err := q.db.Query(ctx, listLoungeCheckIns, arg.ID, arg.Limit, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoungeCheckInsRow{}
	for rows.Next() {
		var i ListLoungeCheckInsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LoungeID,
			&i.VisitorName,
			&i.CreatedAt,
			&i.HostRole,
			&i.RecipientSlot,
			&i.RelationCategory,
			&i.RelationDetail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
