// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMemory = `-- name: CreateMemory :one

INSERT INTO v3_memories (lounge_id, author_user_id, text, photo_url)
VALUES ($1, $2, $3, $4)
RETURNING id, lounge_id, author_user_id, text, photo_url, created_at, deleted_at
`

type CreateMemoryParams struct {
	LoungeID     pgtype.UUID `json:"lounge_id"`
	AuthorUserID pgtype.UUID `json:"author_user_id"`
	Text         string      `json:"text"`
	PhotoUrl     pgtype.Text `json:"photo_url"`
}

// v3_memories: 라운지 V2 "온기" 게시물.
// _scenario/memory-domain-split/SCENARIOS.md §1-§3.
// 식별: author_user_id(인증 user) — GuestbookEntry 무관 → 게스트·호스트 공통.
func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (V3Memory, error) {
	row := q.db.QueryRow(ctx, createMemory,
		arg.LoungeID,
		arg.AuthorUserID,
		arg.Text,
		arg.PhotoUrl,
	)
	var i V3Memory
	err := row.Scan(
		&i.ID,
		&i.LoungeID,
		&i.AuthorUserID,
		&i.Text,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMemoryByID = `-- name: GetMemoryByID :one
SELECT id, lounge_id, author_user_id, text, photo_url, created_at, deleted_at
FROM v3_memories
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMemoryByID(ctx context.Context, id pgtype.UUID) (V3Memory, error) {
	row := q.db.QueryRow(ctx, getMemoryByID, id)
	var i V3Memory
	err := row.Scan(
		&i.ID,
		&i.LoungeID,
		&i.AuthorUserID,
		&i.Text,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMemoriesByLounge = `-- name: ListMemoriesByLounge :many
SELECT id, lounge_id, author_user_id, text, photo_url, created_at, deleted_at
FROM v3_memories
WHERE lounge_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type ListMemoriesByLoungeParams struct {
	LoungeID pgtype.UUID `json:"lounge_id"`
	Limit    int32       `json:"limit"`
}

// "온기" 그리드: 라운지의 최근 Memory들. service에서 author_user_id 그룹핑 → 최근 100명 collapse.
// 그룹핑 N · 그룹별 정렬을 한 번에 받기 위해 raw list를 created_at DESC로 충분히 가져온다.
func (q *Queries) ListMemoriesByLounge(ctx context.Context, arg ListMemoriesByLoungeParams) ([]V3Memory, error) {
	rows, err := q.db.Query(ctx, listMemoriesByLounge, arg.LoungeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []V3Memory{}
	for rows.Next() {
		var i V3Memory
		if err := rows.Scan(
			&i.ID,
			&i.LoungeID,
			&i.AuthorUserID,
			&i.Text,
			&i.PhotoUrl,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMemory = `-- name: SoftDeleteMemory :execrows
UPDATE v3_memories
SET deleted_at = now()
WHERE id = $1 AND author_user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteMemoryParams struct {
	ID           pgtype.UUID `json:"id"`
	AuthorUserID pgtype.UUID `json:"author_user_id"`
}

// 본인만 삭제 — author_user_id 일치 검증을 WHERE에 포함. RETURNING으로 영향 행수 확인.
// 0행 반환 시 (id 없음·이미 삭제·다른 사용자) → service에서 ErrNotFound 또는 ErrForbidden 판단.
func (q *Queries) SoftDeleteMemory(ctx context.Context, arg SoftDeleteMemoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMemory, arg.ID, arg.AuthorUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
