// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory_book_photos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCashGiftsByWedding = `-- name: CountCashGiftsByWedding :one
SELECT count(*)::int FROM v3_cash_gifts WHERE wedding_id = $1
`

// 통계용 (메시지+축의 합산 = totalMessages).
func (q *Queries) CountCashGiftsByWedding(ctx context.Context, weddingID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countCashGiftsByWedding, weddingID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countGuestbookMessagesByWedding = `-- name: CountGuestbookMessagesByWedding :one
SELECT count(*)::int
FROM v3_guestbook_messages gm
JOIN v3_wedding_lounges wl ON wl.id = gm.lounge_id
WHERE wl.wedding_id = $1
`

// 통계용 totalGuests: wedding의 모든 라운지의 방명록 메시지 수.
func (q *Queries) CountGuestbookMessagesByWedding(ctx context.Context, weddingID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countGuestbookMessagesByWedding, weddingID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countMemoryBookPhotosByWedding = `-- name: CountMemoryBookPhotosByWedding :one
SELECT count(*)::int FROM v3_memory_book_photos WHERE wedding_id = $1
`

// status 분기용 (0건 → ready_uncurated).
func (q *Queries) CountMemoryBookPhotosByWedding(ctx context.Context, weddingID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countMemoryBookPhotosByWedding, weddingID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSharedPhotosByWedding = `-- name: CountSharedPhotosByWedding :one

SELECT count(*)::int
FROM v3_shared_photos sp
JOIN v3_wedding_lounges wl ON wl.id = sp.lounge_id
WHERE wl.wedding_id = $1
`

// RPC public.v3_upsert_memory_book_photos(uuid, uuid[], uuid)는 sqlc로 생성하지 않는다.
// 이유: SELECT function() 패턴의 파라미터 추론이 generic interface{}로 생성되어 type-safe하지 않음.
// service_memorybook.go에서 pool.Exec로 직접 호출한다.
// 이름에 v3_ prefix를 둔 이유: dev Supabase에 v2 시절 잔재 upsert_memory_book_photos(uuid, uuid[], uuid)가 존재하므로,
// 동일 시그니처로 덮어쓰지 않도록 분리. (사이드 이펙트 회피)
// 통계용: 라운지(들) 전체 공유 사진 수.
func (q *Queries) CountSharedPhotosByWedding(ctx context.Context, weddingID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countSharedPhotosByWedding, weddingID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getInvitationCoverAndGalleryForMemoryBook = `-- name: GetInvitationCoverAndGalleryForMemoryBook :one
SELECT
    cover_image,
    coalesce(gallery_photos, '[]'::jsonb) AS gallery_photos
FROM v3_mobile_invitations
WHERE wedding_id = $1
LIMIT 1
`

type GetInvitationCoverAndGalleryForMemoryBookRow struct {
	CoverImage    pgtype.Text `json:"cover_image"`
	GalleryPhotos []byte      `json:"gallery_photos"`
}

// 메모리북 표지 + 디스플레이 슬라이드쇼 소스.
// 실제 데이터는 v3_mobile_invitations 행 안의 cover_image(text URL) + gallery_photos(jsonb array of URLs).
// v3_mobile_invitation_photos 테이블은 별개로 v3에서 사실상 안 쓰임 (모청 사진은 invitation row에 통합).
// 두 칼럼 모두 public 버킷의 full URL이라 signed URL 변환 불필요.
func (q *Queries) GetInvitationCoverAndGalleryForMemoryBook(ctx context.Context, weddingID pgtype.UUID) (GetInvitationCoverAndGalleryForMemoryBookRow, error) {
	row := q.db.QueryRow(ctx, getInvitationCoverAndGalleryForMemoryBook, weddingID)
	var i GetInvitationCoverAndGalleryForMemoryBookRow
	err := row.Scan(&i.CoverImage, &i.GalleryPhotos)
	return i, err
}

const getWeddingCoupleForMemoryBook = `-- name: GetWeddingCoupleForMemoryBook :one
SELECT
    id,
    groom_name,
    bride_name,
    date,
    time,
    venue_name,
    venue_address,
    venue_hall,
    host_groom_id,
    host_bride_id,
    host_groom_father_id,
    host_groom_mother_id,
    host_bride_father_id,
    host_bride_mother_id
FROM v3_weddings
WHERE id = $1
`

type GetWeddingCoupleForMemoryBookRow struct {
	ID                pgtype.UUID `json:"id"`
	GroomName         string      `json:"groom_name"`
	BrideName         string      `json:"bride_name"`
	Date              pgtype.Date `json:"date"`
	Time              string      `json:"time"`
	VenueName         string      `json:"venue_name"`
	VenueAddress      string      `json:"venue_address"`
	VenueHall         pgtype.Text `json:"venue_hall"`
	HostGroomID       pgtype.UUID `json:"host_groom_id"`
	HostBrideID       pgtype.UUID `json:"host_bride_id"`
	HostGroomFatherID pgtype.UUID `json:"host_groom_father_id"`
	HostGroomMotherID pgtype.UUID `json:"host_groom_mother_id"`
	HostBrideFatherID pgtype.UUID `json:"host_bride_father_id"`
	HostBrideMotherID pgtype.UUID `json:"host_bride_mother_id"`
}

// 메모리북 couple 섹션. v3_weddings 필요 컬럼만.
func (q *Queries) GetWeddingCoupleForMemoryBook(ctx context.Context, id pgtype.UUID) (GetWeddingCoupleForMemoryBookRow, error) {
	row := q.db.QueryRow(ctx, getWeddingCoupleForMemoryBook, id)
	var i GetWeddingCoupleForMemoryBookRow
	err := row.Scan(
		&i.ID,
		&i.GroomName,
		&i.BrideName,
		&i.Date,
		&i.Time,
		&i.VenueName,
		&i.VenueAddress,
		&i.VenueHall,
		&i.HostGroomID,
		&i.HostBrideID,
		&i.HostGroomFatherID,
		&i.HostGroomMotherID,
		&i.HostBrideFatherID,
		&i.HostBrideMotherID,
	)
	return i, err
}

const listGuestbookMessagesForCurationByWedding = `-- name: ListGuestbookMessagesForCurationByWedding :many
SELECT
    gm.id,
    gm.message,
    gm.created_at,
    ge.guest_name,
    ge.recipient_slot,
    ge.relation_category,
    ge.relation_detail,
    (gm.message = '__HEART__')::boolean AS is_heart
FROM v3_guestbook_messages gm
JOIN v3_guestbook_entries ge ON ge.id = gm.guestbook_entry_id
JOIN v3_wedding_lounges wl ON wl.id = gm.lounge_id
WHERE wl.wedding_id = $1
ORDER BY gm.created_at ASC
`

type ListGuestbookMessagesForCurationByWeddingRow struct {
	ID               pgtype.UUID        `json:"id"`
	Message          string             `json:"message"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	GuestName        string             `json:"guest_name"`
	RecipientSlot    string             `json:"recipient_slot"`
	RelationCategory string             `json:"relation_category"`
	RelationDetail   pgtype.Text        `json:"relation_detail"`
	IsHeart          bool               `json:"is_heart"`
}

// 메시지 자동선별 입력. JOIN entries로 recipient_slot/guest_name/relation 함께 반환.
// is_heart는 message = '__HEART__' sentinel로 판정.
// 빈 문자열 제외는 service의 selectMessages에서 처리 (NULL/공백 정책 일원화).
func (q *Queries) ListGuestbookMessagesForCurationByWedding(ctx context.Context, weddingID pgtype.UUID) ([]ListGuestbookMessagesForCurationByWeddingRow, error) {
	rows, err := q.db.Query(ctx, listGuestbookMessagesForCurationByWedding, weddingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuestbookMessagesForCurationByWeddingRow{}
	for rows.Next() {
		var i ListGuestbookMessagesForCurationByWeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.CreatedAt,
			&i.GuestName,
			&i.RecipientSlot,
			&i.RelationCategory,
			&i.RelationDetail,
			&i.IsHeart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryBookPhotosByWedding = `-- name: ListMemoryBookPhotosByWedding :many

SELECT
    mbp.photo_id,
    mbp.display_order,
    sp.storage_path,
    sp.guest_user_id
FROM v3_memory_book_photos mbp
JOIN v3_shared_photos sp ON sp.id = mbp.photo_id
WHERE mbp.wedding_id = $1
ORDER BY mbp.display_order ASC
`

type ListMemoryBookPhotosByWeddingRow struct {
	PhotoID      pgtype.UUID `json:"photo_id"`
	DisplayOrder int32       `json:"display_order"`
	StoragePath  string      `json:"storage_path"`
	GuestUserID  pgtype.UUID `json:"guest_user_id"`
}

// 웨딩메모리북 큐레이션·조회 쿼리.
// _scenario/wedding-memorybook-2026-05-24/SCENARIOS.md §A, §B, §D.
// 큐레이션된 사진 목록 (display_order 순). 표시용 storage_path / guest_user_id 함께.
func (q *Queries) ListMemoryBookPhotosByWedding(ctx context.Context, weddingID pgtype.UUID) ([]ListMemoryBookPhotosByWeddingRow, error) {
	rows, err := q.db.Query(ctx, listMemoryBookPhotosByWedding, weddingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemoryBookPhotosByWeddingRow{}
	for rows.Next() {
		var i ListMemoryBookPhotosByWeddingRow
		if err := rows.Scan(
			&i.PhotoID,
			&i.DisplayOrder,
			&i.StoragePath,
			&i.GuestUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedPhotosWithGuestForWedding = `-- name: ListSharedPhotosWithGuestForWedding :many
SELECT
    sp.id              AS photo_id,
    sp.storage_path,
    sp.created_at,
    sp.guest_user_id,
    u.name             AS user_name,
    ge.guest_name      AS entry_guest_name,
    ge.recipient_slot,
    ge.relation_category,
    ge.relation_detail
FROM v3_shared_photos sp
JOIN v3_wedding_lounges wl ON wl.id = sp.lounge_id
JOIN v3_users u ON u.id = sp.guest_user_id
LEFT JOIN v3_guestbook_entries ge
    ON ge.lounge_id = sp.lounge_id AND ge.guest_id = sp.guest_user_id
WHERE wl.wedding_id = $1
ORDER BY sp.guest_user_id ASC, sp.created_at DESC
`

type ListSharedPhotosWithGuestForWeddingRow struct {
	PhotoID          pgtype.UUID        `json:"photo_id"`
	StoragePath      string             `json:"storage_path"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	GuestUserID      pgtype.UUID        `json:"guest_user_id"`
	UserName         string             `json:"user_name"`
	EntryGuestName   pgtype.Text        `json:"entry_guest_name"`
	RecipientSlot    pgtype.Text        `json:"recipient_slot"`
	RelationCategory pgtype.Text        `json:"relation_category"`
	RelationDetail   pgtype.Text        `json:"relation_detail"`
}

// 메모리북 큐레이션 페이지용 그룹 데이터 소스.
// wedding의 모든 라운지의 shared_photos에 user.name + entry(누구측·관계) JOIN.
// 호스트는 entry가 없을 수 있어 LEFT JOIN. service 레이어에서 guest_user_id로 그룹화.
func (q *Queries) ListSharedPhotosWithGuestForWedding(ctx context.Context, weddingID pgtype.UUID) ([]ListSharedPhotosWithGuestForWeddingRow, error) {
	rows, err := q.db.Query(ctx, listSharedPhotosWithGuestForWedding, weddingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedPhotosWithGuestForWeddingRow{}
	for rows.Next() {
		var i ListSharedPhotosWithGuestForWeddingRow
		if err := rows.Scan(
			&i.PhotoID,
			&i.StoragePath,
			&i.CreatedAt,
			&i.GuestUserID,
			&i.UserName,
			&i.EntryGuestName,
			&i.RecipientSlot,
			&i.RelationCategory,
			&i.RelationDetail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validateSharedPhotoIdsForWedding = `-- name: ValidateSharedPhotoIdsForWedding :many
SELECT sp.id
FROM v3_shared_photos sp
JOIN v3_wedding_lounges wl ON wl.id = sp.lounge_id
WHERE wl.wedding_id = $1 AND sp.id = ANY($2::uuid[])
`

type ValidateSharedPhotoIdsForWeddingParams struct {
	WeddingID pgtype.UUID   `json:"wedding_id"`
	Column2   []pgtype.UUID `json:"column_2"`
}

// PUT 큐레이션 시 photo_ids가 해당 wedding의 lounge들의 shared 사진인지 검증.
// 입력 photo_ids 중 유효한 것만 반환 → service에서 set diff로 invalidIds 계산.
func (q *Queries) ValidateSharedPhotoIdsForWedding(ctx context.Context, arg ValidateSharedPhotoIdsForWeddingParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, validateSharedPhotoIdsForWedding, arg.WeddingID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
