// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mobile_invitation_photos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMobileInvitationPhoto = `-- name: CreateMobileInvitationPhoto :one
INSERT INTO v3_mobile_invitation_photos (
    invitation_id, sub_kind, storage_path, file_name, file_size, mime_type, sort_order
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, invitation_id, sub_kind, storage_path, file_name, file_size, mime_type, sort_order, created_at
`

type CreateMobileInvitationPhotoParams struct {
	InvitationID pgtype.UUID `json:"invitation_id"`
	SubKind      string      `json:"sub_kind"`
	StoragePath  string      `json:"storage_path"`
	FileName     pgtype.Text `json:"file_name"`
	FileSize     pgtype.Int4 `json:"file_size"`
	MimeType     pgtype.Text `json:"mime_type"`
	SortOrder    int32       `json:"sort_order"`
}

// cover는 invitation당 1행(uniq_v3_mi_photos_cover partial UNIQUE).
// 위반 시 PostgreSQL이 23505 unique_violation 반환 → service에서 ErrCoverConflict로 매핑.
func (q *Queries) CreateMobileInvitationPhoto(ctx context.Context, arg CreateMobileInvitationPhotoParams) (V3MobileInvitationPhoto, error) {
	row := q.db.QueryRow(ctx, createMobileInvitationPhoto,
		arg.InvitationID,
		arg.SubKind,
		arg.StoragePath,
		arg.FileName,
		arg.FileSize,
		arg.MimeType,
		arg.SortOrder,
	)
	var i V3MobileInvitationPhoto
	err := row.Scan(
		&i.ID,
		&i.InvitationID,
		&i.SubKind,
		&i.StoragePath,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationWeddingID = `-- name: GetInvitationWeddingID :one
SELECT wedding_id FROM v3_mobile_invitations WHERE id = $1
`

// 권한 검증용: invitation_id → wedding_id 매핑(권한은 wedding owner 기준).
func (q *Queries) GetInvitationWeddingID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getInvitationWeddingID, id)
	var wedding_id pgtype.UUID
	err := row.Scan(&wedding_id)
	return wedding_id, err
}

const listMobileInvitationPhotosByInvitation = `-- name: ListMobileInvitationPhotosByInvitation :many

SELECT id, invitation_id, sub_kind, storage_path, file_name, file_size, mime_type, sort_order, created_at
FROM v3_mobile_invitation_photos
WHERE invitation_id = $1
ORDER BY sub_kind ASC, sort_order ASC, created_at ASC
`

// 시나리오 §8-1, §10: 청첩장 사진 (cover 1 + gallery 60장)
func (q *Queries) ListMobileInvitationPhotosByInvitation(ctx context.Context, invitationID pgtype.UUID) ([]V3MobileInvitationPhoto, error) {
	rows, err := q.db.Query(ctx, listMobileInvitationPhotosByInvitation, invitationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []V3MobileInvitationPhoto{}
	for rows.Next() {
		var i V3MobileInvitationPhoto
		if err := rows.Scan(
			&i.ID,
			&i.InvitationID,
			&i.SubKind,
			&i.StoragePath,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
