// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAuditLog struct {
	ID            pgtype.UUID        `json:"id"`
	AdminUserID   pgtype.UUID        `json:"admin_user_id"`
	AdminEmail    string             `json:"admin_email"`
	Action        string             `json:"action"`
	ResourceType  string             `json:"resource_type"`
	ResourceID    string             `json:"resource_id"`
	Changes       []byte             `json:"changes"`
	RequestMethod pgtype.Text        `json:"request_method"`
	RequestPath   pgtype.Text        `json:"request_path"`
	IpAddress     pgtype.Text        `json:"ip_address"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ConsentRecord struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	TermsDocumentID int32              `json:"terms_document_id"`
	Agreed          bool               `json:"agreed"`
	AgreedAt        pgtype.Timestamptz `json:"agreed_at"`
	IpAddress       *netip.Addr        `json:"ip_address"`
	UserAgent       pgtype.Text        `json:"user_agent"`
	ConsentMethod   string             `json:"consent_method"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	UserID       pgtype.UUID        `json:"user_id"`
	DisplayName  string             `json:"display_name"`
	TermsVersion int32              `json:"terms_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type TermsDocument struct {
	ID            int32              `json:"id"`
	TermsType     string             `json:"terms_type"`
	Version       int32              `json:"version"`
	Title         string             `json:"title"`
	ContentUrl    string             `json:"content_url"`
	IsRequired    bool               `json:"is_required"`
	EffectiveFrom pgtype.Timestamptz `json:"effective_from"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type V3CashGift struct {
	ID               pgtype.UUID        `json:"id"`
	WeddingID        pgtype.UUID        `json:"wedding_id"`
	GuestName        string             `json:"guest_name"`
	GuestID          pgtype.UUID        `json:"guest_id"`
	RecipientSlot    string             `json:"recipient_slot"`
	RelationCategory string             `json:"relation_category"`
	RelationDetail   pgtype.Text        `json:"relation_detail"`
	Amount           int32              `json:"amount"`
	PayMethod        string             `json:"pay_method"`
	GuestbookEntryID pgtype.UUID        `json:"guestbook_entry_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type V3FeedComment struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TargetType string             `json:"target_type"`
	TargetID   pgtype.UUID        `json:"target_id"`
	Message    string             `json:"message"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

// 피드 아이템 좋아요 (중복 방지). target_type: guestbook_entry | announcement
type V3FeedHeart struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	// guestbook_entry | announcement
	TargetType string `json:"target_type"`
	// 대상 테이블의 PK (UUID)
	TargetID  pgtype.UUID        `json:"target_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type V3GuestbookEntry struct {
	ID        pgtype.UUID        `json:"id"`
	LoungeID  pgtype.UUID        `json:"lounge_id"`
	GuestName string             `json:"guest_name"`
	GuestID   pgtype.UUID        `json:"guest_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 작성자 소속: groom | bride
	RecipientSlot string `json:"recipient_slot"`
	// 관계 카테고리: 친구·지인, 가족·친척, 동문·동창, 직장동료, 스승·제자 등
	RelationCategory string `json:"relation_category"`
	// 세부 관계 설명: 사촌언니, 하이닉스, 경영 13 등
	RelationDetail pgtype.Text `json:"relation_detail"`
}

type V3GuestbookMessage struct {
	ID               pgtype.UUID        `json:"id"`
	GuestbookEntryID pgtype.UUID        `json:"guestbook_entry_id"`
	Message          string             `json:"message"`
	LoungeID         pgtype.UUID        `json:"lounge_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type V3GuestbookMessageView struct {
	ID                 pgtype.UUID        `json:"id"`
	GuestbookMessageID pgtype.UUID        `json:"guestbook_message_id"`
	ViewerID           pgtype.UUID        `json:"viewer_id"`
	ViewedAt           pgtype.Timestamptz `json:"viewed_at"`
}

type V3HostAnnouncement struct {
	ID        pgtype.UUID        `json:"id"`
	LoungeID  pgtype.UUID        `json:"lounge_id"`
	HostID    pgtype.UUID        `json:"host_id"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 피드 상단 고정 여부 (라운지당 최대 1개)
	IsPinned  bool               `json:"is_pinned"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type V3HostInvite struct {
	ID            pgtype.UUID        `json:"id"`
	WeddingID     pgtype.UUID        `json:"wedding_id"`
	Slot          string             `json:"slot"`
	Token         string             `json:"token"`
	Status        string             `json:"status"`
	InvitedUserID pgtype.UUID        `json:"invited_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	AcceptedAt    pgtype.Timestamptz `json:"accepted_at"`
}

type V3InteriorItem struct {
	ID               pgtype.UUID        `json:"id"`
	MoiGatherPlaceID pgtype.UUID        `json:"moi_gather_place_id"`
	Name             string             `json:"name"`
	Type             string             `json:"type"`
	Size             pgtype.Text        `json:"size"`
	Image            pgtype.Text        `json:"image"`
	Status           string             `json:"status"`
	Position         []byte             `json:"position"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type V3Ium struct {
	ID            pgtype.UUID        `json:"id"`
	RelationType  string             `json:"relation_type"`
	RelationLabel string             `json:"relation_label"`
	FromUserID    pgtype.UUID        `json:"from_user_id"`
	ToUserID      pgtype.UUID        `json:"to_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type V3LoungeCheckIn struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	LoungeID         pgtype.UUID        `json:"lounge_id"`
	VisitorName      string             `json:"visitor_name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	RecipientSlot    pgtype.Text        `json:"recipient_slot"`
	RelationCategory pgtype.Text        `json:"relation_category"`
	RelationDetail   pgtype.Text        `json:"relation_detail"`
}

type V3Memory struct {
	ID           pgtype.UUID        `json:"id"`
	LoungeID     pgtype.UUID        `json:"lounge_id"`
	AuthorUserID pgtype.UUID        `json:"author_user_id"`
	Text         string             `json:"text"`
	PhotoUrl     pgtype.Text        `json:"photo_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type V3MemoryBookPhoto struct {
	ID           pgtype.UUID        `json:"id"`
	WeddingID    pgtype.UUID        `json:"wedding_id"`
	PhotoID      pgtype.UUID        `json:"photo_id"`
	DisplayOrder int32              `json:"display_order"`
	SelectedBy   pgtype.UUID        `json:"selected_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type V3MobileInvitation struct {
	ID               pgtype.UUID        `json:"id"`
	WeddingID        pgtype.UUID        `json:"wedding_id"`
	DesignTemplateID string             `json:"design_template_id"`
	CustomMessage    pgtype.Text        `json:"custom_message"`
	VisitedCount     int32              `json:"visited_count"`
	HeartCount       int32              `json:"heart_count"`
	GalleryPhotos    []byte             `json:"gallery_photos"`
	CoverImage       pgtype.Text        `json:"cover_image"`
	CoverTextConfig  []byte             `json:"cover_text_config"`
	DesignConfig     []byte             `json:"design_config"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Slug             string             `json:"slug"`
}

type V3MobileInvitationPhoto struct {
	ID           pgtype.UUID        `json:"id"`
	InvitationID pgtype.UUID        `json:"invitation_id"`
	SubKind      string             `json:"sub_kind"`
	StoragePath  string             `json:"storage_path"`
	FileName     pgtype.Text        `json:"file_name"`
	FileSize     pgtype.Int4        `json:"file_size"`
	MimeType     pgtype.Text        `json:"mime_type"`
	SortOrder    int32              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type V3Moi struct {
	ID            pgtype.UUID `json:"id"`
	UserID        pgtype.UUID `json:"user_id"`
	EquippedItems []byte      `json:"equipped_items"`
}

type V3MoiGatherPlace struct {
	ID       pgtype.UUID `json:"id"`
	LoungeID pgtype.UUID `json:"lounge_id"`
	Type     string      `json:"type"`
}

type V3MoiItem struct {
	ID        pgtype.UUID        `json:"id"`
	MoiID     pgtype.UUID        `json:"moi_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Slot      string             `json:"slot"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type V3Rsvp struct {
	ID             pgtype.UUID        `json:"id"`
	WeddingID      pgtype.UUID        `json:"wedding_id"`
	RecipientSlot  string             `json:"recipient_slot"`
	GuestName      string             `json:"guest_name"`
	Attendance     string             `json:"attendance"`
	CompanionCount int32              `json:"companion_count"`
	Meal           string             `json:"meal"`
	PhoneLast4     pgtype.Text        `json:"phone_last4"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type V3SharedPhoto struct {
	ID          pgtype.UUID        `json:"id"`
	LoungeID    pgtype.UUID        `json:"lounge_id"`
	GuestUserID pgtype.UUID        `json:"guest_user_id"`
	StoragePath string             `json:"storage_path"`
	FileName    pgtype.Text        `json:"file_name"`
	FileSize    pgtype.Int4        `json:"file_size"`
	MimeType    pgtype.Text        `json:"mime_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type V3User struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	Phone           pgtype.Text        `json:"phone"`
	ProfileImageUrl pgtype.Text        `json:"profile_image_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type V3Wedding struct {
	ID                  pgtype.UUID        `json:"id"`
	Status              string             `json:"status"`
	HostGroomID         pgtype.UUID        `json:"host_groom_id"`
	HostBrideID         pgtype.UUID        `json:"host_bride_id"`
	HostGroomFatherID   pgtype.UUID        `json:"host_groom_father_id"`
	HostGroomMotherID   pgtype.UUID        `json:"host_groom_mother_id"`
	HostBrideFatherID   pgtype.UUID        `json:"host_bride_father_id"`
	HostBrideMotherID   pgtype.UUID        `json:"host_bride_mother_id"`
	GroomName           string             `json:"groom_name"`
	BrideName           string             `json:"bride_name"`
	GroomFatherName     pgtype.Text        `json:"groom_father_name"`
	GroomMotherName     pgtype.Text        `json:"groom_mother_name"`
	BrideFatherName     pgtype.Text        `json:"bride_father_name"`
	BrideMotherName     pgtype.Text        `json:"bride_mother_name"`
	GroomFatherDeceased bool               `json:"groom_father_deceased"`
	GroomMotherDeceased bool               `json:"groom_mother_deceased"`
	BrideFatherDeceased bool               `json:"bride_father_deceased"`
	BrideMotherDeceased bool               `json:"bride_mother_deceased"`
	Date                pgtype.Date        `json:"date"`
	Time                string             `json:"time"`
	VenueName           string             `json:"venue_name"`
	VenueAddress        string             `json:"venue_address"`
	VenueHall           pgtype.Text        `json:"venue_hall"`
	GroomAccount        []byte             `json:"groom_account"`
	BrideAccount        []byte             `json:"bride_account"`
	GroomFatherAccount  []byte             `json:"groom_father_account"`
	GroomMotherAccount  []byte             `json:"groom_mother_account"`
	BrideFatherAccount  []byte             `json:"bride_father_account"`
	BrideMotherAccount  []byte             `json:"bride_mother_account"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type V3WeddingLounge struct {
	ID        pgtype.UUID `json:"id"`
	WeddingID pgtype.UUID `json:"wedding_id"`
	Name      string      `json:"name"`
}
