// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rsvps.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertRsvp = `-- name: InsertRsvp :one

INSERT INTO v3_rsvps (wedding_id, recipient_slot, guest_name, attendance, companion_count, meal, phone_last4)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, wedding_id, recipient_slot, guest_name, attendance, companion_count, meal, phone_last4, created_at
`

type InsertRsvpParams struct {
	WeddingID      pgtype.UUID `json:"wedding_id"`
	RecipientSlot  string      `json:"recipient_slot"`
	GuestName      string      `json:"guest_name"`
	Attendance     string      `json:"attendance"`
	CompanionCount int32       `json:"companion_count"`
	Meal           string      `json:"meal"`
	PhoneLast4     pgtype.Text `json:"phone_last4"`
}

// RSVP — 모바일 청첩장 참석 의사 (QA 2026-05-29 G1).
// 게스트가 청첩장에서 제출(InsertRsvp), 호스트가 리포트에서 측별로 조회(ListRsvpsByWeddingSlots).
// 측별 공유 권한(신랑측 3명 공유 / 신랑·신부측 비공유)은 핸들러가 호스트 측 슬롯을 slots로 넘겨 강제.
func (q *Queries) InsertRsvp(ctx context.Context, arg InsertRsvpParams) (V3Rsvp, error) {
	row := q.db.QueryRow(ctx, insertRsvp,
		arg.WeddingID,
		arg.RecipientSlot,
		arg.GuestName,
		arg.Attendance,
		arg.CompanionCount,
		arg.Meal,
		arg.PhoneLast4,
	)
	var i V3Rsvp
	err := row.Scan(
		&i.ID,
		&i.WeddingID,
		&i.RecipientSlot,
		&i.GuestName,
		&i.Attendance,
		&i.CompanionCount,
		&i.Meal,
		&i.PhoneLast4,
		&i.CreatedAt,
	)
	return i, err
}

const listRsvpsByWeddingSlots = `-- name: ListRsvpsByWeddingSlots :many
SELECT id, wedding_id, recipient_slot, guest_name, attendance, companion_count, meal, phone_last4, created_at
FROM v3_rsvps
WHERE wedding_id = $1
  AND recipient_slot = ANY($2::text[])
ORDER BY created_at DESC
`

type ListRsvpsByWeddingSlotsParams struct {
	WeddingID pgtype.UUID `json:"wedding_id"`
	Slots     []string    `json:"slots"`
}

func (q *Queries) ListRsvpsByWeddingSlots(ctx context.Context, arg ListRsvpsByWeddingSlotsParams) ([]V3Rsvp, error) {
	rows, err := q.db.Query(ctx, listRsvpsByWeddingSlots, arg.WeddingID, arg.Slots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []V3Rsvp{}
	for rows.Next() {
		var i V3Rsvp
		if err := rows.Scan(
			&i.ID,
			&i.WeddingID,
			&i.RecipientSlot,
			&i.GuestName,
			&i.Attendance,
			&i.CompanionCount,
			&i.Meal,
			&i.PhoneLast4,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
