// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shared_photos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSharedPhotosByLoungeAndGuest = `-- name: CountSharedPhotosByLoungeAndGuest :one
SELECT count(*)::int FROM v3_shared_photos
WHERE lounge_id = $1 AND guest_user_id = $2
`

type CountSharedPhotosByLoungeAndGuestParams struct {
	LoungeID    pgtype.UUID `json:"lounge_id"`
	GuestUserID pgtype.UUID `json:"guest_user_id"`
}

// 100장 한도 검증용. service는 advisory_xact_lock으로 race-safe 보장.
func (q *Queries) CountSharedPhotosByLoungeAndGuest(ctx context.Context, arg CountSharedPhotosByLoungeAndGuestParams) (int32, error) {
	row := q.db.QueryRow(ctx, countSharedPhotosByLoungeAndGuest, arg.LoungeID, arg.GuestUserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createSharedPhoto = `-- name: CreateSharedPhoto :one
INSERT INTO v3_shared_photos (
    lounge_id, guest_user_id, storage_path, file_name, file_size, mime_type
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, lounge_id, guest_user_id, storage_path, file_name, file_size, mime_type, created_at
`

type CreateSharedPhotoParams struct {
	LoungeID    pgtype.UUID `json:"lounge_id"`
	GuestUserID pgtype.UUID `json:"guest_user_id"`
	StoragePath string      `json:"storage_path"`
	FileName    pgtype.Text `json:"file_name"`
	FileSize    pgtype.Int4 `json:"file_size"`
	MimeType    pgtype.Text `json:"mime_type"`
}

func (q *Queries) CreateSharedPhoto(ctx context.Context, arg CreateSharedPhotoParams) (V3SharedPhoto, error) {
	row := q.db.QueryRow(ctx, createSharedPhoto,
		arg.LoungeID,
		arg.GuestUserID,
		arg.StoragePath,
		arg.FileName,
		arg.FileSize,
		arg.MimeType,
	)
	var i V3SharedPhoto
	err := row.Scan(
		&i.ID,
		&i.LoungeID,
		&i.GuestUserID,
		&i.StoragePath,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const listSharedPhotosByLounge = `-- name: ListSharedPhotosByLounge :many

SELECT id, lounge_id, guest_user_id, storage_path, file_name, file_size, mime_type, created_at
FROM v3_shared_photos
WHERE lounge_id = $1
ORDER BY guest_user_id ASC, created_at DESC
`

// 시나리오 §8-2, §10: 하객 현장사진 공유 (100장/하객 한도)
// host 호출용: 라운지 전체. 하객별 그룹은 클라이언트가 guest_user_id로 group.
func (q *Queries) ListSharedPhotosByLounge(ctx context.Context, loungeID pgtype.UUID) ([]V3SharedPhoto, error) {
	rows, err := q.db.Query(ctx, listSharedPhotosByLounge, loungeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []V3SharedPhoto{}
	for rows.Next() {
		var i V3SharedPhoto
		if err := rows.Scan(
			&i.ID,
			&i.LoungeID,
			&i.GuestUserID,
			&i.StoragePath,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedPhotosByLoungeAndGuest = `-- name: ListSharedPhotosByLoungeAndGuest :many
SELECT id, lounge_id, guest_user_id, storage_path, file_name, file_size, mime_type, created_at
FROM v3_shared_photos
WHERE lounge_id = $1 AND guest_user_id = $2
ORDER BY created_at DESC
`

type ListSharedPhotosByLoungeAndGuestParams struct {
	LoungeID    pgtype.UUID `json:"lounge_id"`
	GuestUserID pgtype.UUID `json:"guest_user_id"`
}

// 입장자 본인 또는 host의 특정 그룹 조회.
func (q *Queries) ListSharedPhotosByLoungeAndGuest(ctx context.Context, arg ListSharedPhotosByLoungeAndGuestParams) ([]V3SharedPhoto, error) {
	rows, err := q.db.Query(ctx, listSharedPhotosByLoungeAndGuest, arg.LoungeID, arg.GuestUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []V3SharedPhoto{}
	for rows.Next() {
		var i V3SharedPhoto
		if err := rows.Scan(
			&i.ID,
			&i.LoungeID,
			&i.GuestUserID,
			&i.StoragePath,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
