// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureUser = `-- name: EnsureUser :exec
INSERT INTO v3_users (id, name, email)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type EnsureUserParams struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Email string      `json:"email"`
}

// JIT 프로비저닝: 인증된 유저의 도메인 행을 멱등 보장.
// ON CONFLICT DO NOTHING(타깃 없음) = id PK / email UNIQUE 등 모든 유니크 위반 무시 → 동시 첫 요청 안전.
func (q *Queries) EnsureUser(ctx context.Context, arg EnsureUserParams) error {
	_, err := q.db.Exec(ctx, ensureUser, arg.ID, arg.Name, arg.Email)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, phone, profile_image_url, created_at FROM v3_users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (V3User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i V3User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.ProfileImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE v3_users
SET name = COALESCE($2, name),
    phone = COALESCE($3, phone),
    profile_image_url = COALESCE($4, profile_image_url)
WHERE id = $1
RETURNING id, name, email, phone, profile_image_url, created_at
`

type UpdateUserParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            pgtype.Text `json:"name"`
	Phone           pgtype.Text `json:"phone"`
	ProfileImageUrl pgtype.Text `json:"profile_image_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (V3User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.ProfileImageUrl,
	)
	var i V3User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.ProfileImageUrl,
		&i.CreatedAt,
	)
	return i, err
}
