// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weddings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMyWeddings = `-- name: GetMyWeddings :many
SELECT w.id, w.status, w.groom_name, w.bride_name,
       w.groom_father_name, w.groom_mother_name, w.bride_father_name, w.bride_mother_name,
       w.date, w."time",
       w.venue_name, w.venue_hall,
       w.host_groom_id, w.host_bride_id,
       w.host_groom_father_id, w.host_groom_mother_id,
       w.host_bride_father_id, w.host_bride_mother_id,
       l.id AS lounge_id
FROM v3_weddings w
LEFT JOIN v3_wedding_lounges l ON l.wedding_id = w.id
WHERE (w.host_groom_id = $1
       OR w.host_bride_id = $1
       OR w.host_groom_father_id = $1
       OR w.host_groom_mother_id = $1
       OR w.host_bride_father_id = $1
       OR w.host_bride_mother_id = $1)
  AND w.status != 'deleted'
ORDER BY w.created_at DESC
`

type GetMyWeddingsRow struct {
	ID                pgtype.UUID `json:"id"`
	Status            string      `json:"status"`
	GroomName         string      `json:"groom_name"`
	BrideName         string      `json:"bride_name"`
	GroomFatherName   pgtype.Text `json:"groom_father_name"`
	GroomMotherName   pgtype.Text `json:"groom_mother_name"`
	BrideFatherName   pgtype.Text `json:"bride_father_name"`
	BrideMotherName   pgtype.Text `json:"bride_mother_name"`
	Date              pgtype.Date `json:"date"`
	Time              string      `json:"time"`
	VenueName         string      `json:"venue_name"`
	VenueHall         pgtype.Text `json:"venue_hall"`
	HostGroomID       pgtype.UUID `json:"host_groom_id"`
	HostBrideID       pgtype.UUID `json:"host_bride_id"`
	HostGroomFatherID pgtype.UUID `json:"host_groom_father_id"`
	HostGroomMotherID pgtype.UUID `json:"host_groom_mother_id"`
	HostBrideFatherID pgtype.UUID `json:"host_bride_father_id"`
	HostBrideMotherID pgtype.UUID `json:"host_bride_mother_id"`
	LoungeID          pgtype.UUID `json:"lounge_id"`
}

func (q *Queries) GetMyWeddings(ctx context.Context, hostGroomID pgtype.UUID) ([]GetMyWeddingsRow, error) {
	rows, err := q.db.Query(ctx, getMyWeddings, hostGroomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMyWeddingsRow{}
	for rows.Next() {
		var i GetMyWeddingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.GroomName,
			&i.BrideName,
			&i.GroomFatherName,
			&i.GroomMotherName,
			&i.BrideFatherName,
			&i.BrideMotherName,
			&i.Date,
			&i.Time,
			&i.VenueName,
			&i.VenueHall,
			&i.HostGroomID,
			&i.HostBrideID,
			&i.HostGroomFatherID,
			&i.HostGroomMotherID,
			&i.HostBrideFatherID,
			&i.HostBrideMotherID,
			&i.LoungeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParticipatedWeddings = `-- name: GetParticipatedWeddings :many
SELECT DISTINCT w.id, w.groom_name, w.bride_name, w.date, w."time",
       w.venue_name, w.venue_hall,
       (SELECT cover_image FROM v3_mobile_invitations WHERE wedding_id = w.id LIMIT 1) AS cover_image,
       l.id AS lounge_id
FROM v3_weddings w
JOIN v3_wedding_lounges l ON l.wedding_id = w.id
WHERE w.id IN (
    -- LoungeCheckIn을 통한 참여
    SELECT wl.wedding_id
    FROM v3_lounge_check_ins le
    JOIN v3_wedding_lounges wl ON wl.id = le.lounge_id
    WHERE le.user_id = $1
    UNION
    -- GuestbookEntry를 통한 참여
    SELECT wl2.wedding_id
    FROM v3_guestbook_entries ge
    JOIN v3_wedding_lounges wl2 ON wl2.id = ge.lounge_id
    WHERE ge.guest_id = $1
)
ORDER BY w.date DESC
`

type GetParticipatedWeddingsRow struct {
	ID         pgtype.UUID `json:"id"`
	GroomName  string      `json:"groom_name"`
	BrideName  string      `json:"bride_name"`
	Date       pgtype.Date `json:"date"`
	Time       string      `json:"time"`
	VenueName  string      `json:"venue_name"`
	VenueHall  pgtype.Text `json:"venue_hall"`
	CoverImage pgtype.Text `json:"cover_image"`
	LoungeID   pgtype.UUID `json:"lounge_id"`
}

func (q *Queries) GetParticipatedWeddings(ctx context.Context, userID pgtype.UUID) ([]GetParticipatedWeddingsRow, error) {
	rows, err := q.db.Query(ctx, getParticipatedWeddings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetParticipatedWeddingsRow{}
	for rows.Next() {
		var i GetParticipatedWeddingsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroomName,
			&i.BrideName,
			&i.Date,
			&i.Time,
			&i.VenueName,
			&i.VenueHall,
			&i.CoverImage,
			&i.LoungeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWedding = `-- name: GetWedding :one
SELECT id, status, host_groom_id, host_bride_id, host_groom_father_id, host_groom_mother_id, host_bride_father_id, host_bride_mother_id, groom_name, bride_name, groom_father_name, groom_mother_name, bride_father_name, bride_mother_name, groom_father_deceased, groom_mother_deceased, bride_father_deceased, bride_mother_deceased, date, time, venue_name, venue_address, venue_hall, groom_account, bride_account, groom_father_account, groom_mother_account, bride_father_account, bride_mother_account, created_at FROM v3_weddings WHERE id = $1
`

func (q *Queries) GetWedding(ctx context.Context, id pgtype.UUID) (V3Wedding, error) {
	row := q.db.QueryRow(ctx, getWedding, id)
	var i V3Wedding
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.HostGroomID,
		&i.HostBrideID,
		&i.HostGroomFatherID,
		&i.HostGroomMotherID,
		&i.HostBrideFatherID,
		&i.HostBrideMotherID,
		&i.GroomName,
		&i.BrideName,
		&i.GroomFatherName,
		&i.GroomMotherName,
		&i.BrideFatherName,
		&i.BrideMotherName,
		&i.GroomFatherDeceased,
		&i.GroomMotherDeceased,
		&i.BrideFatherDeceased,
		&i.BrideMotherDeceased,
		&i.Date,
		&i.Time,
		&i.VenueName,
		&i.VenueAddress,
		&i.VenueHall,
		&i.GroomAccount,
		&i.BrideAccount,
		&i.GroomFatherAccount,
		&i.GroomMotherAccount,
		&i.BrideFatherAccount,
		&i.BrideMotherAccount,
		&i.CreatedAt,
	)
	return i, err
}

const getWeddingFull = `-- name: GetWeddingFull :one
SELECT w.id, w.status, w.host_groom_id, w.host_bride_id, w.host_groom_father_id, w.host_groom_mother_id, w.host_bride_father_id, w.host_bride_mother_id, w.groom_name, w.bride_name, w.groom_father_name, w.groom_mother_name, w.bride_father_name, w.bride_mother_name, w.groom_father_deceased, w.groom_mother_deceased, w.bride_father_deceased, w.bride_mother_deceased, w.date, w.time, w.venue_name, w.venue_address, w.venue_hall, w.groom_account, w.bride_account, w.groom_father_account, w.groom_mother_account, w.bride_father_account, w.bride_mother_account, w.created_at,
       l.id AS lounge_id, l.name AS lounge_name,
       gp.id AS gather_place_id,
       COALESCE((SELECT COUNT(*) FROM v3_lounge_check_ins ci
                 WHERE ci.lounge_id = l.id
                   AND ci.recipient_slot IN ('groom', 'groom_father', 'groom_mother')), 0)::bigint AS groom_side_guest_count,
       COALESCE((SELECT COUNT(*) FROM v3_lounge_check_ins ci
                 WHERE ci.lounge_id = l.id
                   AND ci.recipient_slot IN ('bride', 'bride_father', 'bride_mother')), 0)::bigint AS bride_side_guest_count
FROM v3_weddings w
LEFT JOIN v3_wedding_lounges l ON l.wedding_id = w.id
LEFT JOIN v3_moi_gather_places gp ON gp.lounge_id = l.id
WHERE w.id = $1
`

type GetWeddingFullRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Status              string             `json:"status"`
	HostGroomID         pgtype.UUID        `json:"host_groom_id"`
	HostBrideID         pgtype.UUID        `json:"host_bride_id"`
	HostGroomFatherID   pgtype.UUID        `json:"host_groom_father_id"`
	HostGroomMotherID   pgtype.UUID        `json:"host_groom_mother_id"`
	HostBrideFatherID   pgtype.UUID        `json:"host_bride_father_id"`
	HostBrideMotherID   pgtype.UUID        `json:"host_bride_mother_id"`
	GroomName           string             `json:"groom_name"`
	BrideName           string             `json:"bride_name"`
	GroomFatherName     pgtype.Text        `json:"groom_father_name"`
	GroomMotherName     pgtype.Text        `json:"groom_mother_name"`
	BrideFatherName     pgtype.Text        `json:"bride_father_name"`
	BrideMotherName     pgtype.Text        `json:"bride_mother_name"`
	GroomFatherDeceased bool               `json:"groom_father_deceased"`
	GroomMotherDeceased bool               `json:"groom_mother_deceased"`
	BrideFatherDeceased bool               `json:"bride_father_deceased"`
	BrideMotherDeceased bool               `json:"bride_mother_deceased"`
	Date                pgtype.Date        `json:"date"`
	Time                string             `json:"time"`
	VenueName           string             `json:"venue_name"`
	VenueAddress        string             `json:"venue_address"`
	VenueHall           pgtype.Text        `json:"venue_hall"`
	GroomAccount        []byte             `json:"groom_account"`
	BrideAccount        []byte             `json:"bride_account"`
	GroomFatherAccount  []byte             `json:"groom_father_account"`
	GroomMotherAccount  []byte             `json:"groom_mother_account"`
	BrideFatherAccount  []byte             `json:"bride_father_account"`
	BrideMotherAccount  []byte             `json:"bride_mother_account"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	LoungeID            pgtype.UUID        `json:"lounge_id"`
	LoungeName          pgtype.Text        `json:"lounge_name"`
	GatherPlaceID       pgtype.UUID        `json:"gather_place_id"`
	GroomSideGuestCount int64              `json:"groom_side_guest_count"`
	BrideSideGuestCount int64              `json:"bride_side_guest_count"`
}

func (q *Queries) GetWeddingFull(ctx context.Context, id pgtype.UUID) (GetWeddingFullRow, error) {
	row := q.db.QueryRow(ctx, getWeddingFull, id)
	var i GetWeddingFullRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.HostGroomID,
		&i.HostBrideID,
		&i.HostGroomFatherID,
		&i.HostGroomMotherID,
		&i.HostBrideFatherID,
		&i.HostBrideMotherID,
		&i.GroomName,
		&i.BrideName,
		&i.GroomFatherName,
		&i.GroomMotherName,
		&i.BrideFatherName,
		&i.BrideMotherName,
		&i.GroomFatherDeceased,
		&i.GroomMotherDeceased,
		&i.BrideFatherDeceased,
		&i.BrideMotherDeceased,
		&i.Date,
		&i.Time,
		&i.VenueName,
		&i.VenueAddress,
		&i.VenueHall,
		&i.GroomAccount,
		&i.BrideAccount,
		&i.GroomFatherAccount,
		&i.GroomMotherAccount,
		&i.BrideFatherAccount,
		&i.BrideMotherAccount,
		&i.CreatedAt,
		&i.LoungeID,
		&i.LoungeName,
		&i.GatherPlaceID,
		&i.GroomSideGuestCount,
		&i.BrideSideGuestCount,
	)
	return i, err
}

const insertWedding = `-- name: InsertWedding :one
INSERT INTO v3_weddings (
    groom_name, bride_name,
    groom_father_name, groom_mother_name,
    bride_father_name, bride_mother_name,
    groom_father_deceased, groom_mother_deceased,
    bride_father_deceased, bride_mother_deceased,
    date, "time",
    venue_name, venue_address, venue_hall,
    groom_account, bride_account,
    groom_father_account, groom_mother_account,
    bride_father_account, bride_mother_account,
    host_groom_id, host_bride_id,
    host_groom_father_id, host_groom_mother_id,
    host_bride_father_id, host_bride_mother_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15,
    convert_from($16, 'UTF8')::jsonb, convert_from($17, 'UTF8')::jsonb,
    convert_from($18, 'UTF8')::jsonb, convert_from($19, 'UTF8')::jsonb,
    convert_from($20, 'UTF8')::jsonb, convert_from($21, 'UTF8')::jsonb,
    $22, $23, $24, $25, $26, $27
) RETURNING id, status, host_groom_id, host_bride_id, host_groom_father_id, host_groom_mother_id, host_bride_father_id, host_bride_mother_id, groom_name, bride_name, groom_father_name, groom_mother_name, bride_father_name, bride_mother_name, groom_father_deceased, groom_mother_deceased, bride_father_deceased, bride_mother_deceased, date, time, venue_name, venue_address, venue_hall, groom_account, bride_account, groom_father_account, groom_mother_account, bride_father_account, bride_mother_account, created_at
`

type InsertWeddingParams struct {
	GroomName           string      `json:"groom_name"`
	BrideName           string      `json:"bride_name"`
	GroomFatherName     pgtype.Text `json:"groom_father_name"`
	GroomMotherName     pgtype.Text `json:"groom_mother_name"`
	BrideFatherName     pgtype.Text `json:"bride_father_name"`
	BrideMotherName     pgtype.Text `json:"bride_mother_name"`
	GroomFatherDeceased bool        `json:"groom_father_deceased"`
	GroomMotherDeceased bool        `json:"groom_mother_deceased"`
	BrideFatherDeceased bool        `json:"bride_father_deceased"`
	BrideMotherDeceased bool        `json:"bride_mother_deceased"`
	Date                pgtype.Date `json:"date"`
	Time                string      `json:"time"`
	VenueName           string      `json:"venue_name"`
	VenueAddress        string      `json:"venue_address"`
	VenueHall           pgtype.Text `json:"venue_hall"`
	ConvertFrom         []byte      `json:"convert_from"`
	ConvertFrom_2       []byte      `json:"convert_from_2"`
	ConvertFrom_3       []byte      `json:"convert_from_3"`
	ConvertFrom_4       []byte      `json:"convert_from_4"`
	ConvertFrom_5       []byte      `json:"convert_from_5"`
	ConvertFrom_6       []byte      `json:"convert_from_6"`
	HostGroomID         pgtype.UUID `json:"host_groom_id"`
	HostBrideID         pgtype.UUID `json:"host_bride_id"`
	HostGroomFatherID   pgtype.UUID `json:"host_groom_father_id"`
	HostGroomMotherID   pgtype.UUID `json:"host_groom_mother_id"`
	HostBrideFatherID   pgtype.UUID `json:"host_bride_father_id"`
	HostBrideMotherID   pgtype.UUID `json:"host_bride_mother_id"`
}

func (q *Queries) InsertWedding(ctx context.Context, arg InsertWeddingParams) (V3Wedding, error) {
	row := q.db.QueryRow(ctx, insertWedding,
		arg.GroomName,
		arg.BrideName,
		arg.GroomFatherName,
		arg.GroomMotherName,
		arg.BrideFatherName,
		arg.BrideMotherName,
		arg.GroomFatherDeceased,
		arg.GroomMotherDeceased,
		arg.BrideFatherDeceased,
		arg.BrideMotherDeceased,
		arg.Date,
		arg.Time,
		arg.VenueName,
		arg.VenueAddress,
		arg.VenueHall,
		arg.ConvertFrom,
		arg.ConvertFrom_2,
		arg.ConvertFrom_3,
		arg.ConvertFrom_4,
		arg.ConvertFrom_5,
		arg.ConvertFrom_6,
		arg.HostGroomID,
		arg.HostBrideID,
		arg.HostGroomFatherID,
		arg.HostGroomMotherID,
		arg.HostBrideFatherID,
		arg.HostBrideMotherID,
	)
	var i V3Wedding
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.HostGroomID,
		&i.HostBrideID,
		&i.HostGroomFatherID,
		&i.HostGroomMotherID,
		&i.HostBrideFatherID,
		&i.HostBrideMotherID,
		&i.GroomName,
		&i.BrideName,
		&i.GroomFatherName,
		&i.GroomMotherName,
		&i.BrideFatherName,
		&i.BrideMotherName,
		&i.GroomFatherDeceased,
		&i.GroomMotherDeceased,
		&i.BrideFatherDeceased,
		&i.BrideMotherDeceased,
		&i.Date,
		&i.Time,
		&i.VenueName,
		&i.VenueAddress,
		&i.VenueHall,
		&i.GroomAccount,
		&i.BrideAccount,
		&i.GroomFatherAccount,
		&i.GroomMotherAccount,
		&i.BrideFatherAccount,
		&i.BrideMotherAccount,
		&i.CreatedAt,
	)
	return i, err
}

const updateWeddingInfo = `-- name: UpdateWeddingInfo :one
UPDATE v3_weddings
SET groom_name = COALESCE($2, groom_name),
    bride_name = COALESCE($3, bride_name),
    groom_father_name = COALESCE($4, groom_father_name),
    groom_mother_name = COALESCE($5, groom_mother_name),
    bride_father_name = COALESCE($6, bride_father_name),
    bride_mother_name = COALESCE($7, bride_mother_name),
    groom_father_deceased = COALESCE($8, groom_father_deceased),
    groom_mother_deceased = COALESCE($9, groom_mother_deceased),
    bride_father_deceased = COALESCE($10, bride_father_deceased),
    bride_mother_deceased = COALESCE($11, bride_mother_deceased),
    date = COALESCE($12, date),
    "time" = COALESCE($13, "time"),
    venue_name = COALESCE($14, venue_name),
    venue_address = COALESCE($15, venue_address),
    venue_hall = COALESCE($16, venue_hall),
    groom_account = COALESCE(convert_from($17, 'UTF8')::jsonb, groom_account),
    bride_account = COALESCE(convert_from($18, 'UTF8')::jsonb, bride_account),
    groom_father_account = COALESCE(convert_from($19, 'UTF8')::jsonb, groom_father_account),
    groom_mother_account = COALESCE(convert_from($20, 'UTF8')::jsonb, groom_mother_account),
    bride_father_account = COALESCE(convert_from($21, 'UTF8')::jsonb, bride_father_account),
    bride_mother_account = COALESCE(convert_from($22, 'UTF8')::jsonb, bride_mother_account),
    host_groom_id = COALESCE($23, host_groom_id),
    host_bride_id = COALESCE($24, host_bride_id),
    host_groom_father_id = COALESCE($25, host_groom_father_id),
    host_groom_mother_id = COALESCE($26, host_groom_mother_id),
    host_bride_father_id = COALESCE($27, host_bride_father_id),
    host_bride_mother_id = COALESCE($28, host_bride_mother_id)
WHERE id = $1
RETURNING id, status, host_groom_id, host_bride_id, host_groom_father_id, host_groom_mother_id, host_bride_father_id, host_bride_mother_id, groom_name, bride_name, groom_father_name, groom_mother_name, bride_father_name, bride_mother_name, groom_father_deceased, groom_mother_deceased, bride_father_deceased, bride_mother_deceased, date, time, venue_name, venue_address, venue_hall, groom_account, bride_account, groom_father_account, groom_mother_account, bride_father_account, bride_mother_account, created_at
`

type UpdateWeddingInfoParams struct {
	ID                  pgtype.UUID `json:"id"`
	GroomName           pgtype.Text `json:"groom_name"`
	BrideName           pgtype.Text `json:"bride_name"`
	GroomFatherName     pgtype.Text `json:"groom_father_name"`
	GroomMotherName     pgtype.Text `json:"groom_mother_name"`
	BrideFatherName     pgtype.Text `json:"bride_father_name"`
	BrideMotherName     pgtype.Text `json:"bride_mother_name"`
	GroomFatherDeceased pgtype.Bool `json:"groom_father_deceased"`
	GroomMotherDeceased pgtype.Bool `json:"groom_mother_deceased"`
	BrideFatherDeceased pgtype.Bool `json:"bride_father_deceased"`
	BrideMotherDeceased pgtype.Bool `json:"bride_mother_deceased"`
	Date                pgtype.Date `json:"date"`
	Time                pgtype.Text `json:"time"`
	VenueName           pgtype.Text `json:"venue_name"`
	VenueAddress        pgtype.Text `json:"venue_address"`
	VenueHall           pgtype.Text `json:"venue_hall"`
	GroomAccount        []byte      `json:"groom_account"`
	BrideAccount        []byte      `json:"bride_account"`
	GroomFatherAccount  []byte      `json:"groom_father_account"`
	GroomMotherAccount  []byte      `json:"groom_mother_account"`
	BrideFatherAccount  []byte      `json:"bride_father_account"`
	BrideMotherAccount  []byte      `json:"bride_mother_account"`
	HostGroomID         pgtype.UUID `json:"host_groom_id"`
	HostBrideID         pgtype.UUID `json:"host_bride_id"`
	HostGroomFatherID   pgtype.UUID `json:"host_groom_father_id"`
	HostGroomMotherID   pgtype.UUID `json:"host_groom_mother_id"`
	HostBrideFatherID   pgtype.UUID `json:"host_bride_father_id"`
	HostBrideMotherID   pgtype.UUID `json:"host_bride_mother_id"`
}

func (q *Queries) UpdateWeddingInfo(ctx context.Context, arg UpdateWeddingInfoParams) (V3Wedding, error) {
	row := q.db.QueryRow(ctx, updateWeddingInfo,
		arg.ID,
		arg.GroomName,
		arg.BrideName,
		arg.GroomFatherName,
		arg.GroomMotherName,
		arg.BrideFatherName,
		arg.BrideMotherName,
		arg.GroomFatherDeceased,
		arg.GroomMotherDeceased,
		arg.BrideFatherDeceased,
		arg.BrideMotherDeceased,
		arg.Date,
		arg.Time,
		arg.VenueName,
		arg.VenueAddress,
		arg.VenueHall,
		arg.GroomAccount,
		arg.BrideAccount,
		arg.GroomFatherAccount,
		arg.GroomMotherAccount,
		arg.BrideFatherAccount,
		arg.BrideMotherAccount,
		arg.HostGroomID,
		arg.HostBrideID,
		arg.HostGroomFatherID,
		arg.HostGroomMotherID,
		arg.HostBrideFatherID,
		arg.HostBrideMotherID,
	)
	var i V3Wedding
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.HostGroomID,
		&i.HostBrideID,
		&i.HostGroomFatherID,
		&i.HostGroomMotherID,
		&i.HostBrideFatherID,
		&i.HostBrideMotherID,
		&i.GroomName,
		&i.BrideName,
		&i.GroomFatherName,
		&i.GroomMotherName,
		&i.BrideFatherName,
		&i.BrideMotherName,
		&i.GroomFatherDeceased,
		&i.GroomMotherDeceased,
		&i.BrideFatherDeceased,
		&i.BrideMotherDeceased,
		&i.Date,
		&i.Time,
		&i.VenueName,
		&i.VenueAddress,
		&i.VenueHall,
		&i.GroomAccount,
		&i.BrideAccount,
		&i.GroomFatherAccount,
		&i.GroomMotherAccount,
		&i.BrideFatherAccount,
		&i.BrideMotherAccount,
		&i.CreatedAt,
	)
	return i, err
}
