// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wedding_sui.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateLoungeSuiId = `-- name: UpdateLoungeSuiId :exec
UPDATE v3_wedding_lounges
SET sui_lounge_id = $2
WHERE wedding_id = $1
`

type UpdateLoungeSuiIdParams struct {
	WeddingID   pgtype.UUID `json:"wedding_id"`
	SuiLoungeID pgtype.Text `json:"sui_lounge_id"`
}

func (q *Queries) UpdateLoungeSuiId(ctx context.Context, arg UpdateLoungeSuiIdParams) error {
	_, err := q.db.Exec(ctx, updateLoungeSuiId, arg.WeddingID, arg.SuiLoungeID)
	return err
}

const updateWeddingSuiIds = `-- name: UpdateWeddingSuiIds :exec

UPDATE v3_weddings
SET sui_wedding_id = $2,
    sui_vault_id   = $3
WHERE id = $1
`

type UpdateWeddingSuiIdsParams struct {
	ID           pgtype.UUID `json:"id"`
	SuiWeddingID pgtype.Text `json:"sui_wedding_id"`
	SuiVaultID   pgtype.Text `json:"sui_vault_id"`
}

// Sui 온체인 오브젝트 ID dual-write (C7 데이터 브릿지).
// 호스트 웨딩 온체인 생성 후 발행 ID를 Supabase row에 저장. 온체인 실패 시 호출 안 함(null 유지).
func (q *Queries) UpdateWeddingSuiIds(ctx context.Context, arg UpdateWeddingSuiIdsParams) error {
	_, err := q.db.Exec(ctx, updateWeddingSuiIds, arg.ID, arg.SuiWeddingID, arg.SuiVaultID)
	return err
}
